### ISSUE TITLE
fix slurm rpm spec typo 

### ISSUE THREAD

**Issue by likueimo** [openhpc/ohpc#1017]
ref :  https://github.com/openhpc/ohpc/blob/v1.3.8.GA/components/rms/slurm/SPECS/slurm.spec#L710
```
  -d %{_sysconfdir} -g slurm -s /bin/nologin -r slurm -u 202
````

I think should be `/sbin/nologin`, not `/bin/nologin`

**Comment by koomie** [comment]
Agreed,@likueimo thanks for the report and @amblakem for the patch.

**Comment by koomie** [comment]
Latest slurm build passing in CI.
