### ISSUE TITLE
Please consider replacing pam_slurm.so with pam_slurm_adopt.so in OpenHPC manual  

### ISSUE THREAD

**Issue by likueimo** [openhpc/ohpc#1022]
OpenHPC manual mentioned slurm and pam_slurm.so
ref : https://github.com/openhpc/ohpc/releases/download/v1.3.8.GA/Install_guide-CentOS7-xCAT-Stateful-SLURM-1.3.8-x86_64.pdf

![image](https://user-images.githubusercontent.com/11157543/62427147-255a7600-b721-11e9-8010-500e61f47fab.png)

according this discussion [slurm bug 4098](https://bugs.schedmd.com/show_bug.cgi?id=4098), pam_slurm_adopt.so may be better than pam_slurm.so。

![image](https://user-images.githubusercontent.com/11157543/62427196-d234f300-b721-11e9-8a68-91886c385f34.png)

other ref:
1. https://slurm.schedmd.com/pam_slurm_adopt.html
2. https://www.suse.com/c/deploying-slurm-pam-modules-on-sle-compute-nodes/ 
![image](https://user-images.githubusercontent.com/11157543/62427261-fe04a880-b722-11e9-93fd-f7b9ff5444d4.png)

3. https://wiki.fysik.dtu.dk/niflheim/Slurm_configuration

side effect after changed :

Need to write more about this configuration (from ref 2.)

![image](https://user-images.githubusercontent.com/11157543/62427338-41134b80-b724-11e9-8db0-ee337780e3e6.png)

**Comment by koomie** [comment]
Our default slurm config targets exclusive node usage and also includes a post-execution script that terminates user processes. So, I think the net effect is the same for exclusive usage, but can look into `pam_slurm_adopt.so` if it is now preferred.

**Comment by likueimo** [comment]
@koomie OK !! Thank you !
I used slurm and OpenHPC only 6 months, so a lot of knowledge may not be accurate.

**Comment by sjpb** [comment]
Is it worth considering reopening this please? `pam_slurm_adopt` does have additional functionality and according to Slurm's own FAQ (see under [here](https://slurm.schedmd.com/faq.html#pam)):
> The pam_slurm_adopt module is highly recommended for most installations, and is documented in its own guide.
>
> pam_slurm is older and less functional.

**Comment by koomie** [comment]
I looked at this again a bit more and I think we prefer to stick with `pam_slurm.so` as it gives the desired functionality of limiting/enabling ssh for the user without forcing the site into other options. In particular, pam_slurm_adopt requires additional settings like use of the task/cgroup task plugin and either the proctrack/cgroup or the proctrack/cray_aries proctrack plugin.

Of course, this alternative pam module ships with the ohpc build in `slurm-pam_slurm-ohpc`, so sites who want to opt in to choose that over pam_slurm.so should have the ability to do so.
