### ISSUE TITLE
Fix for warewulf Stateful UEFI on aarch64

### ISSUE THREAD

**Issue by crbaird** [openhpc/ohpc#1027]
https://github.com/warewulf/warewulf3/pull/199

**Comment by NaohiroTamura** [comment]
hello,

warewulf/warewulf3#199 has already been merged.
Can we set the milestone to 1.3.9 too?
Because this issue is critical for aarch64 user.

Thanks.
Naohiro

**Comment by crbaird** [comment]
Patch landed in 4f08b35

**Comment by NaohiroTamura** [comment]
@koomie, @crbaird,

Thanks!
Naohiro
