### ISSUE TITLE
Support for Centos 7.7

### ISSUE THREAD

**Issue by dhilst** [openhpc/ohpc#1030]
Today if anybody issue and yum update on a centos 7.6 It gets upgraded to Centos 7.7, if OHPC won't work we end with and broken cluster. Is there any knowledge if is working or not?

I tried Centos vault but couldn't found the rpms there for 7.6, so I can't pin the versions

**Comment by amblakem** [comment]
The current version of OpenHPC (1.3.8.1) was recently [tested against CentOS 7.7](https://groups.io/g/OpenHPC-users/topic/can_openhpc_1_3_8_1_work_on/34294155?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,34294155 ) and looks like it should be working if you're not using packages that rely on a specific kernel version (EG. the lustre client packages).

**Comment by koomie** [comment]
Also, if you ever do want specific versions of the OS, you need to use the numbered path at valut.centos.org (or any mirror that keeps more than the latest version). For example, the repo path for 7.6 is:

http://vault.centos.org/7.6.1810/os/x86_64/

**Comment by dhilst** [comment]
Hi @koomie, yeah I'm using CentOS Vault

@amblakem Great news, thanks for sharing. So I considering this solved :)
