### ISSUE TITLE
MVAPICH2 cannot be installed if Mellanox OFED is used

### ISSUE THREAD

**Issue by viniciusferrao** [openhpc/ohpc#1031]
Hello,

I'm trying to use the Mellanox OFED with OpenHPC and everything works fine except the MVAPICH2. The problem is the missing libibmad.so.5, that's available on inbox drivers but not on Mellanox OFED, which ships libibmad.so.12.

    --> Finished Dependency Resolution
    Error: Package: mvapich2-gnu8-ohpc-2.3.1-3.1.ohpc.1.3.8.x86_64 (OpenHPC-updates)
           Requires: libibmad.so.5()(64bit)
           Available: infiniband-diags-2.1.0-1.el7.x86_64 (base)
               libibmad.so.5()(64bit)
           Available: libibmad-1.3.13-1.el7.x86_64 (base)
               libibmad.so.5()(64bit)
           Installed: infiniband-diags-5.4.0.MLNX20190422.d1468cd-0.1.46101.x86_64 (@mlnx_ofed_4.6-1.0.1.1_base)
               Not found
           Installed: libibmad-5.4.0.MLNX20190423.1d917ae-0.1.46101.x86_64 (@mlnx_ofed_4.6-1.0.1.1_base)
              ~libibmad.so.12()(64bit)
    Error: Package: mvapich2-gnu8-ohpc-2.3.1-3.1.ohpc.1.3.8.x86_64 (OpenHPC-updates)
           Requires: libibmad.so.5(IBMAD_1.3)(64bit)
           Available: infiniband-diags-2.1.0-1.el7.x86_64 (base)
               libibmad.so.5(IBMAD_1.3)(64bit)
           Available: libibmad-1.3.13-1.el7.x86_64 (base)
               libibmad.so.5(IBMAD_1.3)(64bit)
           Installed: infiniband-diags-5.4.0.MLNX20190422.d1468cd-0.1.46101.x86_64 (@mlnx_ofed_4.6-1.0.1.1_base)
               Not found
           Installed: libibmad-5.4.0.MLNX20190423.1d917ae-0.1.46101.x86_64 (@mlnx_ofed_4.6-1.0.1.1_base)
              ~libibmad.so.12(IBMAD_1.3)(64bit)
              ~libibmad.so.12(IBMAD_1.4)(64bit)
     You could try using --skip-broken to work around the problem

     You could try running: rpm -Va --nofiles --nodigest

There's a way to fix this issue?

**Comment by adrianreber** [comment]
Looking at that output I would say that the Mellanox OFED brings its own libibmad with a different SO name than the one required by OpenHPC's mvapich2 (requires: libibmad.so.5). libibmad.so.5 seems to be part of libibmad and if you cannot install it in parallel to the libibmad from Mellanox it will not work.

Not knowing in which paths the libraries are installed this could still work. If the Mellanox OFED is not installed in any default location this might just be a case of RPM wrongly detecting provides/requires during build. To avoid errors like this OpenHPC uses 'coloring' for its Requires/Provides.

With the information you posted it is not clear if this can be solved. It cannot be solved at the RPM dependency layer at least. But if the Mellanox OFED is installed in a non-default location and if the loader cannot find those libraries it still can be made to work.

**Comment by viniciusferrao** [comment]
Hello Adrian, I’m sorry, but I think I don’t understood exactly what you mean.

Are you saying that I should search for the libibmad.so.5 in the filesystem to see if there’s an hope to fix the issue? Is this correct?

The MLNX OFED, was installed using the repository, so it is in the default locations. But I can double check if you want.


There’s something I can do here to help solve the issue?

**Comment by jabl** [comment]
Looking at https://docs.mellanox.com/display/MLNXOFEDv461000/Installing+Mellanox+OFED there's an alternative installation method using upstream libraries. If you use the mlnxofedinstall script, add the `--upstream-libs` option, or if using the rpm repo in the repo URL the last part should be the RPMS_UPSTREAM_LIBS directory rather than the RPMS directory.

I haven't tried this myself, but looking at the contents of the RPMS_UPSTREAM_LIBS directory, it seems to mostly install the kernel components of MLNX_OFED, and the rest comes from the distro + a (modified?) version of the upstream rdma-core package. So this might have a higher chance of working with OpenHPC instead of using the full MLNX_OFED installation.

**Comment by viniciusferrao** [comment]
@jabl; I can confirm that using the "upstream libs" solved the issue. I was able to Install the OFED packages from Mellanox with MVAPICH2 shipped from OpenHPC.

Thank you!
