### ISSUE TITLE
Lustre 2.12.0 / CentOS 7.7: no support

### ISSUE THREAD

**Issue by mtds** [openhpc/ohpc#1036]
I saw there is already the opened issue #1030 related to CentOS 7.7 but my question is more specifically related to Lustre.

As written in the subject, it looks like there's no support (yet) for Lustre client **2.12.0** in CentOS 7.7 with the kernel version **3.10.0-1062** while with CentOS 7.6 and kernel version **3.10.0-957** there are instead no problems.

According to the [OpenHPC roadmap](https://github.com/openhpc/ohpc/wiki/Release-History-and-Roadmap) it seems that the latest version available is **1.3.8.1** and the next one is the **2.0**, which will support CentOS 8 among other things.

* Are there plans to keep supporting Lustre with the next minor version of RHEL/CentOS (7.7, 7.8, etc.) or it will be required to move toward version 8.x? 
* Will it be another minor release (e.g. 1.3.8.2) with support for Lustre clients and new kernels? 

Thanks in advance!

**Comment by jabl** [comment]
FWIW Lustre 2.12.3 should be released soon (they promised end of September..), and will have CentOS 7.7 support.

**Comment by koomie** [comment]
Good - I tried to cherry-pick some patches on the 2.12 branch to try and address the build issue, but haven't been successful just yet. Hopefully we can just rely on 2.12.3.

**Comment by jabl** [comment]
Lustre 2.12.3 was released a few days ago: http://lustre.org/lustre-2-12-3-released/

**Comment by koomie** [comment]
Thanks. Latest version builds with 7.7 and we will include this in next 1.3.9 release.

https://build.openhpc.community/package/show/OpenHPC:1.3:Update9:Factory/lustre-client
