### ISSUE TITLE
PBS Pro (v19.1.3)

### ISSUE THREAD

**Issue by mike0042** [openhpc/ohpc#1050]
https://github.com/PBSPro/pbspro/releases
https://github.com/PBSPro/pbspro/archive/v19.1.3.tar.gz

**Comment by mike0042** [comment]
@koomie - Shall I update this in master, 1.3.9, and 2.0?

**Comment by mike0042** [comment]
PR #1052 submitted for obs/OpenHPC_1.3.9_Factory

**Comment by koomie** [comment]
Tests passing in CI.
