### ISSUE TITLE
Libfabric support in OpenMPI

### ISSUE THREAD

**Issue by ChrisDowning** [openhpc/ohpc#1051]
Could we include [libfabric](https://github.com/ofiwg/libfabric) support within OpenMPI for 1.3.9 and 2.0?

I'm still getting to grips with the spec files, but from what I can tell it would require something like:
```%ifarch aarch64 || ppc64le
%define with_libfabric 0 
%else 
%define with_libfabric 1 
%endif

...

%if %{with_libfabric}
BuildRequires:  libfabric >= 1.8
%endif

...

%if %{with_libfabric}
  BASEFLAGS="$BASEFLAGS --with-libfabric=<dir>"
%endif
```

Libfabric includes PSM and PSM2 providers (as well as a bunch of others), so it might make sense to just remove references to PSM/PSM2 and rely on libfabric for everything.

Version 1.7 looks to be available in CentOS 7 right now so could be just installed as a dependency. My interest is in 1.8, which adds the "efa" provider to support the AWS Elastic Fabric Adapter low-latency networking option.

Please let me know if either a normal package dependency option or the addition of a manually installed newer libfabric package* are viable. If a new package submission is going to be required I can raise that, otherwise I will attempt to make the changes directly.

\* which would then be similar to PMIx from an OpenMPI standpoint I guess - ie installed separately then loaded as a module?

**Comment by viniciusferrao** [comment]
+1

I'm not sure, but I think this may solve the requirement of libpsm2 on compute images even on non PSM2 machines, since OpenMPI requires it and does not work if the lib is missing on the compute images.

**Comment by adrianreber** [comment]
When we discussed this a few weeks ago the decision was to enable libfabric support for the upcoming OpenHPC 2.0 release.

**Comment by adrianreber** [comment]
libfabric is in use for some time now
