### ISSUE TITLE
Support for OpenMPI v4.0 + UCX

### ISSUE THREAD

**Issue by mtds** [openhpc/ohpc#1080]
Is there a plan to add OpenMPI version **4.0.x** with UCX support?
If not in the next minor upgrades (e.g. from 1.3.x to 1.4) maybe directly in the *2.0* tree?

I saw there is already an opened issue about Open UCX (#921) but I did not see any
other opened issues about newer version of OpenMPI with UCX support.

According to the [OpenMPI README](https://github.com/open-mpi/ompi/blob/v4.0.x/README) released with version *4.0*, support for Infiniband and RoCE through the *openib* plugin is deprecated and superseded by the ucx PML component (see line **740** of the README).

**Comment by amblakem** [comment]
Right now openmpi4 is targeted for the 2.0 release.  There are a few more 2.0 highlights covered in the [meeting notes](https://github.com/openhpc/ohpc/wiki/files/OpenHPC-TSC-Board-20191023.pdf) from the last TSC meeting.  I'm not sure specifically about UCX, but given that #921 has a target milestone of 2.0 I'm thinking that is a likely candidate.

**Comment by viniciusferrao** [comment]
Hello, there's a way to keep OpenMPI 3 too in OpenHPC 2.0? I'm requesting this because of this issue: https://www-lb.open-mpi.org/software/ompi/major-changes.php

> Legacy MPI-1 symbols that were deprecated in MPI-2.0 in 1996 and then deleted from the MPI-3.0 specification in 2012 are no longer prototyped in mpi.h by default. This will almost certainly cause some legacy MPI applications to fail to compile.

So the version can be selected through the modules framework and we can keep the compatibility with legacy code needing the removed symbols?

**Comment by boegel** [comment]
Another option is to configure OpenMPI 4.x with `--enable-mpi1-compatibility`....

**Comment by koomie** [comment]
I would prefer @boegel's suggestion over maintaining a separate build for symbols that were deprecated over 20 years ago.

**Comment by fcannini** [comment]
@boegel @koomie There's a warning about that in the link that @viniciusferrao posted.
```
... WARNING: These legacy symbols may disappear
 in a future major release series of Open MPI!.
```

IMHO, the less risky option would be to have both `openmpi3` and `openmpi4` in 2.0 release with a warning about it, and then drop the 3.x OpenMPI afterwards (e.g: OHPC 3.0)

**Comment by koomie** [comment]
Thanks for pointing that out. I will bring this up for discussion at our next TSC meeting but I'm definitely in the camp that strongly thinks a 20 year warning is plenty...

Barring another motivating reason I really don't want to carry both the 3/4 variants in 2.0 out of the gate.  I'm not against the `--enable-mpi1-compatibility` option for 4.x, but that may also just be kicking the proverbial can down the road ...

**Comment by fcannini** [comment]
@koomie I'm of the same opinion as yours, I just rather not be caught with my pants down when suddenly prof John Doe's software doesn't compile anymore. ;)

**Comment by adrianreber** [comment]
Closing as 3.x switched to Open MPI 5
