### ISSUE TITLE
update test-suite to use distro provided bats

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#1084]
Leap15.1 and EPEL now have `bats`, so we can use that and remove the version carried around within test suite.

**Comment by koomie** [comment]
Reminder that we modified our local bats to get some extra junit/xml output for use with Jenkins. So, leaving as is for now.

**Comment by adrianreber** [comment]
Switch to bats from EPEL and Leap for 3.x. bats has native support for junit for a long time now.
