### ISSUE TITLE
spack (v0.15.0)

### ISSUE THREAD

**Issue by viniciusferrao** [openhpc/ohpc#1090]
0.13.1 was released 20 days ago, can we get an upgraded package?
https://github.com/spack/spack/releases

**Comment by hseara** [comment]
Spack is currently in the v0.14.2.

**Comment by crbaird** [comment]
https://github.com/spack/spack/releases

**Comment by hseara** [comment]
Looking forward to seeing spack 1.5.0 in 2.0. 

It is a must when working with some packages due to long paths. Also, the new feature of virtual packages as non-buildable will be very handy when combining spack with ohpc packages.

https://github.com/spack/spack/pull/14934

**Comment by koomie** [comment]
Tests passing in CI.
