### ISSUE TITLE
Upgrade Slurm to 15.08.6 (minor security issue)

### ISSUE THREAD

**Issue by chrissamuel** [openhpc/ohpc#111]
The Slurm 15.08.4 announcement from Danny says:

> One notable fix is found in commits 8e66e2677 and d72f132d42 which will fix a
> slurmctld bug in which a pending job array could be canceled by a user different
> from the owner or the administrator. This appears to exist in the 15.08.* as well
> as the 14.11.* branches. 

This is a minor security issue but either the commits should be cherry picked or (preferably) Slurm should be upgraded to the current version.

**Comment by JohnWestlund** [comment]
@chrissamuel Thanks for pointing this out!

**Comment by JohnWestlund** [comment]
Upgraded the version in v1.1. Will get an update for v1.0 rolling

**Comment by chrissamuel** [comment]
On Sat, 21 Nov 2015 12:48:57 PM John Westlund wrote:

> Upgraded the version in v1.1. Will get an update for v1.0 rolling

Thanks so much John!

-- 
 Chris Samuel  :  http://www.csamuel.org/  :  Melbourne, VIC

**Comment by koomie** [comment]
Passing in CI tests.
