### ISSUE TITLE
llvm5 + openmpi

### ISSUE THREAD

**Issue by geoffrey4444** [openhpc/ohpc#1118]
Is it possible on an ohpc cluster to install openmpi using llvm5? I have a cluster working with openmpi compiled with gnu7, but I'd like to instead use llvm5. I tried using `yum list available`, but I couldn't find a package for openmpi + llvm.

**Comment by adrianreber** [comment]
No, we only provide llvm as a standalone compiler. The whole stack (including openmpi) is only available compiled with GCC and the Intel compiler.
