### ISSUE TITLE
Missing file in slurm-sql-ohpc RPM on CentOS 7.1

### ISSUE THREAD

**Issue by eshelman** [openhpc/ohpc#113]
Hi Folks,

The RPM build for slurm-sql-ohpc does not include any files (just an empty directory):
````
[root@sms ~]# rpm -qa | grep slurm-sql
slurm-sql-ohpc-15.08.1-4.1.x86_64

[root@sms ~]# rpm -ql slurm-sql-ohpc
/usr/lib64/slurm
````

It should be including `accounting_storage_mysql.so`

I don't see anything wrong with the spec file upon first glance. The build logs don't appear to be publicly available - I was going to take a peek at them.

**Comment by tron88** [comment]
Hi Eliot,
Thanks for bringing this to our attention. 
I also could not find the build logs on the OHPC build service. We will need to get this sorted out as well.

P.S. I did look at our internal build and it also seemed to not have the accounting_storage_mysql.so file.

**Comment by JohnWestlund** [comment]
The spec file doesn't have any files included with that package. Just a directory. That is likely the problem. The question then is why our spec file seems to have dropped the file to include the .so. 



—

**Comment by JohnWestlund** [comment]
@eshelman Here's the issue:

```
[   66s] checking for mysql_config... no
[   66s] configure: WARNING: *** mysql_config not found. Evidently no MySQL development libs installed on system.
```

MySQL isn't getting picked up in the build and so this library isn't being built.

**Comment by JohnWestlund** [comment]
@eshelman I've committed a fix internally that should resolve the issue. Our internal buildfarm appears to be wedged so I'll have to report back after getting the builds going again as to whether there is a resolution.

**Comment by JohnWestlund** [comment]
@eshelman `slurm-sql-ohpc-15.08.1-4.1.x86_64` now contains the library. We're still working on our update repo procedure, but it will be ready when we have that it in place. Thanks.

**Comment by eshelman** [comment]
Great - thanks very much for looking into this so quickly!
