### ISSUE TITLE
openhpc Centos8

### ISSUE THREAD

**Issue by javir86** [openhpc/ohpc#1135]
Hi,
I'm trying to install openHPC on Centos 8 and when i execute the command:
yum install ohpc-base
I have the following issue:

And with the command:
yum install ohpc-warewulf
The following issue.

 - cannot install the best candidate for the job
  - nothing provides dhcp needed by warewulf-provision-server-ohpc-3.7pre-66.1.x86_64
  - nothing provides dhcp needed by warewulf-provision-server-ohpc-3.8.1-56.1.ohpc.1.3.9.x86_64
  - nothing provides policycoreutils-python needed by warewulf-provision-server-ohpc-3.8.1-56.1.ohpc.1.3.9.x86_64

For the first problem i tried to install chrony but the issue is still there. 
Thanks.

**Comment by adrianreber** [comment]
Unfortunately you are too fast. There is no OpenHPC release yet which supports CentOS 8. We are working on it.

**Comment by yixuan178** [comment]
> Unfortunately you are too fast. There is no OpenHPC release yet which supports CentOS 8. We are working on it.
Hello Adrian,
any schedule update for support centos? do we plan to support centos 8.1? since current there have 8.1? 
thanks,
Eugene

**Comment by koomie** [comment]
Yes, the current intercept target is to support CentOS 8.1 and Leap 15.1; no firm release timeline just yet.

**Comment by yixuan178** [comment]
> Yes, the current intercept target is to support CentOS 8.1 and Leap 15.1; no firm release timeline just yet.

hello Karl,
I see from wiki page, 2h this year should have 2.0, does it mean it will be ready after April?  
will we have a preview version before that date? 
Thanks,
Eugene

**Comment by koomie** [comment]
CentOS 8 support included in [2.x series](https://github.com/openhpc/ohpc/wiki/2.x)
