### ISSUE TITLE
Remove obsolete features from RPM .specs

### ISSUE THREAD

**Issue by jcsiadal** [openhpc/ohpc#1139]
Remove features no longer implemented in rpm. Creating this issue as a reminder, since 2.0 is a good time to make the RPM specs current (remove deprecations before they become errors).

Specifically, the following tags are deprecated:
Group:
BuildRoot:
PreReq:

%clean
If the %clean section only contains "rm -rf %buildroot", then it's redundant and should be removed. Cleanup is automatic now.

**Comment by adrianreber** [comment]
Having no `Buildroot:` in the spec file is even verified by Travis for each pull request, so that is already solved.

git grep also claims no `%clean` anywhere.

PreReq exists 5 times and having Group is actually enforced by Travis and is part of each spec file.

**Comment by jcsiadal** [comment]
Thanks for checking. Sounds like a quick update needed for Travis to remove enforcement. I don't think we need to enforce tag removal yet. I can include this when I submit the updated WW packages this week.

We should add a Prereq check to Travis. Prereq is now interpreted as Requires(Pre), and that may not be the specfile authors intent since Requires(Pre) can be removed after RPM installation.

**Comment by koomie** [comment]
We most definitely rely on a specific Group tag taxonomy for machine-generating the package manifests that are included in the documentation. Looks like RHEL8 and Leap15 also continue to use; would prefer to not rock the boat on that (and we really do use them, which was part of the motivation to add to the Travis check)
