### ISSUE TITLE
Register with LANANA

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#114]
Issue generated from mailing list message:
https://groups.io/g/OpenHPC-users/message/22

> The FHS also dictates the path names for packages themselves, so whilst
> you can use /opt/${package} easily if you want to use /opt/ohpc then you
> should register it with LANANA as it's not currently taken here:
> 
> http://www.lanana.org/lsbreg/providers/providers.txt

**Comment by JohnWestlund** [comment]
Bug submitted:
https://lsbbugs.linuxfoundation.org/show_bug.cgi?id=4135

**Comment by koomie** [comment]
Krikey. No update to the submission in 10 months. Going to leave this open as a tracker, but remove  particular milestone.

**Comment by koomie** [comment]
Closing this out with no progress.
