### ISSUE TITLE
Could not import py3-mpi4py in python

### ISSUE THREAD

**Issue by gassyfeve** [openhpc/ohpc#1151]
I have installed python3-mpi4py-gnu8-openmpi3-ohpc and loaded all necessary module through load.
But I found I could import mpi4py in python.

I found all python module was installed in `/opt/ohpc/pub/libs/gnu8/openmpi3/mpi4py/3.0.2/lib64/python3.6/site-packages/`.
But in modulefile, PYTHONPATH was defined as `/opt/ohpc/pub/libs/gnu8/openmpi3/mpi4py/3.0.2/lib64/python3.4/site-packages`.

**Comment by chuckatkins** [comment]
Duplicate of #1093
