### ISSUE TITLE
arm hpc package build failures

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#1153]
This ticket is used to track observed build failures with the latest arm hpc compiler for 3rd party ohpc packages.

**Comment by koomie** [comment]
- [x] scalapack (presumably update to use blas from armpl)
- [x] scotch : ```clang-9: error: unknown argument: '-fstack-clash-protection'```
- [x] superlu: (same fstack-clash-protection)
- [ ] extrae: (https://obs.openhpc.community/package/show/OpenHPC:2.0:Factory/extrae-arm1-mpich)
- [ ] mumps: (needs linkage to armpl for blas, https://obs.openhpc.community/package/show/OpenHPC:2.0:Factory/extrae-arm1-mpich)
- [ ] plasma: (needs linkage to armpl for blas)
- [ ] phdf5: `clang-9: error: unknown argument: '-soname'` (https://obs.openhpc.community/package/live_build_log/OpenHPC:2.0:Factory/phdf5-arm1-mpich/CentOS_8/aarch64)
- [x] sionlib: looks like it may be using gfortran (https://obs.openhpc.community/package/live_build_log/OpenHPC:2.0:Factory/sionlib-arm1-mpich/CentOS_8/aarch64)
- [ ] hypre: likely needs linkage to armpl for blas

**Comment by srinathv** [comment]
PR issed for scalapack and scotch-serial ( I think that ptscotch will also work since I did edit some of those files for consitency). I did not see a paralle-scotch package on openhpc:factor branch 2.0

**Comment by srinathv** [comment]
I just noticed that I have done scalapack + mpich but not openmpi.  I'll finish that dual set and move onto to superlu (dual set).

**Comment by koomie** [comment]
> I just noticed that I have done scalapack + mpich but not openmpi. I'll finish that dual set and move onto to superlu (dual set).

scalapack is built in factory for both mpich and openmpi, so we're good on that.

**Comment by srinathv** [comment]
extrae:  seeing a linker issue that I've sent to the compiler team
`/opt/arm/gcc-9.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/gcc/aarch64-linux-gnu/9.2.0/../../../../aarch64-linux-gnu/bin/ld: /opt/arm/gcc-9.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/libbfd.a(bfd.o)(.text+0xec): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `stdout@@GLIBC_2.17'`

**Comment by srinathv** [comment]
mumps and scotch I think are working (sans PR)

**Comment by koomie** [comment]
Seems there is still an issue with plasma. Although the build completes, there are no plasma libs included in the install. Compare, for example, with gnu9 build:

```
[ohpc-test@sms201 plasma]$ ls $PLASMA_LIB
liblapacke.so  liblapacke.so.0
[ohpc-test@sms201 plasma]$ module swap arm1 gnu9

Activating Modules:
  1) openblas/0.3.7

Due to MODULEPATH changes, the following have been reloaded:
  1) metis/5.1.0     2) openmpi4/4.0.3     3) plasma/2.8.0

[ohpc-test@sms201 plasma]$ ls $PLASMA_LIB
libcoreblas.so    libcoreblasqw.so    liblapacke.so    libplasma.so    libquark.so    pkgconfig
libcoreblas.so.0  libcoreblasqw.so.0  liblapacke.so.0  libplasma.so.0  libquark.so.0
```

**Comment by srinathv** [comment]
Is plamsa still not installing correctly via the ACFL (arm compiler)?
