### ISSUE TITLE
'Packages' link at Wiki main pages points to outdated component list

### ISSUE THREAD

**Issue by TomTheBear** [openhpc/ohpc#1163]
The 'Packages' link at https://github.com/openhpc/ohpc/wiki points to [Component-List-v1.3.3](https://github.com/openhpc/ohpc/wiki/Component-List-v1.3.3) and not to the current [Component-List-v1.3.8](https://github.com/openhpc/ohpc/wiki/Component-List-v1.3.8).

**Comment by koomie** [comment]
Oops - good catch. I have updated the link to latest (v1.3.9).
