### ISSUE TITLE
CentOS 7 image conflict in 1.3.9 install guide for SLURM xCAT stateless

### ISSUE THREAD

**Issue by brattex** [openhpc/ohpc#1165]
I have observed a minor error in the 1.3.9 install guide and am sure it's been picked up before but it's still in the guide, so I just wanted to check in...

**3.9.1** points us to download CentOS-7-x86 64-DVD-1810.iso which is Centos 7.6.

The guide then does **lsdef -t osimage** and shows **centos7.6***

But the CHROOT is trying to do **centos7.7** and **genimage** is trying to do 7.7 ...

Is the original ISO image the error (i.e. 7.6) or is the reference to 7.7 later the error?

If able to, I am also happy to make the correction but I am not sure which is the error - 7.6 or 7.7.

Appears the same in both:
https://github.com/openhpc/ohpc/releases/download/v1.3.9.GA/Install_guide-CentOS7-xCAT-Stateless-SLURM-1.3.9-x86_64.pdf

and

https://github.com/openhpc/ohpc/releases/download/v1.3.9.GA/Install_guide-CentOS7-xCAT-Stateful-SLURM-1.3.9-x86_64.pdf

**Comment by koomie** [comment]
Thank you for the report. the `lsdef` output should indeed have  said centos7.7 and I have updated the two xCAT installation guides accordingly.
