### ISSUE TITLE
question about hwloc build with slurm-ohpc and openmpi-ohpc

### ISSUE THREAD

**Issue by likueimo** [openhpc/ohpc#1170]
OpenHPC offer [hwloc-ohpc 2.1.0](https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.9_Factory/components/dev-tools/hwloc/SPECS/hwloc.spec). 
However, [slurm-ohpc](https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.9_Factory/components/rms/slurm/SPECS/slurm.spec) and [openmpi-ohpc](https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.9_Factory/components/mpi-families/openmpi/SPECS/openmpi.spec) compile with `hwloc 1.11` (from linux distribution , like as `yum install hwloc` and `yum install hwloc-devel`).  
So, my question is that why `slurm-ohpc` and `openmpi-ohpc` build with `hwloc` rather than `hwloc-ohpc` ?
Thank you !

**Comment by koomie** [comment]
The reason for this is that slurm is required to run without any assistance from the `lmod` modules system. ie, the hwloc library must be installed into a fixed path.

**Comment by likueimo** [comment]
@koomie Thank you for your quick reply !
(I spend hours thinking on this question ...😂)

**Comment by likueimo** [comment]
@koomie Sorry, I re-open this issue. One more question.  
According to your reply, I notice that slurm build with `pmix-ohpc`.[ref: slurm spec](https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.9_Factory/components/rms/slurm/SPECS/slurm.spec)
`--with-pmix=/opt/ohpc/admin/pmix` [ref: build slurm log](https://build.openhpc.community/build/OpenHPC:1.3:Update8:U1/CentOS_7/x86_64/slurm/_log)  
Therefore, I am still curious that why `slurm-ohpc` build with `hwloc` rather than `hwloc-ohpc`. 
Thank you !

**Comment by likueimo** [comment]
I apologize for so much question. 
I think what I mean is that if any possible,  
maybe next time `slurm-ohpc`/`openmpi-ohpc` can build with `hwloc-ohpc`.  
Thank you !

**Comment by adrianreber** [comment]
@likueimo Are you missing something with hwloc version provided by the operating system?

**Comment by likueimo** [comment]
@adrianreber   
Sorry, this is my problem.  
I am worried about users who compiling Open MPI 4.  
Users would like to compile Open MPI 4 with `hwloc-ohpc` and `pmix-ohpc`. 

In this situation,
slurm-ohpc compile with `hwloc 1.11`
User's Open MPI 4 compile with `hwloc 2.1.0`

So I am worried that `srun` commmand may not work or something broken. (I am not sure)

**Comment by likueimo** [comment]
Many thanks both of you reply my question !  
I learned a lot from OpenHPC !
I think this is just a question not an issue. So I close it. :)   
Thanks for developing OpenHPC !
