### ISSUE TITLE
how to export YUM_MIRRORS correctly?

### ISSUE THREAD

**Issue by everett-moon** [openhpc/ohpc#1179]
I have exported via command `export YUM_MIRRORS=http://mirrors.ustc.edu.cn/centos/7.7.1908/os/x86_64/`, But it still download file from mirrors.centos.org, the default one is too slow.

**Comment by koomie** [comment]
Did you get this sorted out. I believe it should be `YUM_MIRROR` (not `YUM_MIRRORS`)
