### ISSUE TITLE
warewulf provision failed both ohpc 1.3.7 and 1.3.8

### ISSUE THREAD

**Issue by everett-moon** [openhpc/ohpc#1180]
I have speed three days to deploy openhpc by the recipe.sh script. I have tried two version of ohpc releases on my machines.  Unfortunately, none of them were successful.

warewulf+slurm 1.3.7~1.3.8
OS: Centos7.6 and CentOS7.7

![image](https://user-images.githubusercontent.com/44184916/78208385-dbf03f80-74d6-11ea-990d-3eeeb0d1cc1f.png)

This really make me crazy!

**Comment by koomie** [comment]
Were you able to PXE boot a host?
