### ISSUE TITLE
Ref #1165 - CentOS7.6 DVD image referenced for CentOS7.7 installation

### ISSUE THREAD

**Issue by brattex** [openhpc/ohpc#1182]
Again, in 3.9.1:

> In this recipe, the
relevant ISO image is CentOS-7-x86 64-DVD-1810.iso (available from the CentOS mirrors).

But that DVD ISO is 7.6, we should be pulling 1908.

In the sample code line:

`[sms]# copycds ${iso_path}/CentOS-7-x86_64-DVD-1810.iso`

That should also be 1908 to be CentOS 7.7 ...

**Comment by koomie** [comment]
Thanks for catching this as well. xCAT recipes have been updated to reflect this.
