### ISSUE TITLE
Remove requirement for suse-release in ohpc-release

### ISSUE THREAD

**Issue by jcsiadal** [openhpc/ohpc#1186]
The sles-release 15.1 RPM doesn't "provide" suse-release. OpenHPC 2.0 should not prevent installation on the equivalent SLES without forcing RPMs.

One option is "distribution release", which is a virtual package provided by both openSUSE-release and sles-release.

**Comment by koomie** [comment]
I agree the intent is to also allow installation on SLES 15.  However, the problem with `distribution-release` is that there is no version associated with it.

Digging a bit more though, it seems that the rpm on SLE15/Leap15 is new enough to support conditionals for rpm requirements.  So, I've updated to have minimum version checks for either `suse-release` or `sles-release`.
