### ISSUE TITLE
magpie

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#1188]
https://github.com/LLNL/magpie

**Comment by jcsiadal** [comment]
@koomie, can you assign this to me? I can work with our internal team to get a build this week. The goal is to detect the RM in use and pre-configure appropriately.

**Comment by koomie** [comment]
Added a very basic module test for CI testing which is now passing in CI. This really needs to be expanded for the future to have a minimal working example that pulls down a big data analysis package and runs their equivalent "hello world" thru the RMS.
