### ISSUE TITLE
superlu_dist (v4.2)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#119]
09/25/2015
http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_dist_4.2.tar.gz

**Comment by koomie** [comment]
Updates OBS config for superlu_dist to use 1.1 branch.

**Comment by koomie** [comment]
@crbaird, I have updated the .spec file to pull down version 4.2, but did not check whether the previously applied patches are still relevant. Can you check if you still need/want them?  Thanks.

**Comment by crbaird** [comment]
Building in 1.1

**Comment by koomie** [comment]
CI tests passing.
