### ISSUE TITLE
Suggest StackHPC OpenHPC Ansible role for User Contributions wiki page

### ISSUE THREAD

**Issue by sjpb** [openhpc/ohpc#1199]
The page https://github.com/openhpc/ohpc/wiki/User-Resources lists a couple of "Ansible based recipes" for installing OpenHPC.

We ([StackHPC](https://www.stackhpc.com/)) have an Ansible role at https://github.com/stackhpc/ansible-role-openhpc which I'd like to propose for inclusion there too. Key features of it are:
- Because it's a *role* its more modular and focussed than a playbook, making minimal assumptions about the target cluster. E.g. it doesn't require any particular cluster filesystem or cluster control/admin software - anything could be used.
- It, or code based on it, is currently in production use on several HPC systems:
  - The [JASMIN](https://help.jasmin.ac.uk/article/4799-cluster-as-a-service-slurm) climate and earth-system science data analysis system.
  - The Square Kilometer Array Science Data [Performance Prototype Platform (ALaSKA)](http://ska-sdp.org/sites/default/files/attachments/ska-tel-sdp-0000151_02_sdpp3alaskareport_part_1_-_signed.pdf).
  - For application deployment on [IRIS](https://www.iris.ac.uk/) infrastructure for the [Euclid](https://sci.esa.int/web/euclid) space telescope.
- It's available from [Ansible Galaxy](https://galaxy.ansible.com/stackhpc/openhpc).
- It's under active development.

Unfortunately it seems there is no way to make a PR on the wiki else I'd have done that!

**Comment by koomie** [comment]
Thanks for this suggestion - I added a link to your github on the User-Resources page.
