### ISSUE TITLE
lmod (v6.0.24)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#120]
https://github.com/TACC/Lmod/releases

**Comment by boegel** [comment]
did you mean 6.0.24?

**Comment by JohnWestlund** [comment]
@boegel yes, thanks for catching my typo!

**Comment by koomie** [comment]
Updated obs config for lmod to use 1.1 branch.

**Comment by koomie** [comment]
v6.0.24 now building for centos7.1/sles12.

**Comment by koomie** [comment]
lmod tests passing for centos7.2/sles12sp1.
