### ISSUE TITLE
gcc (v10.1)

### ISSUE THREAD

**Issue by viniciusferrao** [openhpc/ohpc#1209]
Hello, I would like to suggest GCC 10.1 support for the upcoming 2.0 release.

It is released on May 7th, so it should be on time: https://gcc.gnu.org/gcc-10/

**Comment by koomie** [comment]
I'm a bit gun shy on this as we just about have things cooperating with gcc9.

**Comment by koomie** [comment]
Superseded by gcc 12 that is coming in next release.
