### ISSUE TITLE
lua-posix (v33.2.1)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#121]
03/01/2015
https://github.com/luaposix/luaposix

**Comment by JohnWestlund** [comment]
Updating to v33.3.1 causes `lmod` to fail with:
```
/bin/lua: /usr/share/lua/5.1/posix/init.lua:17: module 'bit32' not found:
	no field package.preload['bit32']
	no file '/opt/ohpc/admin/lmod/lmod/libexec/bit32.lua'
	no file '/opt/ohpc/admin/lmod/lmod/libexec/../tools/bit32.lua'
	no file '/opt/ohpc/admin/lmod/lmod/libexec/../shells/bit32.lua'
	no file '/opt/ohpc/admin/lmod/lmod/libexec/bit32/init.lua'
	no file './bit32.lua'
	no file '/usr/share/lua/5.1/bit32.lua'
	no file '/usr/share/lua/5.1/bit32/init.lua'
	no file '/usr/lib64/lua/5.1/bit32.lua'
	no file '/usr/lib64/lua/5.1/bit32/init.lua'
	no file '/opt/ohpc/admin/lmod/lmod/libexec/../lib/bit32.so'
	no file './bit32.so'
	no file '/usr/lib64/lua/5.1/bit32.so'
	no file '/usr/lib64/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/share/lua/5.1/posix/init.lua:17: in main chunk
	[C]: in function 'require'
	/opt/ohpc/admin/lmod/lmod/libexec/../tools/fileOps.lua:35: in main chunk
	[C]: in function 'require'
	/opt/ohpc/admin/lmod/lmod/libexec/myGlobals.lua:40: in main chunk
	[C]: in function 'require'
	/opt/ohpc/admin/lmod/lmod/libexec/lmod:76: in main chunk
	[C]: ?
```

The resolution looks like `Lua` needs to be built with the following flags: `-DLUA_COMPAT_BITLIB -DLUA_COMPAT_APIINTCASTS` per https://github.com/luaposix/luaposix/issues/224

We're currently using the base OS version of Lua (5.1 CentOS, 5.2 SLES -- with 5.3 available). It doesn't look like we can update this package until we resolve the issue in `Lua`.

**Comment by koomie** [comment]
As this package is simply a dependency, I think it's reasonable to keep it at the same v33.2.1 version so that the distro versions of lua can continue to be used.  However, the build out of the box for sles12 was failing and I've adjusted the .spec slightly to use disto-provided autotools for the build.

**Comment by boegel** [comment]
Maybe @rtmclay can help figure this out?

**Comment by koomie** [comment]
Builds now enabled for centos7/sles12.

**Comment by koomie** [comment]
@boegel, I think we're probably ok here. The latest lmod is now building ok as long as we stick with v33.2.1.  We'll have to get to the point where regression tests run ok to say more definitively, but at least the build is fine and we can stick with using distro-provided lua.

**Comment by koomie** [comment]
lmod working wiht this depencency (issue #120) on latest distro versions. Closing this out.
