### ISSUE TITLE
PBS Pro (v19.1.3) root folder of source package changed

### ISSUE THREAD

**Issue by gassyfeve** [openhpc/ohpc#1218]
Root folder of pbspro source package has changed from 'pbspro' to 'openpbs'. This caused pbspro build fail in prep phase.

![image](https://user-images.githubusercontent.com/22388876/83232455-c9854000-a1bf-11ea-9a64-b3015d1990f7.png)

**Comment by koomie** [comment]
Resolved with switch over to openpbs based builds in 2.x tree.
