### ISSUE TITLE
gcc (v5.3.0)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#122]
gcc available at: https://gcc.gnu.org/releases.html

Dependencies available at:

GMP: https://ftp.gnu.org/gnu/gmp
MPC: ftp://ftp.gnu.org/gnu/mpc/
MPFR: http://www.mpfr.org/mpfr-current

**Comment by JohnWestlund** [comment]
gmp is now at v6.1.0

**Comment by koomie** [comment]
Updated versions in 1.1 branch.

**Comment by koomie** [comment]
Basic compiler CI tests passing.
