### ISSUE TITLE
mpich fabric switch error?

### ISSUE THREAD

**Issue by jcsiadal** [openhpc/ohpc#1221]
It looks to me that the fabric switches are not parsed correctly. Current code:

%{!?with_ucx: %define with_ucx 0}
%if 0%{with_ucx}
BuildRequires: ucx%{PROJ_DELIM}
Requires: ucx%{PROJ_DELIM}
Requires: ucx-ib%{PROJ_DELIM}
%define FABRIC_DELIM -ucx
%endif

%{!?with_ofi: %define with_ofi 1}
%if 0%{with_ofi}
BuildRequires: libfabric%{PROJ_DELIM}
Requires: libfabric%{PROJ_DELIM}
%define FABRIC_DELIM -ofi
%endif

If with_ucx is defined as 1 and with_ofi is undefined, with_ofi is set to "1". This leaves both options set to active the DELIM as -ofi

Should this be updated so that OFI is always used, unless UCX is on and OFI is off or undefined?

**Comment by koomie** [comment]
Yes, good catch. I will clean this up for formal 2.0 release.
