### ISSUE TITLE
Document YUM_MIRROR_BASE variable

### ISSUE THREAD

**Issue by solj** [openhpc/ohpc#1223]
In section 3.8.1, the tip mentions setting the YUM_MIRROR environment variable for folks using a local yum repository. Due to upstream changes in CentOS, simply setting this variable the way it was done previously won't work.

Looking at the templates, it looks like the easier way to use a local CentOS 8 repository is to use the YUM_MIRROR_BASE variable. Here are the relevant snippets from the centos7 and centos8 warewulf templates.

`centos-7.tmpl`
```bash
# Define the location of the YUM repository
if [ -z "$YUM_MIRROR" ]; then
    if [ -z "$YUM_MIRROR_BASE" ]; then
        YUM_MIRROR_BASE="http://mirror.centos.org/centos-7"
    fi
    YUM_MIRROR="${YUM_MIRROR_BASE}/7/os/\$basearch/"
fi
```

`centos-8.tmpl`
```bash
# Define the location of the YUM repository
if [ -z "$YUM_MIRROR" ]; then
    if [ -z "$YUM_MIRROR_BASE" ]; then
        YUM_MIRROR_BASE="http://mirror.centos.org/centos-8"
    fi
    YUM_MIRROR="${YUM_MIRROR_BASE}/8/BaseOS/\$basearch/os","${YUM_MIRROR_BASE}/8/AppStream/\$basearch/os","${YUM_MIRROR_BASE}/8/PowerTools/\$basearch/os"
fi
```

**Comment by middelkoopt** [comment]
This also fails for Rocky/SLURM/Warewulf.  I had to do a
```
export YUM_MIRROR_BASE=https://mirror.usi.edu/pub/rocky
```
(specific example to show what part of the path is required.

Could not do a document patch since I don't know what `BOS_MIRROR` is and the CI/CD system seems to use this.
