### ISSUE TITLE
Centos 8.2 is already available

### ISSUE THREAD

**Issue by hseara** [openhpc/ohpc#1230]
Hi Developers,
I have seen that Warewulf 2RC1 is already out. I was planning to give it a shot before installing the final version Warewulf 2.x in our cluster. The issue is that Centos 8.2 is already out. Can I use  Warewulf 2RC1 with Centos 8.2. If not how do I force the system to remain to Centos 8.1?

**Comment by koomie** [comment]
You can use the version of Warewulf that is built with ohpc 2RC1 with CentOS 8.2 (and any new image builds will pick this up automatically).  The only thing that I know to be aware of is for packages that are tied to a specific kernel version. At the moment, that is the `msr-safe` package that is used by the optional geopm software.  If you skip that, I believe you should be fine.

**Comment by hseara** [comment]
Thanks for the info, I will close the topic and reopen it if I detect any issues due to the 8.2 point release.
