### ISSUE TITLE
Installer not working for configless slurm

### ISSUE THREAD

**Issue by solj** [openhpc/ohpc#1233]
The documents in their current form are not working for a configless slurm deployment. The `slurm-example-configs-ohpc` package installs slurm.conf by default.

```
[root@compute-0 ~]# rpm -ql slurm-example-configs-ohpc|grep slurm.conf
/etc/slurm/slurm.conf
/etc/slurm/slurm.conf.example
```
If you try to start the slurm daemon in configless mode per the documentation, you will receive the following error.

```
[root@compute-0 ~]# sinfo 
sinfo: error: Unable to resolve "linux0": Unknown host
sinfo: error: Unable to establish control machine address
slurm_load_partitions: No error
```

It seems like there are 2 possible solutions to this and I don't know which is preferred.

1.  Add a step to the install guide that removes the file in question
```
[root@compute-0 ~]# sinfo 
sinfo: error: Unable to resolve "linux0": Unknown host
sinfo: error: Unable to establish control machine address
slurm_load_partitions: No error
[root@compute-0 ~]# rm /etc/slurm/slurm.conf
[root@compute-0 ~]# systemctl restart slurmd
[root@compute-0 ~]# sinfo 
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST 
normal*      up 1-00:00:00      1   down compute-0 

```
2. Create a separate `slurm-example-configs-ohpc` package for master/compute (or somehow add logic to the SPEC file that will only install the file on the master)

**Comment by koomie** [comment]
This was resolved by having the example package include an .ohpc example that an admin can use to copy on the slurm controller node only.

```
# rpm -ql slurm-example-configs-ohpc | grep slurm.conf
/etc/slurm/slurm.conf.example
/etc/slurm/slurm.conf.ohpc
```
