### ISSUE TITLE
don't see warewulf: missing ' 0' in the end of efi*cmd patch in hpc 2.0-rc1

### ISSUE THREAD

**Issue by fun2yang** [openhpc/ohpc#1234]
[Fix: missing ' 0' in the end of efi*example.cmds ](https://github.com/warewulf/warewulf3/commit/c5a90bee76ac9c6cff48f0fedb2f83e6b5b155d0) has been merged into warewulf development branch since 3 months ago, but I don't see it in [hpc 2.0-rc1](http://repos.openhpc.community/OpenHPC/2).  If we can, please merge it when release 2.0 official final version( I also want to know the schedule.). I will be very grateful

**Comment by koomie** [comment]
Note that the updated build is live in 2.0 factory now: https://obs.openhpc.community/package/show/OpenHPC:2.0:Factory/warewulf-provision
