### ISSUE TITLE
EasyBuild (v4.2.2)

### ISSUE THREAD

**Issue by crbaird** [openhpc/ohpc#1240]
https://pypi.python.org/pypi/easybuild/

**Comment by boegel** [comment]
EasyBuild v4.2.2 will be released very soon (this week, at the latest on Thursday, probably earlier)

**Comment by boegel** [comment]
EasyBuild v4.2.2 is released, see #1242 for the updated `.spec`

**Comment by koomie** [comment]
Tests passing in CI.
