### ISSUE TITLE
Repository Access via Rsync to OpenHPC 2.x

### ISSUE THREAD

**Issue by vpenso** [openhpc/ohpc#1243]
Is it possible to access the OpenHPC **2.x** repository using rsync?

If so could you eventually add the relevant information to:

<https://github.com/openhpc/ohpc/wiki/Repository-Access-via-rsync>

Thanks in advance.

**Comment by koomie** [comment]
rsync is now enabled on the repository.  Example command to pull 2.0 release was added to the wiki location mentioned above.

**Comment by marseaplage** [comment]
Hi guys.

I am trying to mirror the ohpc repository by using rsync as is mentioned here but I got the timeout error:

 rsync -avzHKL --exclude src --exclude repocache --delay-updates rsync://repos.openhpc.community/OpenHPC/2/ 2


rsync: failed to connect to repos.openhpc.community (18.190.130.150): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

I hava also run the nmap for that port and I got the state "filtered" for rsync:

nmap repos.openhpc.community -p 873 -Pn

Starting Nmap 7.70 ( https://nmap.org ) at 2021-10-05 12:13 -05
Nmap scan report for repos.openhpc.community (18.190.130.150)
Host is up.
rDNS record for 18.190.130.150: ec2-18-190-130-150.us-east-2.compute.amazonaws.com

PORT    STATE    SERVICE
873/tcp filtered rsync

Nmap done: 1 IP address (1 host up) scanned in 2.57 seconds

I do not have restrictive firewalls as far as I know.

But do you have any suggestion to mirror the openhpc locally but with rsync or reposync to keep it up to date? THank you un advance for any suggestion or procedure. As you can see I have already tried rsync and reposync and nothing works for me.

 reposync -p repos.openhpc.community/OpenHPC/2/ --download-metadata --repo=OpenHPC

(29/353): dimemas-intel-openmpi4-ohpc-5.4.2-5.1.ohpc.2.0.x86_64.rpm                                   1.1 MB/s | 436 kB     00:00
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[FAILED] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
 reposync -p repos.openhpc.community/OpenHPC/2/ --download-metadata --repo=OpenHPC

(29/353): dimemas-intel-openmpi4-ohpc-5.4.2-5.1.ohpc.2.0.x86_64.rpm                                   1.1 MB/s | 436 kB     00:00
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[FAILED] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
 reposync -p repos.openhpc.community/OpenHPC/2/ --download-metadata --repo=OpenHPC

Could you help me to solve this issue?

Thank you in advance for your help.

**Comment by marseaplage** [comment]
Hi guys.

When I run the command:

rsync -avzHKL --exclude src --exclude repocache --delay-updates rsync://repos.openhpc.community/OpenHPC/2/ 2

I get this error:

rsync: failed to connect to repos.openhpc.community (18.190.130.150): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

In addition to that when I run this command:

 nmap repos.openhpc.community -p 873 -Pn

I get this:

Starting Nmap 7.70 ( https://nmap.org ) at 2022-06-29 16:55 -05
Nmap scan report for repos.openhpc.community (18.190.130.150)
Host is up.
rDNS record for 18.190.130.150: ec2-18-190-130-150.us-east-2.compute.amazonaws.com

PORT    STATE    SERVICE
873/tcp filtered rsync

Nmap done: 1 IP address (1 host up) scanned in 2.42 seconds

 Could you please help me to solve it?

Thank you in advance for any ideas.

**Comment by marseaplage** [comment]
I solve it with this command:

reposync --repoid=OpenHPC --norepopath -p /ohpclocalrepo/EL_8/ --exclude=docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64,mpich-ofi-gnu9-ohpc-3.3.2-8.1.ohpc.2.0.x86_64,mpich-ucx-gnu9-ohpc-3.3.2-10.1.ohpc.2.0.x86_64,mpich-ofi-intel-ohpc-3.3.2-10.3.ohpc.2.0.x86_64,mpich-ucx-intel-ohpc-3.3.2-10.1.ohpc.2.0.x86_64,ohpc-release-2-1.el8.x86_64
