### ISSUE TITLE
Does ohpc work on HUAWEI QILIN 920?

### ISSUE THREAD

**Issue by everett-moon** [openhpc/ohpc#1248]
Have someone tested OHPC deployed on Huawei Kirin 920 server?

I have noticed that ohpc support aarch64 on centos7.7

**Comment by adrianreber** [comment]
If that server is able to run centos or sles/leap then it will probably work.

**Comment by everett-moon** [comment]
I have got the following errors while boot from ipxe, how to fix this?
![image](https://user-images.githubusercontent.com/44184916/87637524-f348f500-c774-11ea-80b5-5dbc8e8d7a30.png)
It seems missing the network booting media
I have not found the `/warewulf/ipxe/bin-arm64-efi/snp.efi` on sms node.

**Comment by everett-moon** [comment]
I have made a mistake to define the variable `eth_provision` with uncorrent network interface.
