### ISSUE TITLE
r (v3.2.3)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#125]
Available at:
http://www.r-project.org
https://cran.r-project.org/src/base/R-3/

**Comment by thiell** [comment]
Hi John,
For sure I don't want to stop you in your tracks, and sorry if I missed the original reason, but why don't you rely on a more modern package or software installation system like EasyBuild or Spack? Sounds like reinventing the wheel, no? I have been administrating HPC cluster for more than 10 years now (on different sites) and right now I'm using EasyBuild and I couldn't get back to install software like R, gcc, and all this software matrix without such a tool. For example, as I'm posting this comment to the R ticket, we have at least 3 different versions or R on our main cluster right now, but for other software it's even more. Just delegate, EasyBuild and lmod is just what you need! My 2 cents ;-)

**Comment by JohnWestlund** [comment]
(cc: @koomie) @thiell I hear you.  I definitely like the benefits of being able to build and track multiple versions at the same time (It's one of my main concerns and is a topic for discussion I'm going to shoot out to the mailing list shortly). 

In this particular case OHPC v1.1 is likely be pre OHPC governance/technical committee so we're trying to keep overall changes to a minimum while we finish bootstrapping the process to allow the community to set the roadmap. So it's probably only going to include version updates, and a few additional packages.

I could see OHPC transitioning to a Spack/EasyBuild model. But that's a large enough change in the current OHPC model that I think it would be best to get some community consensus. Let's start the conversation on the mailing list and then hopefully have it hashed out to a place that the soon-to-be technical committee can rubber stamp it. Whether that's an OHPC v1.2 or a v2.0.

**Comment by crbaird** [comment]
tests passing in CI
