### ISSUE TITLE
Lmod EPEL8 conflicts

### ISSUE THREAD

**Issue by opoplawski** [openhpc/ohpc#1251]
```
Error: Transaction test error:
  file /usr/lib/.build-id/40/b69a3143c66d2be20f78c08f6258504364f81b from install of lmod-ohpc-8.2.10-14.5.ohpc.2.0.x86_64 conflicts with file from package Lmod-8.2.7-1.el8.x86_64
```
I'm just getting started looking at OpenHPC, but am curious to see if the two can be made interchangeable.

**Comment by koomie** [comment]
I'm not sure if the two builds are legitimately interchangeable, but it probably doesn't make sense to have two Lmod variants co-installed simultaneously.  To make this more specific (as opposed to the file conflict you observed), we should probably `Conflict` the EPEL version to avoid confusion.
