### ISSUE TITLE
trilinos-intel build failures

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#1254]
Trilinos builds are failing with intel compiler (looks to be in Kokkos).  

.e.g https://obs.openhpc.community/package/live_build_log/OpenHPC:2.0:Factory/trilinos-intel-openmpi4/CentOS_8/x86_64

**Comment by koomie** [comment]
@jcsiadal,  I setup example Trilnios builds in your home project area on OBS (https://obs.openhpc.community/project/show/home:jcsiadal)

If you want to tinker with builds there, you can just update the `_service` file for the `trilinos-gnu9-openmpi4` package to point to a fork in your own personal github area.  When you push changes to the forked repo, you can click on the Trigger Services button for the gnu9/openmpi4 variant and it should download updated source and kick-off builds for both the gnu and intel variants.

**Comment by koomie** [comment]
FYI, I thought I would try a newer version of PSXE outside of OBS just in case it might build out of the box. I used `2020-u3` and also look to get failures in Kokkos.  Example output below.

```
/root/rpmbuild/BUILD/Trilinos-trilinos-release-12-18-1/packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_mkl_impl.hpp(563): error: identifier "mkl_sparse_d_create_csr" is undefined
          if (SPARSE_STATUS_SUCCESS != mkl_sparse_d_create_csr (&A, SPARSE_INDEX_BASE_ZERO, m, n, a_xadj, a_xadj + 1, a_adj, ( double *)a_ew)){
                                       ^
          detected during:
            instantiation of "void KokkosSparse::Impl::mkl_apply(KernelHandle *, KernelHandle::nnz_lno_t, KernelHandle::nnz_lno_t, KernelHandle::nnz_lno_t, in_row_index_view_type, in_nonzero_index_view_type, in_nonzero_value_v\
iew_type, bool, bin_row_index_view_type, bin_nonzero_index_view_type, bin_nonzero_value_view_type, bool, cin_row_index_view_type, cin_nonzero_index_view_type, cin_nonzero_value_view_type, bool) [with KernelHandle=KokkosSparse:\
:SPGEMMHandle<const size_t={unsigned long},
```

I see there is a new Trilinos 13.0.0 release out last month (vs. the 12.x tree we have been on for a while).

**Comment by jcsiadal** [comment]
I'm looking at this right now. I have a local OpenHPC distro build running with PSXE 2020U2. My info shows that PSXE 2020U3 is a release candidate right now. I'll have an update later today.

**Comment by jcsiadal** [comment]
Using my local (and brand new) SUSE 15.2 build system, 13.0.0 built with Intel Parallel Studio 2020.2. However, trilinos doesn't respect the DESTDIR variable in one of its subroutines and fails on install into buildroot. Testing one CMAKE option before I look at patching the subroutine.

I'll also post a PR for the phdf5 and netcdf dependencies, since these still do not build correctly on a local OpenSUSE install.

**Comment by koomie** [comment]
You can access the working phdf5 and netcdf rpms straight from 2.0 Factory to avoid having to build locally (https://obs.openhpc.community/project/show/OpenHPC:2.0:Factory).

I have a couple of related updates. I went back to see if the Trilinos version that we had in v1.3.9 would build with PSXE 2020 and it did. However, the build fails with gnu9.  There is one more intermediate Trilinos release and I tried that as well. Intel build was successful, but again gnu9 fails.  So, we may be in an odd situation with having to supply different versions between the compiler variants.

Just to summarize what I see:

**Trilinos v12.12.1**
* gnu9 build - build fails
* psxe 2020u0 - build succeeds

**Trilinos v12.12.4**
* gnu9 build - build fails
* psxe 2020u0 - build succeeds

**Trilinos v12.12.18**
* gnu9 build - build succeeds
* psxe 2020u0 - build fails
* psxe 2020u3 - build fails

**Comment by jcsiadal** [comment]
Trilinos 13.0.0 successfully built on gnu9-openmpi4 and intel-impi with PSXE 2020U2. I need to double-check a few items and I'll create a pull request this afternoon.

**Comment by koomie** [comment]
Thanks for the update to enable builds of v13.0.0.  CI tests with PSXE were re-enabled and looking good again.
