### ISSUE TITLE
gcc-gfortran missing from base GNU/8.3.1

### ISSUE THREAD

**Issue by berhane** [openhpc/ohpc#1262]
While trying to build some software with GNU/8.3.1 using Spack on an OpenHPC 2.0RC1 installation, I realized that gcc-gfortran is missing. That may be by design, but I wanted to report it just in case.

```
$~ rpm -qa|grep -i gcc
gcc-8.3.1-4.5.el8.x86_64
libgcc-8.3.1-4.5.el8.x86_64
gcc-c++-8.3.1-4.5.el8.x86_64
gcc-gdb-plugin-8.3.1-4.5.el8.x86_64
```

**Comment by koomie** [comment]
Looks like you are querying the os provided packages.  The ohpc package supplying gfortran on 2.x will have `gnu9-compilers` in the name:

```
[ohpc-test@sms005 ~]$ which gfortran
/opt/ohpc/pub/compiler/gcc/9.3.0/bin/gfortran

[ohpc-test@sms005 ~]$ rpm -qf /opt/ohpc/pub/compiler/gcc/9.3.0/bin/gfortran
gnu9-compilers-ohpc-9.3.0-15.1.ohpc.2.0.x86_64
```

**Comment by berhane** [comment]
Thanks, Karl. I should have realized OpenHPC has no control over the base OS GNU compilers.
