### ISSUE TITLE
OpenHPC 2: chrony.conf needs changes

### ISSUE THREAD

**Issue by phpHavok** [openhpc/ohpc#1265]
In the chrony configuration steps under section 3.3 titled "Add provisioning services on master node," chrony.conf needs a couple changes.

1. chrony.conf needs a line to allow internal network clients to use it as an NTP server. Specifically, something like this should be added:

```bash
echo "allow ${sms_ip}/${internal netmask}" >> /etc/chrony.conf
```

2. chrony.conf needs to comment out or remove the pool line since we are using an NTP server line. Something like:

```bash
perl -pi -e "s/^(pool.*)$/#\\1/" /etc/chrony.conf
```

This pool change also needs to be made for the VNFS images in section 3.8.2 titled "Add OpenHPC components".

**Comment by koomie** [comment]
Thanks for this suggestion. We also detected a needed change in the ntp configuration which was made in the current 2.0 branch and will be in the final 2.0 release.

It is slightly different than you suggested, but should be sufficient to ensure that ntp synchronization is done. I also added a quick ntp test to the ohpc test suite to confirm the daemons are talking.  In the current recipe example, we include the following line in chrony.conf on head node:

`allow all` 

But the docs also have tooltip to indicate how to restrict to a local subnet as well (similar to your suggestion).

Regarding the removal of `pool` options, I'm not sure if we really need that. My testing seems to indicate that the `server` line will have priority over pool settings, so I've left that as is.

Please advise if that is inconsistent with your experience.
