### ISSUE TITLE
OpenHPC 2: rsyslog.conf needs changes

### ISSUE THREAD

**Issue by phpHavok** [openhpc/ohpc#1266]
The rsyslog.conf file has changed a bit in CentOS 8. In section 3.8.4.6 titled "Enable forwarding of system logs," these lines:

```bash
perl -pi -e "s/\\#\\\$ModLoad imudp/\\\$ModLoad imudp/" /etc/rsyslog.conf
perl -pi -e "s/\\#\\\$UDPServerRun 514/\\\$UDPServerRun 514/" /etc/rsyslog.conf
```

are incorrect. The new commented out lines in the file for CentOS 8 are:

```
#module(load="imudp") # needs to be done just once
#input(type="imudp" port="514")
```

**Comment by koomie** [comment]
Thanks for this report. This has been fixed in current 2.0 branch via #1229.
