### ISSUE TITLE
[OHPC 2] Documentation mentions "openmpi4-pmix-slurm-gnu9-ohpc" but it doesn't exist

### ISSUE THREAD

**Issue by phpHavok** [openhpc/ohpc#1273]
On page 26 of "Install_guide-Centos8-Warewulf-SLURM-2.0-x86_64.pdf" revision 1e970dd16, there's this sentence:
> An additional OpenMPI build variant is listed in Table 1 which enables PMIx job launch support for use
with Slurm. This optional variant is available as openmpi4-pmix-slurm-gnu9-ohpc.

But "Table 1" on page 25 does not show that variant, and in fact that package doesn't even exist:
```
[root@sms slurm]# dnf install openmpi4-pmix-slurm-gnu9-ohpc
Last metadata expiration check: 2:55:13 ago on Wed 28 Oct 2020 03:24:37 PM UTC.
No match for argument: openmpi4-pmix-slurm-gnu9-ohpc
Error: Unable to find a match: openmpi4-pmix-slurm-gnu9-ohpc

[root@sms slurm]# dnf search openmpi4 | grep slurm
Last metadata expiration check: 2:54:40 ago on Wed 28 Oct 2020 03:24:37 PM UTC.
```

**Comment by koomie** [comment]
Thanks for catching this. I did some tests to try and add this package back, but was unable to get job launch to work correctly under slurm.  Have removed mention of this package for now.

**Comment by sjpb** [comment]
I note this package is still mentioned in the v2.1 docs, although it still doesn't exist. I don't see why it needs to either, as at least in openhpc v2.0 you could use `srun --mpi=pmix_v` with the openhpc `openmpi4` module provided by `ohpc-gnu9-openmpi4-perf-tools` (or similar) and it worked fine (as far as I could tell). Although in openhpc v2.1 there's an issue #1320 .

**Comment by koomie** [comment]
Sorry, which package are you saying is referenced in the docs? Maybe I'm missing it, but I don't see a mention of the pmix variant of openmpi4 in my doc builds.  

If a direct slurm pmix job launched worked previously in 2.0, it was untested and not codified in job launch with `prun`. The intended support path to use pmix job launch is to opt-in to use a variant of openmpi4 which is built against the same external version of pmix that slurm is built against.  This worked previously with older versions of slurm and openmpi, but I was unable to get it to work with the newer variants in the 2.x series.

**Comment by sjpb** [comment]
Oops my mistake, I think I had v2.0 and v2.1 docs open at the same time, it's gone in v2.1.
