### ISSUE TITLE
Intel OneApi Compatibility

### ISSUE THREAD

**Issue by LecrisUT** [openhpc/ohpc#1281]
It looks like Intel is changing their software bundle from `Parallel Studio` to [`OneApi`](https://software.intel.com/content/www/us/en/develop/tools/oneapi/commercial-base-hpc.html).  With it all of the usual locations are shifted around, e.g. `/opt/intel/bin/compilervars.sh` -> `/opt/intel/oneapi/setvars.sh`. All of the functionality seems to be the same as before.

Is it possible to support the new format in the next `OpenHPC` release?

**Comment by jcsiadal** [comment]
Now that OneAPI is formally released, I'm going to put in a PR for people to look at before I head out for holiday next week. There are environment modules in the new OneAPI Toolkit, so you don't need to use the scripts. However, the compiler module uses a Tcl function that isn't supported by Lmod. I had to put in a minor change to handle it.

**Comment by LecrisUT** [comment]
How about the compatibility with `hdf5`, `prun` and so on?

**Comment by jcsiadal** [comment]
I don't know yet. I want to complete a package to put the toolchain in place and then I can start running some test builds with other OpenHPC components.

**Comment by LecrisUT** [comment]
@jcsiadal any updates on this? I found that the old Parallel Studio licenses have expired and intel now requires us to change to OneAPI, so it is a higher priority task to get the compatibility up and running.

**Comment by jcsiadal** [comment]
Until this update is available in OpenHPC, the manual instructions are published here: https://software.intel.com/content/www/us/en/develop/download/openhpc-installation-guide-for-centos.html
Send me a quick message if you hit any issues.

**Comment by LecrisUT** [comment]
Great thorough guide, I'll do some adjustments to make it more in line with this.

But it doesn't seem to configure mkl/compiler-rt, etc. Also, would it be better to prefix all oneapi's modules with a `oneapi/` in lmod so that there's no potential of clash?

**Comment by jcsiadal** [comment]
I added this as issue #1317. It includes my work in progress.

**Comment by jcsiadal** [comment]
See #1341.

**Comment by koomie** [comment]
Landed for v2.4 release.
