### ISSUE TITLE
Future of OpenHPC for Centos?

### ISSUE THREAD

**Issue by e-alfred** [openhpc/ohpc#1282]
Now that Centos will move away to Centos Stream [1] and support for Centos 8 will end next year, what is the future of OpenHPC on Centos? A rolling release is not a good idea for HPC usage (especially with proprietary software needing specific libraries etc), so is there any future left for it?

[1] https://blog.centos.org/2020/12/future-is-centos-stream/

**Comment by hyviquel** [comment]
I was asking myself the same question...

**Comment by mpurg** [comment]
Thread on mailing list

[here](https://groups.io/g/OpenHPC-users/topic/centos_8_x_support_ending_and/78831347?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,78831347)

**Comment by truatpasteurdotfr** [comment]
if you have time, please voice your concerns/use case to centos-questions@redhat.com

**Comment by viniciusferrao** [comment]
I think this should be closed since OpenHPC always worked on all EL (Enterprise Linux) clones, and as today Rocky Linux 8 was elected as the replacement.

As for my experience, Oracle Linux and Red Hat Enterprise Linux (RHEL) works flawlessly with OpenHPC.

**Comment by adrianreber** [comment]
@viniciusferrao good idea. I am closing this. The discussion were on the mailing lists and also in the TSC meetings and the latest OpenHPC is built based on RHEL and has installation guides targeting Rocky Linux.
