### ISSUE TITLE
[OHPC 2.0] Start/enable for tftp should be tftp.socket (not .service)

### ISSUE THREAD

**Issue by phpHavok** [openhpc/ohpc#1286]
The Install_guide-Centos8-Warewulf-SLURM-2.0-x86_64.pdf on page 12 mentions:

```
[sms]# systemctl enable tftp
[sms]# systemctl restart tftp
```

which defaults to tftp.service. I've found that in our OpenHPC 2.0 setup, this doesn't actually work as intended. The TFTP service dies after a while (even after a reboot) and future provisions fail. If you instead run `systemctl enable tftp.socket` and `systemctl start tftp.socket`, then the socket is enabled which automatically starts the tftp service as needed.

See: https://access.redhat.com/solutions/2145941

**Comment by koomie** [comment]
Thanks for this report - we'll include the updated startup per your suggestion in the next release.
