### ISSUE TITLE
Installing  mpich-ofi-gnu9-ohpc looks for  the wrong version from the repo

### ISSUE THREAD

**Issue by davisgoodman** [openhpc/ohpc#1287]
while trying to install mpich-ofi-gnu9-ohpc the database shows 
 yum install mpich-ofi-gnu9-ohpc
Last metadata expiration check: 0:11:56 ago on Mon 21 Dec 2020 02:15:29 PM EST.
Dependencies resolved.

Installing:
 mpich-ofi-gnu9-ohpc                                x86_64                                3.3.2-8.1.ohpc.2.0                         ohpc               31 M
 
 But can't find any mirrors available:  
 [FAILED] mpich-ofi-gnu9-ohpc-3.3.2-8.1.ohpc.2.0.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

because the version in the repo is actually            mpich-ofi-gnu9-ohpc-3.3.2-10.1.ohpc.2.0.x86_64.rpm

Not sure where the discrepancy is

**Comment by koomie** [comment]
Sorry I missed this - did you sort it out? Version `3.3.2-10.1.ohpc.2.0` is definitely the latest version in 2.0 and I can install `mpich-ofi-gnu9-ohpc` in a minimal docker container without issues.

**Comment by koomie** [comment]
Going to close for now assuming that all is good. Feel free to follow up if you see again.
