### ISSUE TITLE
xCAT (2.11)

### ISSUE THREAD

**Issue by arif-ali** [openhpc/ohpc#129]
version: 2.11
URL: http://xcat.org

I started a mini project 6 months ago on the public OBS to get the xCAT rpms built, some of these are available in my repo at http://download.opensuse.org/repositories/home:/arif-ali80/CentOS_7

If this fits in what you would like, I may work on this further, to add to this repo

The full set of packages that are being doing in OBS is listed here https://build.opensuse.org/project/show/home:arif-ali80

Packages Built
- [x] xCAT
- [x] conserver-xcat
- [x] elilo-xcat
- [x] grub2-xcat
- [x] ipmitool-xcat
- [x] perl-xCAT
- [x] syslinux-xcat
- [x] xCAT
- [x] xCAT-buildkit
- [x] xCAT-client
- [x] xCAT-confluent
- [ ] xCAT-genesis-base-x86_64
- [x] xCAT-genesis-scripts
- [x] xCAT-server
- [x] xCAT-vlan
- [x] xCATsn
- [ ] xnba-undi
- [ ] perl-IO-Stty

**Comment by JohnWestlund** [comment]
Thanks @arif-ali ! I've been tracking xCAT as a possible addition. I'll check out your work.

**Comment by JohnWestlund** [comment]
@arif-ali I'm trying to locate some of the dependencies you don't build:

Error: Package: xCAT-2.11-36.1.x86_64 (home_arif-ali80)
           Requires: conserver-xcat
Error: Package: xCAT-2.11-36.1.x86_64 (home_arif-ali80)
           Requires: syslinux-xcat
Error: Package: xCAT-2.11-36.1.x86_64 (home_arif-ali80)
           Requires: elilo-xcat
Error: Package: 1:xCAT-genesis-scripts-x86_64-2.11-2.1.noarch (home_arif-ali80)
           Requires: xCAT-genesis-base-x86_64
Error: Package: xCAT-2.11-36.1.x86_64 (home_arif-ali80)
           Requires: xCAT-buildkit
Error: Package: xCAT-2.11-36.1.x86_64 (home_arif-ali80)
           Requires: xnba-undi
Error: Package: 4:xCAT-server-2.11-24.1.noarch (home_arif-ali80)
           Requires: grub2-xcat

Where do you source these from? A different OBS repo?

**Comment by arif-ali** [comment]
Hi @JohnWestlund,

These were just test builds, I need to look at building others as well, all the dependancies and the RPMS are built by IBM/Lenovo on xcat.org. TheOBS stuff was really a test project for me to see if that would work.

If this is the route you would like to take, then I am happy to spend some time in the next few weeks to add all the relevant dependencies onto OBS as well. It just requires some work to extract from the xcat-core github directory structure.

I will then write scripts around that, so that these are easily extracted, and uploaded to OBS

Let me know your thoughts

**Comment by JohnWestlund** [comment]
That would be great @arif-ali -- let me know if I can assist in any way.

**Comment by arif-ali** [comment]
Ok, leave that with me, and I will see what I can do

**Comment by JohnWestlund** [comment]
@arif-ali I just wanted to clarify that you don't need to exhaustively build all packages from the `xcat-dev` tarball.

Just the one's that aren't likely to be found in distro's repo -- the really xCat specific stuff. Such as the deps I listed above.

**Comment by arif-ali** [comment]
Built more packages today, still need to do the following

[ ] xCAT-genesis-base-x86_64
[ ] xnba-undi

Can you double check with your dependancies, if you have an opportunity, to see if you are missing anything

**Comment by JohnWestlund** [comment]
Sorry for the delayed response. There is one additional dependency beyond xnba and genesis-base
```
Error: Package: xCAT-2.11-36.1.x86_64 (home_arif-ali80)
           Requires: xnba-undi
Error: Package: 1:xCAT-genesis-scripts-x86_64-2.11-2.1.noarch (home_arif-ali80)
           Requires: xCAT-genesis-base-x86_64
Error: Package: xCAT-2.11-36.1.x86_64 (home_arif-ali80)
           Requires: perl-IO-Stty
```

**Comment by koomie** [comment]
This is deprecated in favor of using the public xCAT repo and the OpenHPC/xCAT recipe that first appeared with [v1.3.1](https://github.com/openhpc/ohpc/releases/tag/v1.3.1.GA) release.
