### ISSUE TITLE
Problem with WW provisioning with --filesystem (and hence stateful builds)

### ISSUE THREAD

**Issue by ECoulter** [openhpc/ohpc#1291]
So, using the `wwsh provision set --filesystem=...` command with a node in OHPC 2.0 currently creates a failing boot state. The node will fail with errors when running the mkfs commands during initial provisioning (visible in logs through the WW pre-shell). 

There's a fix here: https://groups.io/g/OpenHPC-users/topic/77713339#3900
which may not be the actual root cause. Basically, the fix adds /etc/mke2fs.conf back into the base initramfs image provided by the 
 warewulf-provision-ohpc-initramfs-x86_64 rpm.
 (Haven't tested on aarch64) 

 I'm not 100% clear on how the /srv/warewulf/initramfs/x86_64/base image is created; it isn't listed in 
 https://github.com/openhpc/ohpc/blob/2.x/components/provisioning/warewulf-provision/SPECS/warewulf-provision.spec
but is generated at some point via the WW make process.

This has been raised on the WW github page as well, but no insightful comments yet.
https://github.com/warewulf/warewulf3/issues/268

**Comment by crbaird** [comment]
https://github.com/openhpc/ohpc/commit/9575865019d249ad3e5770ec93693c933aa55db5

**Comment by crbaird** [comment]
@ECoulter The distro provided mke2fs.conf is now shipped inside the base initramfs.
