### ISSUE TITLE
`systemctld reload slurmctld` returns 0 even if reload fails

### ISSUE THREAD

**Issue by sjpb** [openhpc/ohpc#1293]
As per title, if you reload slurmctld with a changed config which causes an error (e.g. adding a node - this requires a restart rather than a reload) then `systemctcl reload slurmctld` returns 0 even though the daemon stops.

Having looked at the unit file in `/usr/lib/systemd/system/slurmctld.service`, ExecReload is `/bin/kill -HUP $MAINPID`. Which is the [right signal](https://slurm.schedmd.com/slurmctld.html) for a reload but is async with no check that the daemon actually successfully reloads.

This makes it hard to catch errors in automation.

I'm assuming that the unit files are openhpc provided rather than this being a slurm bug.

**Comment by adrianreber** [comment]
The file `slurmctld.service` is directly taken from upstream:  https://github.com/openhpc/ohpc/blob/2.x/components/rms/slurm/SPECS/slurm.spec#L415

https://github.com/SchedMD/slurm/blob/master/etc/slurmctld.service.in

It probably would make more sense to report this directly upstream to slurm.

**Comment by adrianreber** [comment]
Not exactly the bug you reported but there are changes coming to slurm's systemd files in 20.11:

https://github.com/SchedMD/slurm/commit/9249173482a8fe23d52b4f2fbf41482941fead77
https://bugs.schedmd.com/show_bug.cgi?id=8388

**Comment by sjpb** [comment]
Wow that was fast 😃 thanks for links to unit files. Raised here: https://bugs.schedmd.com/show_bug.cgi?id=10712

**Comment by adrianreber** [comment]
Do you want to close the ticket (I cannot) or keep it open for better tracking?
