### ISSUE TITLE
NHC fails on OpenSUSE Leap 15.2

### ISSUE THREAD

**Issue by mpurg** [openhpc/ohpc#1295]
Hi, 

I noticed that the Node Health Check tool fails to call the scripts which are responsible for marking the nodes online/offline in Slurm/PBE.

My setup is Leap15.2 + OHPC 2.1 + Warewulf + Slurm.

After running `nhc`, the logfile shows:

/var/log/nhc.log
`/usr/sbin/nhc: line 54: /usr/libexec/nhc/node-mark-offline: No such file or directory`

The issue has to do with the missing /usr/libexec directory, and was already addressed in this commit:
https://github.com/mej/nhc/commit/b37627243023b77b6f5fb02d1049f92926e4ce49#diff-2ef00c2c1b12a24e0fa75cd49e0d55fbe7d80c2fca467e421d7853d197bba654

Quick workaround is to symlink /usr/lib to /usr/libexec

**Comment by koomie** [comment]
Thanks for the pointer to the upstream patch. I had to tweak slightly to take against the release version of nhc, but have rebuilt for our 2.1 release.

If you wanted to check the Leap build in advance, you can grab the RPM from our build server:

http://obs.openhpc.community:82/OpenHPC:/2.1:/Factory/Leap_15/
