### ISSUE TITLE
 2.0 of CentOS 8.2 : nothing provides kernel(__ib_alloc_pd)

### ISSUE THREAD

**Issue by gitlky9** [openhpc/ohpc#1306]
dear friend:
    I did install  package(the lustre-client-ohpc-2.12.5-2.1.ohpc.2.0.x86_64 in compute image) a problem，and I have been kernel install finished in "/opt/ohpc/admin/images/centos8.2/".
    would you help me? 
    thanks.  
   

![1](https://user-images.githubusercontent.com/45412228/107474448-54bb3000-6bad-11eb-81e4-5ca131c80f9e.png)

**Comment by gitlky9** [comment]
I have finished by build the pakage on CentOS 8.2

**Comment by gitlky9** [comment]
.

**Comment by koomie** [comment]
Glad to hear it; hopefully starting from our .src rpm helped facilitate the rebuild. In general, you will have to rebuild anything that is tied to a specific kernel module if it deviates from the version available at the time when we did the release.
