### ISSUE TITLE
The Centos8.2 is updated  and  kernel version  4.18.0-240.10.1.el8_3

### ISSUE THREAD

**Issue by gitlky9** [openhpc/ohpc#1308]
Hi friends:
  I am attempted update  Centos8.2 kernel，but It's not what I want，and I having attempt seek the kernel-4.18.0-193.el8，but I haven't find.
  now， I should need your help. and could you update to kernel-4.18.0-240.10.1.el8_3 then building  dependent package of  this kernel. 
  if this made too much trouble，you tell me this kernel(kernel-4.18.0-193) of download address. 
  thank you, my friend.

**Comment by adrianreber** [comment]
You should be able to find older CentOS packages at: https://vault.centos.org/

The kernel you are looking for can be found here: https://vault.centos.org/8.2.2004/BaseOS/x86_64/os/Packages/

**Comment by gitlky9** [comment]
> You should be able to find older CentOS packages at: https://vault.centos.org/
> 
> The kernel you are looking for can be found here: https://vault.centos.org/8.2.2004/BaseOS/x86_64/os/Packages/

Thank you very much. and I would attempt going go use these package tomorrow.

**Comment by adrianreber** [comment]
If it works, let us know and please close this ticket.
