### ISSUE TITLE
easybuild (v2.5.0)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#131]
Available at: https://github.com/hpcugent/easybuild
https://pypi.python.org/pypi/easybuild/2.4.0

**Comment by boegel** [comment]
Depending on when you need this in: EasyBuild v2.5.0 is going to be released very soon (next week most likely).

**Comment by boegel** [comment]
EasyBuild v2.5.0 has been released earlier today.

**Comment by JohnWestlund** [comment]
Thanks @boegel. Updated the issue.

**Comment by koomie** [comment]
@crbaird, Can you enable updated build?

**Comment by koomie** [comment]
Basic CI tests passing.
