### ISSUE TITLE
Warewulf 4.x

### ISSUE THREAD

**Issue by LecrisUT** [openhpc/ohpc#1314]
I've just found out that the development of warewulf is now moved to a different repository [ctrliq/warewulf](https://github.com/ctrliq/warewulf). Probably the core OHPC team is already aware of it, but I thought it would be useful to make the rest of the community aware of this as well.

So far it seems it is still in alpha testing and it has been completely re-written, so I'm curious what are OHPC's plan for integrating v4?

**Comment by jcsiadal** [comment]
With the release of 4.2RC1, I'm creating the OpenHPC RPM package starting from the WW4 .in template. I expect that piece to be finished today, with the validation testing on Rocky 8.4 and OpenSUSE 15.3 done later this week. Assuming no major changes, I can supply the PR when 4.2 releases. In-process work is here: https://github.com/jcsiadal/ohpc/tree/ww4

**Comment by jcsiadal** [comment]
See #1436.

**Comment by adrianreber** [comment]
Closing as warewulf 4 is now (2.6) available as a tech preview .
