### ISSUE TITLE
Move Intel Compilers to oneAPI

### ISSUE THREAD

**Issue by jcsiadal** [openhpc/ohpc#1317]
The Intel oneAPI Toolkit is required for support of new processor features and the current PSXE is fairly old now. Update OpenHPC to use the latest oneAPI HPC Toolkit.

1) oneAPI provides Tcl environment modules. They are almost compatible with LMOD. The one Tcl function that's unsupported I've been told is unsupportable in LMOD, but it can be replaced with an LMOD function.
2) oneAPI can be installed outside of RPM. It's about time we ditch the RPM scanning method anyway. The current OHPC intel-devel packages are broken in our infrastructure (and many others). We centrally share tool installations to all clusters and nodes through a parallel FS. Even with dummy RPMs, the ohpc packages attempt to write into the PSXE installs and break.
3) Since the compilers do not require a license file to install or run, we don't need to worry separate runtime modules.
4) We should keep some backward compatibility with older PSXE installs.
5) It is possible to integrate the toolkit install into the RPM, but that doesn't work for installations like ours.

**Comment by jcsiadal** [comment]
I will be out for the next 8 weeks, so I'll link here to my WIP. These are the specfiles for compilers and impi. They build in OBS, the install of the oneAPI modules is working, and the resulting LMOD modules seem to work. I have not tested the compat modules for PSXE and overall I wanted to do much more validation on the main modules. Since this isn't baked yet, I'm not putting this in a PR.

https://github.com/jcsiadal/ohpc/blob/0bd8528f96b09fde2f1cfaa63030063807f408e2/components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec
https://github.com/jcsiadal/ohpc/blob/0bd8528f96b09fde2f1cfaa63030063807f408e2/components/mpi-families/impi-devel/SPECS/intel-mpi.spec

These work equally well with the RPM, web-based, and remote-shared oneAPI installations.

oneAPI stores multiple versions under the same root, but the same version of a component could exist in different roots on one system. Since there isn't an elegant way yet to merge environment modules from different oneAPI roots, it defaults to the first oneAPI root found.

One significant change is that due to the way oneAPI modules are generated, the MPI-devel package now requires the compiler-devel package. oneAPI MPI requires the oneAPI compilers, so no issue with dependencies.

**Comment by LecrisUT** [comment]
> 4. We should keep some backward compatibility with older PSXE installs.

You don't need to worry about this one. It is now impossible to run PSXE since the licenses have/will shortly expire.

**Comment by jcsiadal** [comment]
PR #1341 submitted.

**Comment by sjpb** [comment]
Can I just check - this will mean intel compilers will then be directly installable via the openhpc packages, correct?

**Comment by jcsiadal** [comment]
That's correct. Th current PR would create three packages: one to set up the repos, one to set up oneAPI toolchains (and install it if you haven't done so), and one for PSXE compiler modules.

**Comment by koomie** [comment]
Updated `intel-compilers-devel` and `intel-mpi-devel` landed for 2.4.
