### ISSUE TITLE
Request: add CPATH to GSL module file 

### ISSUE THREAD

**Issue by marhoni** [openhpc/ohpc#1321]
Hi, 
could we also set CPATH in the gls module file (analoge to INCLUDE), so that the compiler on our cent OS cluster find the lib. Users than don't need to add crumbersome include statements in their build files and commands. I guess that's what the other env variables are for. 
Thanks.

**Comment by marhoni** [comment]
Hi, setting the CPATH was not sufficient, we also had to set LIBRARY_PATH. 
Now everything works well (until the next update, when the module files are overwritten).

**Comment by koomie** [comment]
Please see discussion in https://github.com/openhpc/ohpc/pull/791 regarding CPATH. We looked at this before and decided against modifying the default modules to include; however, there is an outline of how one can use lmod hooks to implement this functionality if desired locally.

**Comment by marhoni** [comment]
Thanks, this will do.

On 5. May 2021, at 13:47, Karl W. Schulz ***@***.******@***.***>> wrote:



Please see discussion in #791<https://github.com/openhpc/ohpc/pull/791> regarding CPATH. We looked at this before and decided against modifying the default modules to include; however, there is an outline of how one can use lmod hooks to implement this functionality if desired locally.
