### ISSUE TITLE
hwloc problem when install openpbs or slurm

### ISSUE THREAD

**Issue by zhaoha** [openhpc/ohpc#1324]
Hi, I'm using centos8.2, and I follow install guide recipe to install openhpc. But when I try to install openpbs-execution-ohpc, an error of missing libhwloc.so.5 pops out. Actually I manually install hwloc 1.11.8 to install openpbs-server-ohpc while yum provide hwloc 2.2.0 which do not contain libhwloc.so.5. So I want to know which hwloc version can support openpbs-excution-ohpc-20.0.0-4.1.ohpc.2.0？ Thanks.

**Comment by adrianreber** [comment]
We are aware of the problem. CentOS 8.4 has a newer hwloc and requires a rebuild of all hwloc dependencies. Right now we cannot offer a solution besides recommending to use hwloc from CentOS 8.3 or older.

**Comment by ruixingw** [comment]
I would suggest using ```centos-vault``` instead of ```centos``` as the yum repo. https://vault.centos.org/ 
You can use the mirror from tsinghua university, see their manual: https://mirrors.tuna.tsinghua.edu.cn/help/centos-vault/

**Comment by zhaoha** [comment]
hwloc1.11.9 works. Thanks!

**Comment by koomie** [comment]
We have rebuilt slurm and openpbs for CentOS8.4 to deal with the `hwloc` change. These will be available in the forthcoming ohpc release.

**Comment by koomie** [comment]
Tests passing in CI.

**Comment by ruixingw** [comment]
Hello. I see ohpc 2.3 is released to deal with this issue, and it targets CentOS 8.4. Will ohpc 2.3 work also on CentOS 8.3? (is the newer version of ```hwloc``` backward compatible?)
Also, the change log only mentioned CentOS and Rocky recipe. Is there any difference between ohpc 2.2 and 2.3 for openSUSE Leap?

**Comment by koomie** [comment]
> Hello. I see ohpc 2.3 is released to deal with this issue, and it targets CentOS 8.4. Will ohpc 2.3 work also on CentOS 8.3? (is the newer version of `hwloc` backward compatible?)
> Also, the change log only mentioned CentOS and Rocky recipe. Is there any difference between ohpc 2.2 and 2.3 for openSUSE Leap?

If still using the `hwloc` from CentOS 8.3, you will want to stick with the builds of openPBS and SLURM that are in ohpc 2.2. The only other software change in ohpc 2.3 is a newer version of libfabric and that is available for both CentOS and openSUE Leap.
