### ISSUE TITLE
pmix (v1.1.3)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#134]
https://github.com/pmix/releases/releases

**Comment by rhc54** [comment]
Hi John

Just an FYI: I'm prepping to release 1.1.2 which has a number of bug fixes. Should be released by end of week.

**Comment by JohnWestlund** [comment]
Perfect. I'll keep an eye out for it and update the issue. 



—

**Comment by rhc54** [comment]
Just released it:  http://pmix.github.io/master/downloads/

**Comment by JohnWestlund** [comment]
Thanks for the heads up!



—

**Comment by koomie** [comment]
Superceded by #466.
