### ISSUE TITLE
[OHPC 2.3] OpenSUSE Leap 15.2 Install Guide (with Warewulf + Slurm),  tftp error

### ISSUE THREAD

**Issue by tlsong** [openhpc/ohpc#1345]
When running the command on page 12：“perl -pi -e "s/^\s+disable\s+= yes/ disable = no/" /etc/xinetd.d/tftp”
Give this error message：“it Can't open /etc/xinetd.d/tftp: No such file or directory.”

**Comment by koomie** [comment]
Thanks for this report. I have updated the documentation to remove this step since it is no necessary on Leap.
