### ISSUE TITLE
Update recipes for Infiniband Support on CentOS 8.4

### ISSUE THREAD

**Issue by ruixingw** [openhpc/ohpc#1347]
Current version of the recipes instructs ```systemctl start rdma``` after installing Infiniband support. 
On CentOS 8.4, ```rdma.service``` is removed. See discussions here: https://www.reddit.com/r/HPC/comments/p46et0/centos_84_does_not_provide_rdmaservice_and/

OpenHPC recipes can be updated accordingly.

**Comment by koomie** [comment]
Thanks for the pointer. Forthcoming Rocky8.4 recipes have been updated.
