### ISSUE TITLE
Lustre Client (v2.12.7)

### ISSUE THREAD

**Issue by liv-acollins** [openhpc/ohpc#1348]
Lustre Client 2.12.7 is now available and supports RHEL 8.4
https://www.lustre.org/lustre-2-12-7-released/

I couldn't see any notes for this, or anything in the milestones for the v2.4 release - though I assume it is planned.
It would be great to get this for those of us trying to migrate to RockyLinux with Lustre

**Comment by liv-acollins** [comment]
Just checking on this, will this update make it into the 2.4 release?

**Comment by koomie** [comment]
I would expect this to land in 2.4.  I did a build with the latest 2.12.7 release and was able to mount a lustre client on one of our Rocky CI test environments:

```
# uname -a
Linux sms005 4.18.0-305.3.1.el8_4.x86_64
```

**Comment by liv-acollins** [comment]
Fantastic. Look forward to the release. Thank you! :)

**Comment by koomie** [comment]
Note that you can access the current build early if you want to try on Rocky 8.4 at: 

https://obs.openhpc.community/package/binaries/OpenHPC:2.4:Factory/lustre-client/EL_8

**Comment by liv-acollins** [comment]
Thanks @koomie, I'll give these a try once I get a window to pull the nodes offline.

**Comment by liv-acollins** [comment]
I've rolled this out across our cluster - all nodes are using Rocky. So far everything looks good, all the nodes are up and communicating with the storage servers.
Thanks @koomie !

**Comment by koomie** [comment]
Excellent!  Thanks for the update.

**Comment by koomie** [comment]
@detritus, just a head's up that this is a bit of a short lived victory.  Lustre does not yet support EL 8.5, so you would need to stick with an 8.4 kernel if wanting to upgrade to Rocky 8.5

**Comment by liv-acollins** [comment]
@koomie, that is the plan. We took a bit of a gamble jumping on Rocky for a new cluster. Now we have nearly everything stable (except Lustre Server), we will hold our ground until 8.5 is fully supported by all the dependencies.
