### ISSUE TITLE
FAIL: libs/fftw/ohpc-tests/test_mpi_families

### ISSUE THREAD

**Issue by henkblik** [openhpc/ohpc#1354]
Using Installl-guide OpenHPC (v2.3) Cluster Building Recipes CentOS 8.4 Base OS Warewulf/SLURM Edition for Linux* (x86 64)
I used recipe script provided in the ohpc-docs, adapted for 6 nodes 12 cores/cpu 
followind Appendix C, i got the result:
make --no-print-directory check-TESTS
FAIL: libs/fftw/ohpc-tests/test_mpi_families
============================================================================
Testsuite summary for test-suite 2.0.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/openhpc/ohpc
============================================================================
make[3]: *** [Makefile:757: test-suite.log] Error 1
make[2]: *** [Makefile:865: check-TESTS] Error 2
make[1]: *** [Makefile:1439: check-am] Error 2
make: *** [Makefile:642: check-recursive] Error 1
[test-suite.log](https://github.com/openhpc/ohpc/files/7202994/test-suite.log)

from slurm_jobcomp.log
JobId=20 UserId=ohpc-test(1001) GroupId=ohpc-test(1001) Name=C_test JobState=COMPLETED Partition=normal TimeLimit=5 StartTime=2021-09-21T14:17:55 EndTime=2021-09-21T14:17:55 NodeList=c1 NodeCnt=1 ProcCnt=48 WorkDir=/home/ohpc-test/tests/libs/fftw/tests ReservationName= Tres=cpu=1,node=1,billing=1 Account= QOS= WcKey= Cluster=unknown SubmitTime=2021-09-21T14:16:37 EligibleTime=2021-09-21T14:16:37 DerivedExitCode=0:0 ExitCode=0:0 
JobId=21 UserId=ohpc-test(1001) GroupId=ohpc-test(1001) Name=OpenHPC-test JobState=COMPLETED Partition=normal TimeLimit=5 StartTime=2021-09-21T14:17:55 EndTime=2021-09-21T14:18:05 NodeList=c[1-2] NodeCnt=2 ProcCnt=96 WorkDir=/home/ohpc-test/tests/libs/fftw/tests ReservationName= Tres=cpu=8,node=2,billing=8 Account= QOS= WcKey= Cluster=unknown SubmitTime=2021-09-21T14:17:55 EligibleTime=2021-09-21T14:17:55 DerivedExitCode=0:0 ExitCode=0:0 
JobId=22 UserId=ohpc-test(1001) GroupId=ohpc-test(1001) Name=F_test JobState=COMPLETED Partition=normal TimeLimit=5 StartTime=2021-09-21T14:18:06 EndTime=2021-09-21T14:18:06 NodeList=c1 NodeCnt=1 ProcCnt=48 WorkDir=/home/ohpc-test/tests/libs/fftw/tests ReservationName= Tres=cpu=1,node=1,billing=1 Account= QOS= WcKey= Cluster=unknown SubmitTime=2021-09-21T14:18:06 EligibleTime=2021-09-21T14:18:06 DerivedExitCode=0:0 ExitCode=0:0 

As requested in the outputi the command I report this issue

**Comment by koomie** [comment]
Sorry for the delay here. Looking at the logs, the test results for fftw with `gnu9-mpich` went ok. The failure happens when trying to test with `gnu9-mvapich2`, presumably because you don't have that variant installed locally.

To test with a subset of MPI stacks, you can use the `--with-mpi-families` option.  For example, assuming you rebuilt for openmpi4, you might want to add:

```
--with-mpi-families="openmpi4" 
```

**Comment by koomie** [comment]
Added quick mention of this option in Appendix C.
