### ISSUE TITLE
Openhpc repository Local mirror centos 8 - rsync doesn't work

### ISSUE THREAD

**Issue by marseaplage** [openhpc/ohpc#1360]
Hi guys.

I am trying to mirror the ohpc repository by using rsync as is mentioned here but I got the timeout error:

rsync -avzHKL --exclude src --exclude repocache --delay-updates rsync://repos.openhpc.community/OpenHPC/2/ 2

rsync: failed to connect to repos.openhpc.community (18.190.130.150): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

I have also run the nmap for that port and I got the state "filtered" for rsync:

nmap repos.openhpc.community -p 873 -Pn

Starting Nmap 7.70 ( https://nmap.org ) at 2021-10-05 12:13 -05
Nmap scan report for repos.openhpc.community (18.190.130.150)
Host is up.
rDNS record for 18.190.130.150: ec2-18-190-130-150.us-east-2.compute.amazonaws.com

PORT STATE SERVICE
873/tcp filtered rsync

Nmap done: 1 IP address (1 host up) scanned in 2.57 seconds

I do not have restrictive firewalls as far as I know.

But do you have any suggestion to mirror the openhpc locally but with rsync or reposync to keep it up to date? THank you un advance for any suggestion or procedure. As you can see I have already tried rsync and reposync and nothing works for me.

reposync -p repos.openhpc.community/OpenHPC/2/ --download-metadata --repo=OpenHPC

(29/353): dimemas-intel-openmpi4-ohpc-5.4.2-5.1.ohpc.2.0.x86_64.rpm 1.1 MB/s | 436 kB 00:00
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[MIRROR] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: Status code: 404 for http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm (IP: 18.190.130.150)
[FAILED] docs-ohpc-2.0.0-117.1.ohpc.2.0.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
reposync -p repos.openhpc.community/OpenHPC/2/ --download-metadata --repo=OpenHPC

Could you help me to solve this issue?

Thank you in advance for your help.

**Comment by koomie** [comment]
I would think `rsync` is a good choice if you want to mirror locally.   I just tried on a standalone box, and the rsync command you have kicked off downloads ok for me.  Not sure why it would not work for you when nmap shows you can access the rync port.

Another alternative is to download the tarball that includes the full repository for each release.  These are hosted at http://repos.openhpc.community/dist/ and links are also available at https://github.com/openhpc/ohpc/wiki/2.x. Once downloaded, you can untar and use the included `make_repo.sh` script to setup a locally hosted repository.

**Comment by marseaplage** [comment]
Hi yes I know what you said and I did it. The problem is how can I keep to up to date the repository? Since I want to use the local repository for the master node and the compute nodes instead of using the online repository. Do you think that is a good practice too?

**Comment by adrianreber** [comment]
@marseaplage I also tried to run you rsync command and it also works for me. I am closing this. Please reopen if you still have troubles.
