### ISSUE TITLE
can not update libfabric-ohpc-1.11 openhpc 2.3

### ISSUE THREAD

**Issue by marseaplage** [openhpc/ohpc#1361]
Hi 

Could you help me to fix the error that is shown below when I update the openhpc packages:

 yum --disablerepo="*" --enablerepo="OpenHPC-*" update

Error:
 Problem: cannot install the best update candidate for package libfabric-ohpc-1.11.2-4.1.ohpc.2.1.x86_64
  - nothing provides libefa.so.1()(64bit) needed by libfabric-ohpc-1.12.1-3.1.ohpc.2.3.x86_64
  - nothing provides libefa.so.1(EFA_1.1)(64bit) needed by libfabric-ohpc-1.12.1-3.1.ohpc.2.3.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

Thank you in advance for your reply

**Comment by koomie** [comment]
The `libefa.so.1()` dependency that is mentioned should be be supplied by the `libibverbs` package that is available in the baseOS repo (I'm assuming CentOS here).

```
# rpm -qf /usr/lib64/libefa.so.1
libibverbs-32.0-4.el8.x86_64
```

What do you get if you just try upgrading that package specifically, a la something like: `yum upgrade libfabric-ohpc`

**Comment by marseaplage** [comment]
Hello Koomie.

Yes it it Centos 8.4. As I mentioned before I am running that command in the master node and I got this error when I run the upgrade that you say:

yum upgrade libfabric-ohpc

Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Last metadata expiration check: 1:51:12 ago on Wed 06 Oct 2021 09:11:25 AM -05.
Error:
 Problem: package libfabric-ohpc-1.12.1-3.1.ohpc.2.3.x86_64 requires libefa.so.1()(64bit), but none of the providers can be installed
  - package libfabric-ohpc-1.12.1-3.1.ohpc.2.3.x86_64 requires libefa.so.1(EFA_1.1)(64bit), but none of the providers can be installed
  - cannot install both libibverbs-32.0-4.el8.x86_64 and libibverbs-54mlnx1-1.54103.x86_64
  - cannot install the best update candidate for package libfabric-ohpc-1.11.2-4.1.ohpc.2.1.x86_64
  - problem with installed package libibverbs-54mlnx1-1.54103.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

I am using this openhpc repo:

[OpenHPC]
name=OpenHPC-2 - Base
baseurl=http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-2

[OpenHPC-updates]
name=OpenHPC-2 - Updates
baseurl=http://repos.openhpc.community/OpenHPC/2/updates/CentOS_8
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-2

**Comment by marseaplage** [comment]
I have removed the mellanox drivers and I solved it.
