### ISSUE TITLE
boost (v1.60.0)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#138]
http://sourceforge.net/projects/boost/files/boost/1.60.0/

**Comment by koomie** [comment]
Updated obs config for boost packages to use 1.1 branch.

**Comment by koomie** [comment]
boost tests passing in CI on centos7.2/sles12sp1

**Comment by koomie** [comment]
Oops, I thought it was passing on sles12sp1, but there are a few outliers, so opening this back up.

**Comment by koomie** [comment]
Boost CI tests now passing with inclusion of libicu dependency.  Thanks.
