### ISSUE TITLE
ClusterShell (v1.8.4)

### ISSUE THREAD

**Issue by boegel** [openhpc/ohpc#1389]
@koomie I'm not sure if there are specific requirements for software updates, but I happened to notice there's a recently released update for ClusterShell compared to what OpenHPC includes currently (1.8.3); see https://github.com/cea-hpc/clustershell/releases/tag/v1.8.4

**Comment by koomie** [comment]
Thanks for the pointer. In the ohpc 2.x series, we now just use the distro-provided version of `clustershell`.  Looks like RHEL 8.5 is at v1.8.4
