### ISSUE TITLE
oneAPI: ohpc package depends on certain versions of oneAPI despite a newer version is installed. 

### ISSUE THREAD

**Issue by ruixingw** [openhpc/ohpc#1401]
Hello. I am installing OHPC 2.4 on Rocky 8 following Install Guide (v2.4): Rocky 8.5/x86 64 + Warewulf + SLURM, Rev: d198c8ee6. 

Following the instructions in Section 4.7, I installed all oneAPI related packages. I found that multiple versions were installed in the `/opt/intel/oneapi` folder:
```
[root@master compiler]# pwd
/opt/intel/oneapi/compiler
[root@master compiler]# ls
2021.2.0  2022.0.1  latest
```
 there are also two versions in `licensing`, `mkl`, `tbb` folders. Also, the `latest` symlink points to the older version despite its name "latest". 

by removing and reinstalling them step by step, it seems that ```yum -y install intel-compilers-devel-ohpc intel-mpi-devel-ohpc``` installs the latest version of oneAPI, but some OHPC packages depends on older version of oneAPI packages:
![QQ20220107-162232](https://user-images.githubusercontent.com/13862787/148514199-7f570910-4398-4506-93cb-2b34f7de190a.png)
The screenshot shows that ```intel-oneapi-mkl-2022.0.1``` is installed, but ```geopm-intel-openmpi4-ohpc``` depends on ```intel-oneapi-mkl-2021.2.0```. As a result, multiple versions of oneAPI are installed, and since the older version are installed after the latest version, the `latest` symlink is overwritten to the older one.

The modulefiles in `/opt/ohpc/moduledeps/oneapi` does not include the later installed old versions, because the modulefiles were generated when installing ```intel-compilers-devel-ohpc```, and were not regenerated after installing older versions.

**Comment by viniciusferrao** [comment]
@ruixingw if you run the following command after installation of old modules: 

`dnf reinstall intel-mpi-devel-ohpc intel-compilers-devel-ohpc`

Does it solve the issue?

**Comment by ruixingw** [comment]
this is obsolete as iirc now ohpc do fix a certain version of oneAPI (but newer).
