### ISSUE TITLE
hpc-workspace

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#1403]
https://github.com/holgerBerger/hpc-workspace

**Comment by georgiastuart** [comment]
@koomie , I work with @utdsimmons and I can build the SPEC for the hpc-workspace component if someone else isn't already assigned.

**Comment by martin-g** [comment]
I think this issue could be closed.

https://github.com/openhpc/ohpc/issues/1691 - Fixed the build.
https://github.com/openhpc/ohpc/issues/1675 - issue for adding tests.
