### ISSUE TITLE
Typo in fftw.spec: FFTW included in openhpc was never compiled with any SIMD intrinsics & enable avx2/avx512 

### ISSUE THREAD

**Issue by ruixingw** [openhpc/ohpc#1409]
This line in `fftw.spec` missed two closing `"`s that cause the `FFTW` was never compiled with any SIMD intrinsics:
https://github.com/openhpc/ohpc/blob/86eb69ff4dcfe0db176fefe0cf97d3bb9ff90075/components/parallel-libs/fftw/SPECS/fftw.spec#L75

While you look into this line, please have a look at the next line and consider adding more SIMD options. Currently, it compiles only with `sse2` and `avx` intrinsics. According to [FFTW documentation ](https://www.fftw.org/fftw3_doc/Installation-on-Unix.html), it does no harm to include recent SIMD options even when running on old machines. 
> "FFTW will try to detect at runtime whether the CPU supports these extensions. That is, you can compile with--enable-avx and the code will still run on a CPU without AVX support."

I suggest adding `--enable-avx2` and `--enable-avx512` for better performance on recent CPUs.

**Comment by adrianreber** [comment]
Can you provide a patch?

**Comment by ruixingw** [comment]
> Can you provide a patch?

created PR #1410
