### ISSUE TITLE
problem syncing OpenHPC 1.3 CentOS7 repo

### ISSUE THREAD

**Issue by jbeaird** [openhpc/ohpc#1419]
We use Spacewalk and Oracle Linux Manager to sync the OHPC 1.3 CentOS7 repos, both the main one

http://build.openhpc.community/OpenHPC:/1.3/CentOS_7

and updates

http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7

Since 6/23/2021, the sync of the main one has been failing. This is what we see in the logs:

    [root@server reposync]# /usr/bin/spacewalk-repo-sync --channel wc_ohpc_el7 --type yum
    17:45:03 ======================================
    17:45:03 | Channel: wc_ohpc_el7
    17:45:03 ======================================
    17:45:03 Sync of channel started.
    17:45:04
    17:45:04   Processing repository with URL: http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/
    17:45:04
    17:45:04   Importing comps file comps.xml.
    17:45:04 ERROR: 'group'
    17:45:05 Sync of channel completed in 0:00:01.
    17:45:05 Total time: 0:00:01
    
Other repositories that sync successfully always have an XML DTD declaration at the top of the file, e.g.

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE comps PUBLIC "-//CentOS//DTD Comps info//EN" "comps.dtd">
    
Is it possible that the comps.xml that comes as part of the repodata ( from http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/repodata/2dca89f2a5786911f5dee4a7e32a24b86128bdcea613788157d5a0c59ec7386c-group.xml.gz) could/should also have that declaration?

TIA, Jeff

**Comment by adrianreber** [comment]
Sorry, that nobody reacted for so long. I am closing this now. Please re-open if you still think something needs to be changed.

You are actually using the wrong location. Please use repos.openhpc.community.
