### ISSUE TITLE
Improve lmod dependency configuration within OBS build system

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#143]
One of the nice things about OBS is the transitive dependency analysis and automatic rebuilds that get triggered when packages include `BuildRequires` statements. This is definitely good and the most bullet-proof approach. However, in certain cases it can lead to overzealous rebuilds and the current use of Lmod for all development-oriented packages is an example of this. Lmod is included today as a `BuildRequires` since the build process shells out to setup the correct compiler/mpi family environment in the OBS chroot setup.  However, if a development package version has not changed, we do not necessarily need to rebuild at every lmod version commit, and this is the OBS config we have presently.

To improve upon the approach, we will augment the OBS configuration for the 1.1 branch to pre-install lmod into the chroot environment. This is done via the `Prefer` keyword in OBS. We will also update the default .spec configuration for development-oriented packages to not call out lmod specifically. However, to make sure that the .src rpms do the right things, lmod will be retained as a `BuildRequires` in a non OBS environment.  

Example updated syntax is as follows:

```
%if !0%{?opensuse_bs}
BuildRequires: lmod%{PROJ_DELIM}
%endif
```

**Comment by koomie** [comment]
@gdeisher, I've tested out this new approach for handling lmod dependencies in a standalone OBS project. I think we're ready for a full-sail update in the 1.1 branch. Can you use the current spec in the 1.1 branch as an example and update all the remaining .spec files that call out Lmod as a `BuildRequres`?

Thanks.

**Comment by gdeisher** [comment]
Lmod dependency added - commit ac567ce03b99c6c9bc26e2ad87f26b8aab7b305c.

**Comment by koomie** [comment]
@crbaird and I have discovered an issue with the current approach in that the `opensuse_bs` variable is not being set on the OBS instance, so the BuildRequires statement is being activated when we don't want it in the openhpc bulid env.  So, reopening this issue to address. After testing further, the intent is to revert to using a macro variable that is defined by our OBS project config (namely, `OHPC_BUILD`).  So, the updated logic will be:

```
%if !0%{?OHPC_BUILD}
BuildRequires: lmod%{PROJ_DELIM}
%endif
```

**Comment by koomie** [comment]
Spec files were updated to use the %{OHPC_BUILD} variable instead.  Confirmed that the build dependencies behave as expected for lmod after the change.
