### ISSUE TITLE
GCC12

### ISSUE THREAD

**Issue by jcsiadal** [openhpc/ohpc#1437]
Update to GNU Compiler Collection 12.1 or later as the default toolchain.

My initial testing shows that most of the packages will build as-is or with minor modifications.

Would supersede #1209.

**Comment by adrianreber** [comment]
@utdsimmons Let's discuss this in the TSC. During the 1.3.x release cycle we also upgraded gcc at some point. This would mean we would provide a new version of gcc and recompile almost everything with it.

**Comment by ohpcsim** [comment]
Sounds good; I'll add it to the agenda.
