### ISSUE TITLE
install guide tries to re-install MPI packages

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#145]
Under "Performance Tools" a group install is done:

```
[sms]# yum -y groupinstall ohpc-mpiP
```

This sucks in all the mpi packages (mvapich2, openmpi, impi), and then in the next section "MPI Stacks" it tries to install them again.

Should the "MPI Stacks" section be moved above "Performance Tools" so someone following along in the guide won't get an error about them already being installed?

**Comment by koomie** [comment]
Install reordered.
