### ISSUE TITLE
boost broken on aarch64

### ISSUE THREAD

**Issue by adrianreber** [openhpc/ohpc#1456]
The latest PR to update boost unfortunately broke the build on aarch64. Now that we have an `aarch64` build included in the CI run, it would be good to fix it.

@jcsiadal can you take a look at it? Hopefully with existing aarch64 CI it make it easier to test. Not sure if you have access to OBS again.

**Comment by jcsiadal** [comment]
I'll take a look. I noted in the PR that ARM was probably broken because I don't have any hardware to test it. If OBS demand-repos are working again, that would definitely help.

**Comment by jcsiadal** [comment]
Fixed by #1470.
