### ISSUE TITLE
Rocky 8 wwmkchroot fails to install extras, which is required for epel

### ISSUE THREAD

**Issue by bernstei** [openhpc/ohpc#1469]
The install guide for Rocky 8 warewulf/slurm appears to say that `dnf -y --installroot $CHROOT install epel-release` should just work.  However, `wwmkchroot` does not set up the Rocky 8 `extras` repo, which is required for getting `epel-release`. I'm not sure what the cleanest solution is - presumably changing the list of repos in the definition of `YUM_MIRROR` in `/usr/libexec/warewulf/wwmkchroot/rocky-8.tmpl`

**Comment by wwworkk** [comment]
I just ran into the same issue, solved it myself by modifying " /usr/libexec/warewulf/wwmkchroot/rocky-8.tmpl"
 add ,"${YUM_MIRROR_BASE}/8/extras/\$basearch/os" to the end of 
`YUM_MIRROR="${YUM_MIRROR_BASE}/8/BaseOS/\$basearch/os","${YUM_MIRROR_BASE}/8/AppStream/\$basearch/os","${YUM_MIRROR_BASE}/8/PowerTools/\$basearch/os"`

result:
`YUM_MIRROR="${YUM_MIRROR_BASE}/8/BaseOS/\$basearch/os","${YUM_MIRROR_BASE}/8/AppStream/\$basearch/os","${YUM_MIRROR_BASE}/8/PowerTools/\$basearch/os","${YUM_MIRROR_BASE}/8/extras/\$basearch/os"`

and start with building the initial chroot image.

Have only just tested this myself, do not feel comfortable to create a pull request for this.

**Comment by adrianreber** [comment]
I am closing this for now. The `extras` repository seems to be enabled by default in Rocky 8 when I just looked.

The documentation also mentions the `extras` repository that it needs to be enabled.
