### ISSUE TITLE
Keyerror raised when running misc/build_order.sh 

### ISSUE THREAD

**Issue by Yikun** [openhpc/ohpc#1473]
```
misc/build_order.sh
'nagios-common-ohpc'
'nagios-plugins-ohpc'
'openpbs-devel-ohpc'
'openpbs-server-ohpc'
'boost-gnu9-openmpi4-ohpc'
'petsc-gnu9-openmpi4-ohpc'
'boost-gnu9-openmpi4-ohpc'
'petsc-gnu9-openmpi4-ohpc'
'fftw-gnu9-openmpi4-ohpc'
Traceback (most recent call last):
  File "/root/ohpc/misc/build_order.py", line 107, in <module>
    v[i] = spec_dict[v[i]]
KeyError: 'nagios-common-ohpc'
```

Any comments?

**Comment by Yikun** [comment]
```python
diff --git a/misc/build_order.py b/misc/build_order.py
index 2a8a3ef48..e3c2ec56d 100755
--- a/misc/build_order.py
+++ b/misc/build_order.py
@@ -90,6 +90,16 @@ for v in dependency.values():
             # Handle python_prefix rpm macro
             if '-numpy-' in value:
                 spec_dict[value] = 'python-numpy.spec'
+            elif 'nagios-' in value:
+                spec_dict[value] = 'nrpe.spec'
+            elif 'petsc-' in value:
+                spec_dict[value] = 'petsc.spec'
+            elif 'openpbs-' in value:
+                spec_dict[value] = 'openmpi.spec'
+            elif 'boost-' in value:
+                spec_dict[value] = 'boost.spec'
+            elif 'fftw-' in value:
+                spec_dict[value] = 'python-scipy.spec'
             elif '-Cython-' in value:
                 spec_dict[value] = 'python-Cython.spec'
             elif '-scipy-' in value:
```

I could make it work according above workground.

> $ misc/build_order.sh
> lmod.spec boost.spec petsc.spec ohpc-filesystem.spec losf.spec release.spec powerman.spec nhc.spec nrpe.spec prun.spec conman.spec clustershell.spec examples.spec genders.spec docs.spec singularity.spec charliecloud.spec shine.spec libfabric.spec ucx.spec papi.spec paraver.spec pmix.spec munge.spec magpie.spec warewulf-common.spec spack.spec valgrind.spec cmake.spec autoconf.spec python34-build-patch.spec easybuild.spec automake.spec hwloc.spec gnu-compilers.spec llvm-compilers.spec intel-compilers-devel.spec sigar.spec python-rpm-macros.spec flex.spec ipmiutil.spec python-Cython.spec mrsh.spec tests.spec mvapich2.spec intel-mpi.spec mpich.spec openmpi.spec openblas.spec metis.spec superlu.spec example.spec scotch.spec R.spec pdtoolkit.spec likwid.spec extrae.spec imb.spec dimemas.spec geopm.spec omb.spec slurm.spec hypre.spec scalapack.spec opencoarrays.spec ptscotch.spec slepc.spec superlu_dist.spec warewulf-provision.spec warewulf-vnfs.spec warewulf-cluster.spec python-mpi4py.spec libtool.spec python-numpy.spec annobin.spec python-scipy.spec python.spec pdsh.spec lmod-defaults.spec hdf5.spec pnetcdf.spec netcdf.spec netcdf-cxx4.spec mfem.spec trilinos.spec warewulf-ipmi.spec adios.spec netcdf-fortran.spec

**Comment by adrianreber** [comment]
The script is not very reliable and needs fixing all the time. You could submit your changes as a pull request.

**Comment by adrianreber** [comment]
As you have solved it I am closing this issue. Please reopen if you have any further problems. Please open a PR if possible so that we can include your changes.
