### ISSUE TITLE
automake build error

### ISSUE THREAD

**Issue by huangtianhua** [openhpc/ohpc#1478]
+ cd /home/ohpc/rpmbuild/BUILD
+ '[' /home/ohpc/rpmbuild/BUILDROOT/automake-ohpc-1.16.1-1.ohpc.2.0.0.x86_64 '!=' / ']'
+ rm -rf /home/ohpc/rpmbuild/BUILDROOT/automake-ohpc-1.16.1-1.ohpc.2.0.0.x86_64
++ dirname /home/ohpc/rpmbuild/BUILDROOT/automake-ohpc-1.16.1-1.ohpc.2.0.0.x86_64
+ mkdir -p /home/ohpc/rpmbuild/BUILDROOT
+ mkdir /home/ohpc/rpmbuild/BUILDROOT/automake-ohpc-1.16.1-1.ohpc.2.0.0.x86_64
+ cd automake-1.16.1
+ make -j2 DESTDIR=/home/ohpc/rpmbuild/BUILDROOT/automake-ohpc-1.16.1-1.ohpc.2.0.0.x86_64 install
help2man: can't get `--help' info from automake-1.16
Try `--no-discard-stderr' if option outputs to stderr
make: *** [Makefile:3695: doc/automake-1.16.1] Error 2
make: *** Waiting for unfinished jobs....
error: Bad exit status from /var/tmp/rpm-tmp.4A6fe2 (%install)
    Bad exit status from /var/tmp/rpm-tmp.4A6fe2 (%install)

The details you can find https://github.com/openhpc/ohpc/pull/1477

**Comment by adrianreber** [comment]
Please see #1479 for a fix.
