### ISSUE TITLE
lmod-defaults not available

### ISSUE THREAD

**Issue by marseaplage** [openhpc/ohpc#1486]
Hi guys,

Please help me !! I am not able to find "lmod-defaults" for my ohpc version:

 rpm -q ohpc-base
ohpc-base-2.2-13.1.ohpc.2.4.x86_64

cat /etc/redhat-release
CentOS Linux release 8.5.2111

I get this error when I execute the following command:

"yum -y install lmod-defaults-gnu9-openmpi4-ohpc"

Updating Subscription Management repositories.
Last metadata expiration check: 0:32:45 ago on Thu 29 Sep 2022 12:20:13 PM -05.
No match for argument: lmod-defaults-gnu9-openmpi4-ohpc
Error: Unable to find a match: lmod-defaults-gnu9-openmpi4-ohpc

I am following the guide: "Install Guide (v2.1): CentOS8.3/x86 64 + xCAT (stateful) + SLURM"

Thank you in advance for your help

**Comment by adrianreber** [comment]
Works for me on RHEL 8. Do you have the OpenHPC repository enabled?

**Comment by marseaplage** [comment]
> Works for me on RHEL 8. Do you have the OpenHPC repository enabled?

Hi Adrian.

Yes I have the following repo, but the package lmod-defaults-gnu9-openmpi4-ohpc doesn't exist:

cat OpenHPC.repo
[OpenHPC]
name=OpenHPC-2 - Base
baseurl=http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-2

[OpenHPC-updates]
name=OpenHPC-2 - Updates
baseurl=http://repos.openhpc.community/OpenHPC/2/updates/CentOS_8/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-2

Any ideas to solve this situation?

Thank you in advance for your help.

**Comment by adrianreber** [comment]
Where did you get this repository definition. This looks wrong. What do you get from:
```shell
$ rpm -qf /etc/yum.repos.d/OpenHPC.repo
$ rpm -V ohpc-release
```

**Comment by marseaplage** [comment]
> Where did you get this repository definition. This looks wrong. What do you get from:
> 
> ```shell
> $ rpm -qf /etc/yum.repos.d/OpenHPC.repo
> $ rpm -V ohpc-release
> ```

Hi

The output of the commands are:

rpm -qf /etc/yum.repos.d/OpenHPC.repo
ohpc-release-2-1.el8.x86_64
# rpm -V ohpc-release
S.5....T.    /etc/yum.repos.d/OpenHPC.repo

Is My openhpc repo wrong? If so, please tell me how to fix it. Thank you in advance for your help.

**Comment by adrianreber** [comment]
So rpm tells you that that file was modified and indeed it is wrong. It points to `x86_64` part of the repository and the package you are looking for is in `noarch`. The original line looks like this: `baseurl=http://repos.openhpc.community/OpenHPC/2/CentOS_8`

Maybe do a `dnf reinstall ohpc-release` and do not change the repository definitions after that manually.

**Comment by marseaplage** [comment]
> dnf reinstall ohpc-release

Could you please send me your Openhpc.repo because I got this error when I tried the command that you told me:

 dnf reinstall ohpc-release
Updating Subscription Management repositories.
Last metadata expiration check: 2:02:17 ago on Mon 03 Oct 2022 08:19:49 AM -05.
Dependencies resolved.
================================================================================================================
 Package                       Architecture            Version                   Repository                Size
================================================================================================================
Reinstalling:
 ohpc-release                  x86_64                  2-1.el8                   OpenHPC                   10 k

Transaction Summary
================================================================================================================

Total download size: 10 k
Installed size: 2.7 k
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] ohpc-release-2-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 10720 b                   ut expected size is: 10740
[MIRROR] ohpc-release-2-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 10720 b                   ut expected size is: 10740
[MIRROR] ohpc-release-2-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 10720 b                   ut expected size is: 10740
[MIRROR] ohpc-release-2-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 10720 b                   ut expected size is: 10740
[FAILED] ohpc-release-2-1.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without succes                   s

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download ohpc-release-2-1.el8.x86_64.rpm: All mirrors were tried

**Comment by adrianreber** [comment]
http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm

**Comment by marseaplage** [comment]
> http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm

Hi Adrian

But in github for openhpc 2.4 the rpm and tarballs are these ones:

Source: https://github.com/openhpc/ohpc/wiki/2.X

https://github.com/openhpc/ohpc/releases/download/v2.4.GA//ohpc-release-2-1.el8.x86_64.rpm

http://repos.openhpc.community/dist/2.4/OpenHPC-2.4.EL_8.x86_64.tar

Then I suppose that I have to wget this version: http://repos.openhpc.community/dist/2.4/OpenHPC-2.4.EL_8.x86_64.tar as the procedure located at the page#29 of the "OpenHPC (v2.1) Cluster Building Recipes" specifies. Is it correct?
In addition to that, I have a question for you: Should the Master node have access exclusively to the local  OpenHPC repository as well as the compute nodes or Should it have access only to the internet repository?

Thank you in advance for your answers.

**Comment by marseaplage** [comment]
> http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm

Hi Adrian.

I made the changes that you suggest but openhpc 2.4 as I mentioned before and the lmod-defaults is still not available. I think that it is only available for openhpc 2.1. But I do not know how bad it will affect my implementation.

**Comment by adrianreber** [comment]
Did you check that the file is actually used? If I remember it correctly RPM might not overwrite the file but create a `.rpmnew` file next to it.

If you look at our CI setup (https://github.com/openhpc/ohpc/blob/2.x/.github/workflows/validate.yml#L33) you see what we do every day many times without any problems.

**Comment by martin-g** [comment]
I guess this issue could be closed.
