### ISSUE TITLE
Question about the package 'gnu-compilers' upgrading?

### ISSUE THREAD

**Issue by huangtianhua** [openhpc/ohpc#1487]
I found the package 'gnu-compilers'  has been upgraded to 12, and there are many other packages related with mpi-compiler(now default is gnu12), I am now working on adapting ohpc packages on openEuler OS, and hope to release in 2.6, so I wonder what version of gnu-compiler I should use?

**Comment by adrianreber** [comment]
We are currently switching from GCC 9 to GCC 12. Currently the repository is not completely ready for GCC 12, but we are targetting GCC 12 for the next OpenHPC release.

**Comment by huangtianhua** [comment]
OK, thanks very much：）

**Comment by huangtianhua** [comment]
@adrianreber 
And as I mentioned I am working on adapting ohpc packages on openEuler OS, we hope to discuss with the community, I have proposed an issue: https://github.com/openhpc/ohpc/issues/1488
Welcome any suggestion about it, thank you!

**Comment by martin-g** [comment]
I think this issue could be closed!
