### ISSUE TITLE
Discuss： OpenHPC on openEuler support

### ISSUE THREAD

**Issue by huangtianhua** [openhpc/ohpc#1488]
Hi, OpenHPC teams!

We'd like to start the discussion about adding OpenHPC on openEuler OS (https://www.openeuler.org/en/) support.

As discussion in TSC meeting, we introduced the openEuler, a preliminary intention about cooperation was reached

After some consideration, the support work might roughly by below steps:

1. Add openEuler OpenHPC OBS worker.
Actually, we started to initial support on openEuler OBS:
[﻿https://build.openeuler.org/project/show/home:huangtianhua:ohpc](https://build.openeuler.org/project/show/home:huangtianhua:ohpc)
So we'd better move this to OpenHPC OBS, just like what rocky/leap do today.

2. Make rpm spec work on openEuler and merge to ohpc repo.
To ensure the quality we will first check on [2] to make sure it works on openEuler/SUSE/Rocky x86/aarch64
https://github.com/ohpc-openeuler/ohpc/pulls?q=is%3Apr+is%3Aclosed
But due to frequent upstream changes, we have to rebase frequently in downstream repo.
Could we submit some adaptations to the upstream repo (OpenHPC) directly?

3. Add openEuler CI to the ohpc upstream repo.
After all things completed, then we can enable the complete aarch64/x86 CI on OpenHPC repo:
Just like https://github.com/ohpc-openeuler/ohpc/pull/2/files

Any thoughts?

**Comment by martin-g** [comment]
The 3 points in the description are done!

The only TODO that comes to my mind is adding openEuler in the Jenkins setup.

**Comment by adrianreber** [comment]
This seems to be all done.
