### ISSUE TITLE
automate creation of `input.local`

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#152]
`input.local` on a small scale is functional, but as systems scale it becomes increasingly difficult to create this file.  A lot of information in this file can be generated by a script.

**Comment by alansill** [comment]
Please see the following for a demonstration of a solution to this problem for both IPMI-based (generally older) and Redfish-enabled (true for most newer) hardware:

Code: [Automating-the-scale-up-process-in-OpenHPC](https://github.com/nsfcac/Automating-the-scale-up-process-in-OpenHPC)
Presentation: [Introduce OpenHPC-Get-Mac Application](https://drive.google.com/file/d/1f3Yd5aaDj9zhgw_8wExsCsIUUdvJE7s5/view?usp=sharing)
Demo: [Introduce OpenHPC-Get-Mac Application](https://drive.google.com/file/d/1rSuk2ugNkjkiPHGa4pc7ef5pP9V6tV05/view?usp=sharing)
