### ISSUE TITLE
Missing mysql build for slurm in 1.1

### ISSUE THREAD

**Issue by o0v** [openhpc/ohpc#155]
Hi Folks,

 same issue (mysql is not build up for slurm) as in 
https://github.com/openhpc/ohpc/issues/113
for the 7.2 1.1 build.

 rpm -qlp http://build.openhpc.community/OpenHPC:/1.1:/Factory/CentOS_7.2/x86_64/slurm-sql-ohpc-15.08.1-5.1.x86_64.rpm 
/usr/lib64/slurm

 (should contain accounting_storage_mysql.so)

**Comment by JohnWestlund** [comment]
Sorry about that. I'm on top of it.

**Comment by JohnWestlund** [comment]
The fix is in 1.0.1 and 1.1, and a regression test has been added so we should catch this if it happens again.
