### ISSUE TITLE
document falling back to distro [l]pxelinux.0 if WW version fails

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#157]
We’ve also encountered issues with booting using the included WareWulf lpxelinux.0, and falling back to the dstro provided version often resolved these problems. We’re adding a note to the documentation regarding this possible problem.

**Comment by JohnWestlund** [comment]
This issue now has a visibility in the documentation, with suggestions for work arounds.

**Comment by koomie** [comment]
Note, this was assigned to 1.0.1 but landed on 1.1.  I just landed it on 1.0.1 and tweaked the language slightly.
