### ISSUE TITLE
Lustre 2.12/2.15?

### ISSUE THREAD

**Issue by liv-acollins** [openhpc/ohpc#1583]
Lustre has not been updated in the repo for quite some time and is falling a bit behind in terms of supporting the latest kernel that the rest of OHPC supports. It would be really great to finally get this available.

Currently the latest version in the repo is 2.12.7 (RHEL 8.4 kernel). Both the 2.12.9 and 2.15.1 releases support RHEL 8.6.

Will the latest Lustre update become available in the current OHPC release or is it planned for the next minor release?

Secondly, since 2.15.x is now LTS, will OHPC be moving to using 2.15.x? https://www.lustre.org/lustre-2-15-0-released/

**Comment by adrianreber** [comment]
For the upcoming 2.6 release we have already built 2.15.1

https://obs.openhpc.community/package/show/OpenHPC:2.6:Factory/lustre-client

**Comment by liv-acollins** [comment]
Fantastic. Thanks for the quick response. :)
