### ISSUE TITLE
add genders for pdsh node typing support

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#159]
Add LLNL `genders` and build `pdsh` with support for using the library

**Comment by JohnWestlund** [comment]
genders support is added. It's a dependency of pdsh to it gets pulled in when pdsh is installed.

Documentation could include creating an example genders file and basic usage.

**Comment by eshelman** [comment]
If it helps, here's what I've got in the genders file for a smaller cluster:
```
head                     master,login,nfshome
node[1-7]                compute
storage[1-4]             storage
```

**Comment by JohnWestlund** [comment]
Thanks @eshelman -- I'm looking at creating an example template via our install guide and your `genders` file is a good reference.

**Comment by crbaird** [comment]
tests passing in CI
