### ISSUE TITLE
intel-compilers-devel build unresolvable: nothing provides intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic

### ISSUE THREAD

**Issue by huangtianhua** [openhpc/ohpc#1590]
We can install package "intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic" after config the intel oneAPI.repo, but seems Requires(pre) ask the package before building?("Requires(pre): intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic >= %{min_intel_ver}" )

**Comment by adrianreber** [comment]
If you first install `intel-oneapi-toolkit-release-ohpc` does it work then?

**Comment by huangtianhua** [comment]
How to do this? Now I am working on adapting ohpc on openEuler system, https://build.openeuler.org/project/show/home:huangtianhua:ohpc  
you can see package 'intel-compilers-devel' is unresolvable, and if I delete the line "Requires(pre): intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic >= %{min_intel_ver}" in SPEC file , it works.

**Comment by adrianreber** [comment]
I would ignore the Intel compiler and Intel mpi for the start. This requires the Intel compiler which needs to be downloaded additionally.

Have a look at https://github.com/openhpc/ohpc/releases/download/v2.5.GA/Install_guide-Rocky8-Warewulf-SLURM-2.5-x86_64.pdf, chapter 4.7 for example.

I personally would ignore the optional Intel compiler for the first round and only look at it once you have everything working with the gnu12-compiler package.

**Comment by huangtianhua** [comment]
OK, I will have a look, thank you very much!
