### ISSUE TITLE
warewulf-provision build error: undefined reference to `stime'

### ISSUE THREAD

**Issue by huangtianhua** [openhpc/ohpc#1592]
I built warewulf-provision package on my environment which glibc is version 2.34, the error raised : undefined reference to `stime'. stime() has been deprecated in glibc 2.31 and replaced with clock_settime().

**Comment by adrianreber** [comment]
You should probably take this request to upstream warewulf and have it fixed there.

**Comment by huangtianhua** [comment]
Yes, I have proposed one, thanks!

**Comment by Yikun** [comment]
@huangtianhua Would you mind also paste the warewulf usptream link here?

**Comment by huangtianhua** [comment]
https://github.com/warewulf/warewulf3/issues/315

**Comment by martin-g** [comment]
This issue could be closed.
Fixed with: https://github.com/openhpc/ohpc/pull/1716 and https://github.com/openhpc/ohpc/pull/1723
