### ISSUE TITLE
stop using bootstrap script to install EasyBuild, just use 'pip install'

### ISSUE THREAD

**Issue by boegel** [openhpc/ohpc#1597]
As mentioned in #1593, the `.spec` file for installing EasyBuild should be updated to stop using the bootstrap script, [which is deprecated since June 2021](https://github.com/easybuilders/easybuild-framework/pull/3742).

For quite a while now (since EasyBuild v4.0.0), EasyBuild is a pretty standard Python package that can be installed with standard Python tools like `pip install`.

The only peculiar thing about the [`easybuild`](https://pypi.org/project/easybuild) Python package is that it's a meta-package: it basically only pulls in the 3 packages that *actually* provide the EasyBuild code and accompanying easyconfigs (build recipes, in some sense): [`easybuild-framework`](https://pypi.org/project/easybuild-framework), [`easybuild-easyblocks`](https://pypi.org/project/easybuild-easyblocks), [`easybuild-easyconfigs`](https://pypi.org/project/easybuild-easyconfigs).

**Comment by adrianreber** [comment]
Thanks for opening this tracking bug. I looked at it for a short time and the three packages was what confused me. There are a lot of macros to handle Python packages but with `easybuild` being a meta-package it was not immediately clear what to do.

Let's try to get it ready for the 2.7 release. We are in the middle of the 2.6 work and I do not think we want to introduce bigger changes at this point.

**Comment by adrianreber** [comment]
Fixed in #1621
