### ISSUE TITLE
add powerman as powercontrol abstraction layer

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#161]
`powerman` can use a large number of power control technologies (IPMI, smart PDU, etc) under the covers while presenting a consistent simple interface.

**Comment by JohnWestlund** [comment]
`IPMI_PASSWORD` needs to be correctly set for service to start. Assumes powercontrol is via IPMI.

**Comment by koomie** [comment]
Going to open this back up and push to future version.  Seeing some strangeness with reporting results and unable to recommend a configuration that doesn't expose world-readable credentials.

**Comment by adrianreber** [comment]
Closing as powerman was never built for 2.x nor 3.x.
