### ISSUE TITLE
Any thoughts on Intel's LLVM based compilers (icx, icpx, ifx)?

### ISSUE THREAD

**Issue by ruixingw** [openhpc/ohpc#1613]
If one use the latest version of Intel classic compliers (icc, icpc, ifort) to compile something, a warning message is shown as below:
> icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.

So Intel will remove icc/icpc/ifort from oneAPI in mid 2023. not sure if they will provide the last version of them after then.

A popular molecular dynamics simulation program, GROMACS, has ended the support of `icc/icpc`, and started to support `icx/icpx`.
> The Intel classic compiler (icc/icpc) is no longer supported in GROMACS. Use Intel’s newer clang-based compiler from oneAPI, or gcc. (https://manual.gromacs.org/current/install-guide/index.html)

IIRC, GROMACS is written in C/C++, and it is good with `icx/icpx`. Unfortunately, it seems that the fortran compiler `ifx` isn't as functional as `ifort` at the moment. CP2K doesn't support `ifx` for its "Incomplete Fortran standards support". (https://www.cp2k.org/dev:compiler_support)

I am wondering what is the OpenHPC teams' thought on this? It might be too premature to make any conclusion or decision though.

**Comment by martin-g** [comment]
related: https://github.com/openhpc/ohpc/issues/1692

**Comment by adrianreber** [comment]
3.x uses the new backend
