### ISSUE TITLE
Missing `nagios-common-ohpc` (nrpe-ohpc required)

### ISSUE THREAD

**Issue by Yikun** [openhpc/ohpc#1619]
`nagios-common-ohpc` is required by `nagioos-nrpe`, but looks like the package nagios-common-ohpc is already removed by ohpc in source tree? 

https://github.com/openhpc/ohpc/blob/58ce19b408e025f798a8e49a8db6dab2d0ce0870/components/admin/nrpe/SPECS/nrpe.spec#L60

The missing required error:
![image](https://user-images.githubusercontent.com/1736354/204180590-4d11b541-08e5-4970-84c5-05ba3fec54e7.png)

**Comment by Yikun** [comment]
And we also noticed that `nrpe` is not published in `2.x` (looks like a pkg in 1.x).

Should we clenup:
https://github.com/openhpc/ohpc/blob/58ce19b408e025f798a8e49a8db6dab2d0ce0870/misc/obs/config.2.x#L15

and spec in 2.x source tree?

**Comment by adrianreber** [comment]
The whole nagios monitoring setup was dropped in 2.x.  It should probably be cleaned up, yes.
