### ISSUE TITLE
netcdf-intel-openmpi4-ohpc 4.9.0 build not complete

### ISSUE THREAD

**Issue by kittirak** [openhpc/ohpc#1622]
```
$ncdump
ncdump: symbol lookup error: /opt/ohpc/pub/libs/intel/openmpi4/netcdf/4.9.0/lib/libnetcdf.so.19: undefined symbol: __libm_feature_flag_x
```

workaround, i move back to using netcdf-4.7.4 in update2.5 repo http://repos.openhpc.community/OpenHPC/2/update.2.5/CentOS_8

**Comment by kittirak** [comment]
sorry,  cannot reproduce it.

**Comment by adrianreber** [comment]
Are you saying you do not see the error anymore and this ticket can be closed?

**Comment by ckippe** [comment]
We have the same behavior here. But it's running under CentOS-8.1 and glibc-2.28-72.el8_1.1. That might play a role ...

**Comment by rherbst77** [comment]
Same behaviour. It seems, the NetCDF package was compiled against the libimf.so contained in the Intel compiler toolkit version 2023.0.0. This library contains the requested symbols:
```
# nm /opt/intel/oneapi/compiler/2023.0.0/linux/compiler/lib/intel64_lin/libimf.so | grep '__libm_feature_flag_x'
00000000003e45c0 b __libm_feature_flag_x
0000000000024f50 t __libm_feature_flag_x_init
```
We installed that compiler version, but the error remains.
OpenHPC 2.6 for CentOS 8.

**Comment by adrianreber** [comment]
> We installed that compiler version, but the error remains.
> OpenHPC 2.6 for CentOS 8.

Do you still the error with the compiler 2023.0.0? Or does that compiler work for you? Not 100% sure what you are saying?

**Comment by rherbst77** [comment]
I still get the error even after I installed the Intel compiler 2023.0.0 and set the LD_LIBRARY_PATH respectivly:

```
echo $LD_LIBRARY_PATH 
/opt/ohpc/pub/libs/intel/openmpi4/netcdf/4.9.0/lib:/opt/ohpc/pub/libs/intel/openmpi4/hdf5/1.10.8/lib:/opt/ohpc/pub/mpi/libfabric/1.13.0/lib:/opt/ohpc/pub/mpi/ucx-ohpc/1.11.2/lib:/opt/ohpc/pub/libs/hwloc/lib:/opt/ohpc/pub/mpi/openmpi4-intel/4.1.4/lib:/opt/intel/oneapi/mkl/2022.1.0/lib/intel64:/opt/intel/oneapi/compiler/2023.0.0/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/2023.0.0/linux/lib:/opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64:/opt/intel/oneapi/compiler/2023.0.0/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/tbb/2021.6.0/lib/intel64/gcc4.8

which ncdump
/opt/ohpc/pub/libs/intel/openmpi4/netcdf/4.9.0/bin/ncdump

/opt/ohpc/pub/libs/intel/openmpi4/netcdf/4.9.0/bin/ncdump
/opt/ohpc/pub/libs/intel/openmpi4/netcdf/4.9.0/bin/ncdump: symbol lookup error: /opt/ohpc/pub/libs/intel/openmpi4/netcdf/4.9.0/lib/libnetcdf.so.19: undefined symbol: __libm_feature_flag_x
```
