### ISSUE TITLE
Enable intel xpu plugin in slurm

### ISSUE THREAD

**Issue by gassyfeve** [openhpc/ohpc#1623]
Enable gpu_oneapi plugin in slurm.spec

**Comment by adrianreber** [comment]
> Enable gpu_oneapi plugin in slurm.spec

Does this feature need any additional libraries? Packages?

Trying to enable the configure option I get:
```
checking for ze_api.h... no
checking for zeInit in -lze_loader... no
configure: error: unable to locate libze_loader.so and/or ze_api.h
```

Maybe you could provide a patch against our `slurm.spec` to enable the feature. A test to verify that the features is enabled correctly would also be helpful.
