### ISSUE TITLE
Upgrade ADIOS component to ADIOS2 (2.8.3)

### ISSUE THREAD

**Issue by martin-g** [openhpc/ohpc#1639]
There are some problems in the build of ADIOS (v1) related to Python2, see https://github.com/openhpc/ohpc/issues/872.

The ADIOS developers [suggest](https://github.com/ornladios/ADIOS/issues/216#issuecomment-1347768036) to upgrade/move to ADIOS2 instead.

**Comment by martin-g** [comment]
I am going to work on a PR for this!

**Comment by adrianreber** [comment]
@mghpcsim do we want to go through the usual submission process for adios2 or do we say it is just an upgrade. On the one hand it is a new component, but it could also be seen as an upgrade.
