### ISSUE TITLE
Lustre client 2.15.1-5.1.ohpc.2.6 causing crash

### ISSUE THREAD

**Issue by liv-acollins** [openhpc/ohpc#1655]
My compute node is running:

$ dnf --installroot=test_image list installed | grep lustre
kmod-lustre-client-ohpc.x86_64           2.15.1-5.1.ohpc.2.6                  @OpenHPC-updates
lustre-client-ohpc.x86_64                2.15.1-5.1.ohpc.2.6                  @OpenHPC-updates

$ cat etc/redhat-release
Rocky Linux release 8.6 (Green Obsidian)

When writing to the Lustre storage the compute node locks up completely (LBUG crash?). I'm unable to access any further logs due to lock up. My compute node can read directory listings/file contents, but any attempt to create a new file results in a crash.

Is there any known issues with this package?

**Comment by adrianreber** [comment]
> Is there any known issues with this package?

You are the first to report this problem. I have not heard any reports before.
