### ISSUE TITLE
Correct ipcx settings

### ISSUE THREAD

**Issue by adrianreber** [openhpc/ohpc#1692]
Currently we do the following if the intel compiler is activated:
```
    export toolset=intel
    export CC=icc
    export CXX=icpc
    export FC=ifort
    export F77=ifort
    module purge
    module load intel
```

What should we set this to if we want to default to `ipcx`?

CC: @mghpcsim @jcsiadal

**Comment by jcsiadal** [comment]
export CC=icx
    export CXX=icpx
    export FC=ifx
    export F77=ifx

We also need to configure defaults for MPI (mpicc mpicxx mpif90, etc). The other question is: whether we should configure these environment defaults in setup scripts, or more generally in the modules themselves?
