### ISSUE TITLE
intel-advisor (v16.1.30.450722)

### ISSUE THREAD

**Issue by tron88** [openhpc/ohpc#170]
https://registrationcenter.intel.com/

**Comment by tron88** [comment]
PSXE_2016_update2 or Advisor_XE_2016_update3 available in IRC as of Feb 18, 2016

**Comment by koomie** [comment]
Landed on 1.1 branch.

**Comment by koomie** [comment]
Builds enabled.

**Comment by koomie** [comment]
CI tests passing.
