### ISSUE TITLE
pathway for new openhpc releases

### ISSUE THREAD

**Issue by marseaplage** [openhpc/ohpc#1701]
Hi guys.

I need your guidance in order to upgrade my openhpc system. I have already implemented the openhpc 2.6 with xcat 2.16.4 on CentOS Linux release 8.5.2111 according to the openhpc manual with xcat stateful. but I am not able to upgrade the openhpc anymore because I have several conflicts when I try "yum upgrade". Also I notice that xcat is not supported anymore by openhpc according to this url: [](https://github.com/openhpc/ohpc/wiki/2.x.) . 
I think that I have to upgrade to Centos Stream 8 but what about openhpc with xcat? What can I do to continue upgrading the system to make it compatible?

**Comment by adrianreber** [comment]
Closing here as it has been discussed on the mailing list and slack.
