### ISSUE TITLE
It seems the rpm package "ohpc-release-2-1.el8.x86_64.rpm" can't get normally

### ISSUE THREAD

**Issue by Eipgen** [openhpc/ohpc#1717]
I'm building ohpc in rocky linux 8.7 according to the docs . I add the ohpc rpm package and it can't  visit normally.

```
yum install http://repos.openhpc.community/OpenHPC/2/EL_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm
```

**Comment by adrianreber** [comment]
Seems like our repository server is down.

@koomie @mghpcsim Something is not right with repos.openhpc.community

**Comment by adrianreber** [comment]
Works again. Closing. Please re-open if you still see a problem.

**Comment by Eipgen** [comment]
it seems ok, thank you very much
