### ISSUE TITLE
Failed to install `warewulf-provision` (dev branch)

### ISSUE THREAD

**Issue by Yikun** [openhpc/ohpc#1726]
```
Error: 
 Problem: conflicting requests
  - nothing provides perl(Apache) needed by warewulf-provision-ohpc-server-3.10.0-19999.ci.ohpc.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

It seems also hited in CI:
- openEuler: https://github.com/openhpc/ohpc/actions/runs/4292476945/jobs/7479261414
- RHEL: https://github.com/openhpc/ohpc/actions/runs/4292476945/jobs/7479203715

But no failure show before

**Comment by Yikun** [comment]
cc @martin-g

**Comment by adrianreber** [comment]
Closing as we do not see this in CI.
