### ISSUE TITLE
UCX version

### ISSUE THREAD

**Issue by enuff-tech** [openhpc/ohpc#1776]
While testing out NDR equipment we’ve run into an issue – namely, NDR won’t work. Our guys have found out that ucx v1.12 and higher is required - however both ohpc 2.0 and the future release are still at 1.11. Any chance UCX versions can be upgraded ?

**Comment by adrianreber** [comment]
For 3.0 it should not be a problem.

**Comment by adrianreber** [comment]
UCX has been upgraded to 1.14 for 2.7 and 3.0.

**Comment by enuff-tech** [comment]
Thank you. Btw, when is the release date for 2.7 ? (need to know if we have time to test before our own next release)

**Comment by adrianreber** [comment]
> Thank you. Btw, when is the release date for 2.7 ? (need to know if we have time to test before our own next release)

We hope to have the release ready around ISC23.

**Comment by adrianreber** [comment]
@enuff-tech do you have experience concerning the UCX ABI? Does an UCX update require the rebuild of its dependencies or should it just work as a replacement?

**Comment by enuff-tech** [comment]
From what my team tested so far, newer versions should work as stand-in replacements (there should be no need for a rebuild of all components)
