### ISSUE TITLE
module default path does not use %OHPC_PUB/modulefiles

### ISSUE THREAD

**Issue by surak** [openhpc/ohpc#180]
One needs to add a
    module use /opt/ohpc/pub/modulefiles/

In order to see the modules generated by openhpc's tools. This should be default.

**Comment by koomie** [comment]
The `/opt/ohpc/pub/modulefiles` path is setup by an "ohpc" module that is provided via a variety of lmod-defaults RPMs. The original motivation here was to provide multiple default login environment options (in terms of compiler/MPI families) so there are 6 lmid-defaults packages at present to choose from:

```
lmod-defaults-gnu-impi-ohpc.noarch
lmod-defaults-gnu-mvapich2-ohpc.noarch
lmod-defaults-gnu-openmpi-ohpc.noarch
lmod-defaults-intel-impi-ohpc.noarch
lmod-defaults-intel-mvapich2-ohpc.noarch
lmod-defaults-intel-openmpi-ohpc.noarch
```

The example recipe installs ```lmod-defaults-gnu-mvapich2-ohpc``` and if you installed that package, you should get ohpc modules visible on a fresh login.

**Comment by surak** [comment]
I agree, but those packages themselves do not add the "ohpc" module to a default location (it goes exactly to %OHPC_PUB/modulefiles which is not visible)

I just tried with lmod-defaults-gnu-openmpi-ohpc.noarch

    # rpm -ql lmod-defaults-gnu-openmpi-ohpc
    /opt/ohpc
    /opt/ohpc/pub
    /opt/ohpc/pub/modulefiles
    /opt/ohpc/pub/modulefiles/ohpc
    # module avail
    -------------------------- /opt/ohpc/admin/modulefiles ---------------------------
       clck/3.0.1
    Use "module spider" to find all possible modules.
    Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".

    # module load ohpc
    Lmod has detected the following error: The following module(s) are unknown: "ohpc"

However, when forcing the location, it works: 

    # module use /opt/ohpc/pub/modulefiles/
    # module load ohpc
    # module avail
    -------------------------- /opt/ohpc/pub/moduledeps/gnu-openmpi ---------------------------
    tau/2.24.1
    --------------------------- /opt/ohpc/pub/moduledeps/gnu ---------------------------
    mkl/16.0.0.109    openmpi/1.8.8 (L)    pdtoolkit/3.20
    --------------------------- /opt/ohpc/pub/modulefiles ---------------------------
    EasyBuild/2.3.0    cube/4.3.3    gnu/5.2.0 (L)    intel/16.0.0.109    ohpc (L)    papi/5.4.1    prun/1.0 (L)    valgrind/3.10.1
    --------------------------- /opt/ohpc/admin/modulefiles ---------------------------
    clck/3.0.1



So, either the "ohpc" module should go to the "admin" directory or those packages should add pub/modulefiles as a valid place.

**Comment by koomie** [comment]
Ahh, thanks for the additional details. I think I have more of a clue now. The profile.d scripts that are included with lmod-ohpc are where the initial default MODULEPATH(s) get setup. However, these are sensitive to whether you are root or non-root.  From your post, it looks like you might be root, so you get the default administrator path.  I'm betting (hoping) if you repeated the same exercise as a non-root user, you would get ohpc loaded.

**Comment by surak** [comment]
You are right, thanks.
