### ISSUE TITLE
OpenHPC compatibility with Rocky9 and RHEL9

### ISSUE THREAD

**Issue by Yujaeseo** [openhpc/ohpc#1814]
Does the latest version of OpenHPC support Rocky9 and RHEL9?? If i install OpenHPC on those linux versions, could there be compatibility issues?? and i want to know the 3.x version is still in development.

**Comment by martin-g** [comment]
> Does the latest version of OpenHPC support Rocky9 and RHEL9??

3.x supports RHEL9.
2.x supports RHEL8.

> If i install OpenHPC on those linux versions, could there be compatibility issues??

Now is the time to test 3.x and give feedback!

> and i want to know the 3.x version is still in development.

Yes! The plan is to release it in one month.

**Comment by adrianreber** [comment]
> If I install OpenHPC on those linux versions, could there be compatibility issues?

I would not install the existing 2.x release on RHEL 9 or one of the clones. Like @martin-g we are working on the 3.x release which should work on RHEL 9 (and clones), LEAP 15.4 and openEuler 22.03.

Please close the ticket if this answers your questions.

**Comment by Yujaeseo** [comment]
Thanks for reply, @martin-g , @adrianreber! I hope to see the new version for RHEL9 soon.
