### ISSUE TITLE
Slurmrestd jwt support

### ISSUE THREAD

**Issue by msteggink** [openhpc/ohpc#1815]
The RPM's for SLURM are appearing to be missing the JWT support / JWT authentication (/usr/lib64/slurm/rest_auth_jwt.so). Would it be possible to add this to the SPEC files?

Without this, only unix sockets will work.
(EPEL has it included, although only version 20.11.9, https://bugzilla.redhat.com/show_bug.cgi?id=1947878)

**Comment by adrianreber** [comment]
Sounds doable. Can you provide a pull request with the corresponding changes?

**Comment by adrianreber** [comment]
Closing this as the latest 2.x (2.8) release should have it enabled and the upcoming 3.1will also have it enabled.
