### ISSUE TITLE
slurmd is not enabled/started on Rocky/Warewulf/Slurm

### ISSUE THREAD

**Issue by middelkoopt** [openhpc/ohpc#1821]
The `slurmd` service is not enabled for Rocky/Warewulf/Slurm.  Needs to be enabled in chroot with
```
chroot $CHROOT systemctl enable slurmd
```

**Comment by middelkoopt** [comment]
Patched all OS/Arch combos for 2.x in #1822 and 3.x in #1939

**Comment by adrianreber** [comment]
Fixed in 2.x and 3.x. Thanks!
