### ISSUE TITLE
slurm.conf notes and updates

### ISSUE THREAD

**Issue by middelkoopt** [openhpc/ohpc#1823]
It is not clear from the the instructions that the node names much match (c1-c4), the hardware must match, and a `scontrol reconfigure` must be run for SLRUM to see the changes.  This was difficult for me as I have not touched SLURM in quite some time.  I ended up doing the following to clear out the node definitions, I am not sure if slurmd can now auto-detect some of these.
```
perl -pi -e 's/^NodeName=c\[1-4\].*$/NodeName=c[1-4] State=UNKNOWN/' /etc/slurm/slurm.conf
```

**Comment by adrianreber** [comment]
Can this be closed? Not that your PRs are merged.

**Comment by middelkoopt** [comment]
Ah, there is the button. I thought it needed to be closed by the project.  Closing.
