### ISSUE TITLE
mpif90 / mvapich2 compile issues on openhpc 2.x

### ISSUE THREAD

**Issue by mdeignan** [openhpc/ohpc#1833]
I have a new headend I am attempting to set up to migrate off an old Rocks 7 cluster. The user community is used to an mvapich2 environment.

I've installed the intel oneapi compiler and various mvapich2 components. No custom modifications. Modules currently loaded show as follows:

Currently Loaded Modules:
  1) autotools   2) prun/2.2   3) tbb/2021.9.0   4) compiler-rt/2023.1.0   5) oclfpga/2023.1.0   6) compiler/2023.1.0   7) mkl/2023.1.0   8) intel/2023.1.0   9) mvapich2/2.3.7  10) ohpc

if I attempt to compile a basic fortran program with mpifort, I get the following error:

 mpif90 token_ring.f90
xfortcom: Unknown command line argument '-dwarf-debug-flags'.  Try: '/usr/local/opt/intel/oneapi/compiler/2023.1.0/linux/bin-llvm/xfortcom --help'
xfortcom: Did you mean '--asan-debug-stack'?
compilation aborted for token_ring.f90 (code 1)

 which mpifort
/opt/ohpc/pub/mpi/mvapich2-intel/2.3.7/bin/mpifort

executing the script with echo shows me the compilation is aborting on the following command:

ifort -O3 -g -m64 -fexceptions -fstack-protector-strong -grecord-gcc-switches -mtune=generic -g -O3 token_ring.f90 -I/opt/ohpc/pub/mpi/mvapich2-intel/2.3.7/include -I/opt/ohpc/pub/mpi/mvapich2-intel/2.3.7/include -L/opt/ohpc/pub/mpi/mvapich2-intel/2.3.7/lib -lmpifort -Wl,-rpath -Wl,/opt/ohpc/pub/mpi/mvapich2-intel/2.3.7/lib -Wl,--enable-new-dtags -lmpi

through trial and error, I determined if I remove the "-grecord-gcc-switches" flag, the compile will work okay.

Is this the expected behavior, or is it an incompatibility or a bug in the mvapich2-intel-ohpc-2.3.7-5.3.ohpc.2.6.x86_64 package with the latest version (2023.1) of the Intel compilers?

For the moment I have edited the mpifort script to remove that flag from being passed as part of the ifort command string.

Thanks,
MD

**Comment by adrianreber** [comment]
Thanks for the report. As mentioned this is fixed in the 3.x branch with

https://github.com/openhpc/ohpc/commit/5dd866a9a12dea7d59f34269b625d08f7dc533fa

We just need that commit on the 2.x branch

**Comment by adrianreber** [comment]
To fix this correctly we need to rebuild at least mvapich2 also for the 2.7 release.
