### ISSUE TITLE
broken link to man pages in intel compilers 2016.2.181 modulefile

### ISSUE THREAD

**Issue by crbaird** [openhpc/ohpc#184]
The modulefile sets MANPATH to /opt/ohpc/pub/compiler/intel/compilers_and_libraries_2016.2.181/linux/man/en_US... but compilers_and_libraries_2016.2.181/linux/man is a broken link to ../../man. We should fix the link or set MANPATH to /opt/ohpc/pub/compiler/intel/documentation_2016/en/man/common as in 2016.0.109.

**Comment by koomie** [comment]
CI tests passing now with modulefile update.
