### ISSUE TITLE
Updates to wiki

### ISSUE THREAD

**Issue by IanLee1521** [openhpc/ohpc#185]
Hi there, just noticed that a few of the links to LLNL related projects are out of data on [the wiki](https://github.com/openhpc/ohpc/wiki/Component-suggestions).

* LaunchMon -> https://github.com/LLNL/LaunchMON
* magpie -> https://github.com/LLNL/magpie

And for scr, you could also / alternatively link to the GitHub repo, currently, https://github.com/hpc/scr

**Comment by koomie** [comment]
Thanks for the updated links - I updated the wiki.
