### ISSUE TITLE
SLURM spool directory missing

### ISSUE THREAD

**Issue by s-kuh** [openhpc/ohpc#1859]
In the `slurm-ohpc` package, the script that runs only creates `/var/spool/slurmctld`

```
# 10/20/22 - ohpc create spool directory
if [ ! -d /var/spool/slurmctld ];then
   mkdir -p /var/spool/slurmctld
   chown slurm: /var/spool/slurmctld
fi
```

However in the `slurm.conf.example` file (both locally installed and in the Slurm Github), the two spool directories are:

```
SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/spool/slurmctld
```

If one uses the example file as a template, Slurm won't work on the compute nodes because the `/var/spool/slurmd` directory doesn't exist.

**Comment by adrianreber** [comment]
Thanks for your report. Do you actually see an error somewhere? I looked at our recipes and we do not create the directory anywhere but from what I see the directory is automatically created if it doesn't exist.

**Comment by s-kuh** [comment]
In our case the spoolers are slightly different than the template so we do get an error:

```
$ grep spool /etc/slurm/slurm.conf
SlurmdSpoolDir=/var/spool/slurm/d
StateSaveLocation=/var/spool/slurm/ctld
```
The systemd process fails and when run manually:

```
$ /usr/sbin/slurmd -D -s --conf-server 172.16.224.12
slurmd: fatal: mkdir(/var/spool/slurm/d): No such file or directory
```

We intend to push out a configuration change to point both the spool and savestates to `/var/spool/slurmctld` later this week which *should* fix the issue. Also, it seems like (at least on our end) the slurm-ohpc package has a script that runs (sorry for wall of text) when the package installs and that creates the spool directory:

```
$ rpm -q --scripts slurm-ohpc
preinstall scriptlet (using /bin/sh):

# provide specific uid/gid to ensure that it is the same across the cluster
/usr/bin/getent group slurm >/dev/null 2>&1 || \
  /usr/sbin/groupadd -r slurm -g 202
/usr/bin/getent passwd slurm >/dev/null 2>&1 || \
  /usr/sbin/useradd -c "SLURM resource manager" \
  -d /etc/slurm -g slurm -s /sbin/nologin -r slurm -u 202

exit 0
postinstall scriptlet (using /bin/sh):

# 3/23/21 karl@oden.utexas.edu - fix perm for txt job accounting possibility
if [ ! -f /var/log/slurm_jobcomp.log ];then
    touch /var/log/slurm_jobcomp.log
    chown slurm: /var/log/slurm_jobcomp.log
fi

# 10/20/22 - ohpc create spool directory
if [ ! -d /var/spool/slurmctld ];then
   mkdir -p /var/spool/slurmctld
   chown slurm: /var/spool/slurmctld
fi

if [ -x /sbin/ldconfig ]; then
    /sbin/ldconfig /usr/lib64
fi
preuninstall program: /bin/sh
postuninstall scriptlet (using /bin/sh):
/sbin/ldconfig
[root@compute-2-06-13 ~]# rpm -q --scripts slurm-ohpc
preinstall scriptlet (using /bin/sh):

# provide specific uid/gid to ensure that it is the same across the cluster
/usr/bin/getent group slurm >/dev/null 2>&1 || \
  /usr/sbin/groupadd -r slurm -g 202
/usr/bin/getent passwd slurm >/dev/null 2>&1 || \
  /usr/sbin/useradd -c "SLURM resource manager" \
  -d /etc/slurm -g slurm -s /sbin/nologin -r slurm -u 202

exit 0
postinstall scriptlet (using /bin/sh):

# 3/23/21 karl@oden.utexas.edu - fix perm for txt job accounting possibility
if [ ! -f /var/log/slurm_jobcomp.log ];then
    touch /var/log/slurm_jobcomp.log
    chown slurm: /var/log/slurm_jobcomp.log
fi

# 10/20/22 - ohpc create spool directory
if [ ! -d /var/spool/slurmctld ];then
   mkdir -p /var/spool/slurmctld
   chown slurm: /var/spool/slurmctld
fi

if [ -x /sbin/ldconfig ]; then
    /sbin/ldconfig /usr/lib64
fi
preuninstall program: /bin/sh
postuninstall scriptlet (using /bin/sh):
/sbin/ldconfig
```

**Comment by adrianreber** [comment]
> `SlurmdSpoolDir=/var/spool/slurm/d`

So it seems slurmd cannot create recursive directory structures. `slurm/d`.

Not sure what OpenHPC can do to help you. The default which we use works (`SlurmdSpoolDir=/var/spool/slurmd`). That seems to work because it is just one level of directories below the already existing `/var/spool`. If you use another value for `SlurmdSpoolDir` it is not clear how OpenHPC can help you with your special value.

Any suggestions what we should do to help you?

**Comment by s-kuh** [comment]
...the rubber ducky strikes again. I now realize that it's not an issue that the `../spool/slurmd` directory isn't created by the package. We planned to change our deployment to get rid of the `slurm/d` directory and we'll change over from `slurm/ctld` to `slurmctld`.

I think this can be closed now, I don't foresee any issues using the defaults anymore! Thanks for the help!

**Comment by adrianreber** [comment]
> ...the rubber ducky strikes again

😉 no problem. Do you want to close the ticket yourself?
