### ISSUE TITLE
Need a rebuild for 3.x doc?

### ISSUE THREAD

**Issue by Yikun** [openhpc/ohpc#1876]
I download the [docs-ohpc-3.0.0-300.ohpc.47.1.aarch64.rpm](http://repos.openhpc.community/OpenHPC/3/openEuler_22.03/aarch64/docs-ohpc-3.0.0-300.ohpc.47.1.aarch64.rpm)

In the doc of `3.1 Enable OpenHPC repository for local use`:

![image](https://github.com/openhpc/ohpc/assets/1736354/d6180bc4-b852-4529-ad3f-6476b9d2d8eb)

seems there include a wrong link to enbale ohpc repo:

```patch
- [sms]# yum install http://repos.openhpc.community/OpenHPC/3/openEuler_2203/aarch64/ohpc-release-3-1.oe2203.aarch64.rpm
+ [sms]# yum install http://repos.openhpc.community/OpenHPC/3/openEuler_22.03/aarch64/ohpc-release-3-1.oe2203.aarch64.rpm
```

But I'm not sure where to fix it, seem we already fix it in OSRepo and OStree, or maybe just need a rebuild for doc?

Related: https://github.com/openhpc/ohpc/commit/98a02fb1e008c59c6e7f3824a9dac1daca3f0195

**Comment by Yikun** [comment]
The doc rpm was using https://github.com/openhpc/ohpc/commit/19a78d6dde09db9996cbafa9528efd7124be9fa1 

```
<servicedata>
<service name="tar_scm">
                <param name="url">https://github.com/openhpc/ohpc.git</param>
              <param name="changesrevision">19a78d6dde09db9996cbafa9528efd7124be9fa1</param></service></servicedata>
```

[1] https://obs.openhpc.community/package/view_file/OpenHPC3:3.0:Factory/docs/_service:tar_scm:_servicedata?expand=1

**Comment by adrianreber** [comment]
Please open a PR with a fix.

**Comment by martin-g** [comment]
I am not 100% certain but I think this has been fixed with https://github.com/openhpc/ohpc/commit/98a02fb1e008c59c6e7f3824a9dac1daca3f0195

**Comment by adrianreber** [comment]
Okay. But I am now confused. Is it a problem or not?

**Comment by martin-g** [comment]
I just checked the `.rpm`s at https://obs.openhpc.community/package/binaries/OpenHPC3:3.0:Factory/docs/openEuler_22.03 and the PDFs inside look OK to me!

```
[sms]# yum install http://repos.openhpc.community/OpenHPC/3/openEuler_22.03/x86_64/ohpc-release-3-1.oe2203.x86_64.rpm
```

```
[sms]# yum install http://repos.openhpc.community/OpenHPC/3/openEuler_22.03/aarch64/ohpc-release-3-1.oe2203.aarch64.rpm
```

**Comment by Yikun** [comment]
Oh, my bad! There are some wrong to validate the doc, I open the old pdf rpm cache ``docs-ohpc-3.0.0-300.ohpc.**42**.1.aarch64.rpm``

**Comment by Yikun** [comment]
I confirmed It's not a issue!

**Comment by adrianreber** [comment]
Good. Thanks for verifying.
