### ISSUE TITLE
`packit` and `testing-farm`

### ISSUE THREAD

**Issue by LecrisUT** [openhpc/ohpc#1886]
Hi everyone,

Just wanted to let you guys know of 2 projects that could be useful for this project:
- [`packit`](https://github.com/packit/packit)
  - Basically a CI interface for submitting jobs to `copr` and downstreams like `Fedora` or `Rhel`. There is a recent interest to [add OBS](https://github.com/packit/packit/pull/2067) as well. If there is interest for some features here, they are very welcoming folks
  - has a CLI interface that is friendly for newcomers to packaging
  - works with multi-package repo like this project
  - can link upstream development to automatically bump downstream distributions in either direction (upstream making PRs in downstream, or downstream listening to new releases in upstream)
- [`testing-farm`](https://docs.testing-farm.io/Testing%20Farm/0.1/index.html)
  - a CI testing environment used by packit and Fedora
  - focused on testing RPMs
  - can spawn and coordinate multiple hosts to test communication between each other. Would be useful for `slurm` and `warewulf`
  - main testing framework is `tmt` which is also platform independent, i.e. it can be run outside `testing-farm`, even locally
  - unfortunately, no freely available service for custom integration (outside of packit and fedora environment), because of how new it is, but I think the lead will be glad to discuss

**Comment by adrianreber** [comment]
Thanks for letting us know. We already have a setup to build our RPMs on pull requests, but the interesting thing from your list is "can link upstream development to automatically bump downstream distributions". That sounds like it could be really helpful.

`testing-farm` also sounds interesting. Currently we run tests on top of AlmaLinux, Rocky Linux, Leap 15.5 and openEuler 22.03.
