### ISSUE TITLE
Please update lmod to 8.7.31 to support Intel oneAPI debugger 2023.2.0 module file

### ISSUE THREAD

**Issue by opoplawski** [openhpc/ohpc#1905]
When trying to load the Intel debugger module I'm getting:
```
Loading debugger version 2023.2.0
Lmod has detected the following error:
/opt/intel/oneapi/modulefiles/debugger/2023.2.0: (debugger/2023.2.0): invalid command name
"getenv"
While processing the following module(s):
    Module fullname    Module Filename
    ---------------    ---------------
    debugger/2023.2.0  /opt/intel/oneapi/modulefiles/debugger/2023.2.0
```
Support for getenv was added to Lmod in version 8.7.31.

**Comment by adrianreber** [comment]
Thanks for the report. We have been aware of the problems but we didn't know that a newer lmod version fixes it.

@jcsiadal @mghpcsim fyi

**Comment by adrianreber** [comment]
2.7 will have 8.7.32. I just updated it and the first test runs are without errors: 
http://test.openhpc.community:8080/job/2.x/job/(2.7)%20-%20(rocky8.8,x86_64)%20(warewulf+slurm)%20(fabric=eth)/15/

@jcsiadal does this mean we can use 2023.2.0 or 2023.2.1 for 2.7? If we can add the necessary changes today we can get a rebuild for the 2.7 branch and still have enough time to test next week.

**Comment by adrianreber** [comment]
Related: #1907

With the latest lmod I can install and load 2023.2.0 locally in a test container. So the lmod update really helps.

**Comment by adrianreber** [comment]
2.7 release is out with the latest version of Lmod. I will keep this open until we also have it in the 3.x branch

**Comment by adrianreber** [comment]
3.1 will have 8.7.34
