### ISSUE TITLE
Offline tar files for OpenHPC 2.7

### ISSUE THREAD

**Issue by ruixingw** [openhpc/ohpc#1908]
I cannot find tar files for OpenHPC 2.7 from http://repos.openhpc.community/dist/

Can you please add this? Thank you.

**Comment by adrianreber** [comment]
Thanks for the report. Hopefully they should be soon available.

**Comment by CyrilICGM** [comment]
Still not available today...

**Comment by adrianreber** [comment]
We moved to a new repository server with more diskspace and it should be available now
