### ISSUE TITLE
Error for the 2.7 repo in current Install recipes

### ISSUE THREAD

**Issue by derekjhunt** [openhpc/ohpc#1920]
There is an error on page 8 in the current Install recipe for Rocky 8 with Warewulf and Slurm for 2.ari7.  I checked the other install recipes, and the same incorrect URL is present in both x86_64 and aarch64, for both OS variants.

The documentation points to a repository:  **http://repos.openhpc.community/dist/2.7**
that does not exist.  Traversing the directory up one level to dist/ shows the highest version of of the 2.x branch as 2.6.1 from February. As mentioned above it's present in all of the install recipes.

**Comment by martin-g** [comment]
Here are the problematic lines:

https://github.com/openhpc/ohpc/blob/c4517fd4711271d1c339511bd7e6b56738b2a39f/docs/recipes/install/common/ohpc-doc.sty#L48

https://github.com/openhpc/ohpc/blob/c4517fd4711271d1c339511bd7e6b56738b2a39f/docs/recipes/install/common/enable_ohpc_repo.tex#L34

I guess it has to point to http://repos.openhpc.community/OpenHPC/2/update.2.7.1/

**Comment by adrianreber** [comment]
Thanks for the report. Is this actually something that breaks the recipe or just something you found that is wrong?

Our testing has not shown this and we use the recipes, but maybe we do not detect it correctly.

I think this related to #1908. `dist/` should be the location of the tar archives but we currently have problems with some parts of the infrastructure systems and cannot fix that easily.

**Comment by derekjhunt** [comment]
I don't think it breaks the recipe entirely, however, the instructions for a local repository won't work.  I think it is related to #1908 , this is just the front facing part.  The documentation does lead the user to believe they are install OpenHPC 2.7, not 2.6.  The name of the files even suggest that the install will be for that release.

**Comment by adrianreber** [comment]
We moved to a new repository server with more diskspace. tarballs are available now.
