### ISSUE TITLE
Update Score-P / Scalasca to new versions

### ISSUE THREAD

**Issue by Thyre** [openhpc/ohpc#1981]
Hi there,

I'm one of the developers working on the performance measurement infrastructure Score-P, mainly on the OpenMP and accelerator support.

After updating Score-P and OPARI2 to newer versions in the Fedora repositories, @adrianreber made me aware of Score-P and Scalasca being in the OpenHPC repositories and also mentioned that these are a bit outdated.

---

After discussing with colleagues for a bit, we're interested in providing newer versions of Score-P and Scalasca and try to keep them updated as well. We're doing the same thing for EasyBuild and spack already and also maintain a Ubuntu PPA for this. 

Based on the current state of the SPEC files, I would suggest the following approach:

- First, split the vendor packages delivered in Score-P into its own packages. Score-P normally includes the latest and greatest versions when it releases, but sometimes new versions of our dependent libraries release before a new version of Score-P. This is especially important with the idea to also integrate Cube GUI into OpenHPC (see https://github.com/openhpc/submissions/issues/49 ).
- Next, update Score-P for the latest versions. We are able to test things for Intel compilers and GCC and have a extensive internal testing suite for it. For Intel compilers (if the LLVM-based compilers are used), oneAPI 2024.0 or newer will be required as older versions will not give any information about called functions (unfortunately). 
- Then, update Scalasca. This should be straight-forward.

---

I'll probably start working on this in the coming days / weeks, depending on how much other work there is.

**Comment by adrianreber** [comment]
@Thyre Thanks a lot for your help. I agree with your approach. Let's do it.
