### ISSUE TITLE
Duplicate ReturnToService line in /etc/slurm/slurm.conf?

### ISSUE THREAD

**Issue by mikerenfro** [openhpc/ohpc#1991]
Currently have slurm-example-configs-ohpc-23.11.6-310.ohpc.5.1.x86_64 installed on Rocky 9.

https://github.com/openhpc/ohpc/blob/792e7cd3ba1aa486f2f8e2d4cd8494c98ca161c9/components/rms/slurm/SOURCES/slurm.conf.example.patch#L45

There are notes on the previous line indicating there was a `ReturnToService` variable removed earlier, but that doesn't appear to be the case.

```bash
[rocky@sms ~]$ grep ReturnToService /etc/slurm/slurm.conf.example
ReturnToService=1
# Adding ReturnToService Directive to starting config file (note removal of variable during above creation)
ReturnToService=1
```

Did I miss something, or should this line be removed from the patch, or the earlier ReturnToService line be removed via whatever method was proposed?

**Comment by adrianreber** [comment]
If the upstream file already contains the line then we do not have to include it second time. Removing it from the patch sounds correct. The git history is not entirely clear why it is removed and then added back. There is some discussion in #234.

Anyway, I think the patch can be adapted to not add the line. The comment also doesn't make any sense any more.
