### ISSUE TITLE
Rocky9-Warewulf-Slurm-3.1 rpcbind problem

### ISSUE THREAD

**Issue by a18090** [openhpc/ohpc#2001]
Hi all,

I have a problem, I get rpcbind problem on every boot.
I use Install_guide-Rocky9 (9.3) -Warewulf-Slurm-3.1-x86_64 to deploy my cluster, my network is:
Ethernet(pxe boot) + infiniband(slurm/nfs/mpi)
Network configuration `/etc/sysconfig/network-script/` It can be found that the Ethernet IP can be automatically configured successfully when entering the system, but the infiniband IP cannot be configured.
I tried to deploy the infiniband network configuration `network.ib  :  rw-r--r-- 1   root root   332 /etc/NetworkManager/system-connections/ibp65s0.nmconnection` to `/etc/NetworkManager/system-connections/ibp65s0.nmconnection`. I can see the IP when booting up, and running `ip a` shows it is correct.

I pointed nfs and slurmd to the address of IPoIB, but I found that these two services could not be started every time I started them, and I was prompted with an rpcbind error.
I tried to modify `/etc/rc.local systemctl restart rpcbind, systemctl restart slurmd, mount -a ` and slurmd and rpcbind service file in `/lib/systemd/system/`, and even after adding
to rpcbind and slurmd, I still couldn't get my nfs (rpcbind) and slurmd to start automatically.

slurmd:
```
[Unit]
Description=Slurm node daemon
After=munge.service network-online.target remote-fs.target sssd.service NetworkManager-wait-online.service
```
rpcbind:
`After=systemd-tmpfiles-setup.service network-online.target NetworkManager-wait-online.service`

dmesg error:
```
[   46.054206] systemd[2726]: rpcbind.socket: Failed to create listening socket (0.0.0.0:111): Address already in use
[   46.054625] systemd[1]: rpcbind.socket: Failed to receive listening socket (0.0.0.0:111): Input/output error
[   46.054642] systemd[1]: rpcbind.socket: Failed to listen on sockets: Input/output error
[   46.054758] systemd[1]: rpcbind.socket: Failed with result 'resources'.
[   46.054961] systemd[1]: Failed to listen on RPCbind Server Activation Socket.
[   46.055195] systemd[1]: Dependency failed for RPC Bind.
```

ibp65s0.nmconnection:
```
[connection]
id=ibp65s0
type=infiniband
interface-name=ibp65s0
autoconnect-priority=-999

[infiniband]
transport-mode=datagram

[ipv4]
address1=%{NETDEVS::IBP65S0::IPADDR}/24
method=manual

[ipv6]
addr-gen-mode=eui64
method=disabled
[proxy]
```

I tried rebuilding the image several times but the result is still the same, I'm not sure if it's a problem with my configuration or if there's a priority somewhere that needs to be adjusted?

**Comment by adrianreber** [comment]
The following line:
```
[   46.054206] systemd[2726]: rpcbind.socket: Failed to create listening socket (0.0.0.0:111): Address already in use
```
Somehow indicates that rpcbind is already running. I guess the combination of booting via Ethernet which mounts the root file system via Ethernet and then you want remount it using IPoIB, right?

It is also not clear what you do with `/etc/rc.local`, this is confusing.

Are you sure, that you need to restart rpcbind to listen to the IPoIB address. When I add a new IP address to my compute node rpcbind is also available on that IP address without restart rpcbind. Why are you trying to restart rpcbind?

When you talk about NFS, do you mean the root files system or things like `/opt/ohpc` and maybe `/home`?

Also, it usually it is not necessary to directly change files in `/lib/systemd/system/`. systemd offers the possibility to change part of those files in `/etc/systemd/system` without changing the OS supplied systemd definitions.

**Comment by a18090** [comment]
Hi @adrianreber ,

I booted with Ethernet(192.168.50.x/24) PXE and then mounted NFS with IPoIB(192.168.60.x/24).

The main reason I restarted rpcbind was because fstab could not automatically mount.

My manipulation of /etc/rc.local was only because rpcbind reported an error, so I restarted rpcbind and slurmd.

My original intention of modifying /lib/systemd/system was to determine that the application time of IPoIB was after rpcbind and slurmd, so I tried to make the service after the IPoIB network.


node systemctl status rpcbind
```
○ rpcbind.service - RPC Bind
     Loaded: loaded (/usr/lib/systemd/system/rpcbind.service; enabled; preset: enabled)
     Active: inactive (dead)
TriggeredBy: × rpcbind.socket
       Docs: man:rpcbind(8)

```

node systemctl status home.mount
```
× home.mount - /home
     Loaded: loaded (/etc/fstab; generated)
     Active: failed (Result: exit-code) since Wed 2024-08-07 01:04:10 ; 17h ago
      Where: /home
       What: 192.168.60.1:/home
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
        CPU: 7ms

Aug 07 01:04:10 gpu07 systemd[1]: Mounting /home...
Aug 07 01:04:10 gpu07 mount[3135]: mount.nfs: Network is unreachable
Aug 07 01:04:10 gpu07 systemd[1]: home.mount: Mount process exited, code=exited, status=32/n/a
Aug 07 01:04:10 gpu07 systemd[1]: home.mount: Failed with result 'exit-code'.
Aug 07 01:04:10 gpu07 systemd[1]: Failed to mount /home.
```

node slurmd:
```
× slurmd.service - Slurm node daemon
     Loaded: loaded (/usr/lib/systemd/system/slurmd.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Wed 2024-08-07 01:04:19 ; 16h ago
    Process: 3166 ExecStart=/usr/sbin/slurmd --systemd $SLURMD_OPTIONS (code=exited, status=1/FAILURE)
   Main PID: 3166 (code=exited, status=1/FAILURE)
        CPU: 6ms

Aug 07 01:04:10 gpu07 systemd[1]: Starting Slurm node daemon...
Aug 07 01:04:19 gpu07 slurmd[3170]: slurmd: error: _fetch_child: failed to fetch remote configs: Unable to contact slurm controller (connect failure)
Aug 07 01:04:19 gpu07 slurmd[3166]: slurmd: error: _establish_configuration: failed to load configs
Aug 07 01:04:19 gpu07 slurmd[3170]: error: _fetch_child: failed to fetch remote configs: Unable to contact slurm controller (connect failure)
Aug 07 01:04:19 gpu07 slurmd[3166]: slurmd: error: slurmd initialization failed
Aug 07 01:04:19 gpu07 slurmd[3166]: error: _establish_configuration: failed to load configs
Aug 07 01:04:19 gpu07 slurmd[3166]: error: slurmd initialization failed
Aug 07 01:04:19 gpu07 systemd[1]: slurmd.service: Main process exited, code=exited, status=1/FAILURE
Aug 07 01:04:19 gpu07 systemd[1]: slurmd.service: Failed with result 'exit-code'.
Aug 07 01:04:19 gpu07 systemd[1]: Failed to start Slurm node daemon.
```

node fstab:
```
#GENERATED_ENTRIES#
tmpfs /dev/shm tmpfs defaults 0 0
devpts /dev/pts devpts gid=5,mode=620 0 0
sysfs /sys sysfs defaults 0 0
proc /proc proc defaults 0 0
192.168.60.1:/home /home nfs rdma,nodev,nosuid 0 0
192.168.60.1:/opt/ohpc/pub /opt/ohpc/pub nfs rdma,nodev 0 0
192.168.60.1:/opt/intel /opt/intel nfs rdma,nodev 0 0
```

node rc.local:
```
#systemctl restart rpcbind
#mount -a
#systemctl restart slurmd
```

**Comment by adrianreber** [comment]
So this does not sound like it is an OpenHPC problem. Sounds more like a general problem of correctly ordering services.

Using Google I found this thread: https://groups.google.com/g/slurm-users/c/qHDPncrfYHQ

It seems a recommendation is to use `systemd-networkd-wait-online` with which it is possible to wait on specific network interfaces. Using `After=NetworkManager-wait-online.service` is successful after the first interface is ready. But you need to wait until your IPoIB interface is ready.

I would try to use that for your slurm configuration.

For the NFS mounts I would try to use also systemd mount definitions and have the mounts happen after the IPoIB interface is ready, just as with the slurm configuration.

As this does not seem directly an OpenHPC problem I think you could close the ticket if there are no further questions.

**Comment by a18090** [comment]
I'll try it again, thank you very much.

Because updating the ib network using sysconfig on rocky no longer works, it is recommended to adjust it to `/etc/NetworkManager/system-connections/n.nmconnection` in the new version, I don't know how to submit a PR on GitHub, sorry.
