### ISSUE TITLE
possible wrong prefix in MPIs

### ISSUE THREAD

**Issue by martinj80** [openhpc/ohpc#2003]
Hi, I noticed in OHPC3 than in both mpich and openmpi4, there is --with-ucx=/opt/ohpc/pub/mpi/ucx-ohpc/1.14.0, but current version should be 1.15.0. Is this relevant?

**Comment by adrianreber** [comment]
Thanks for the report. Can you give us an example where this error is visible? How did you detect the error and how can we reproduce it?

**Comment by martinj80** [comment]
hi, so far I have not really noticed anything specific as error, but I noticed it in the following:
I am using openmpi4-pmix-gnu12-ohpc.x86_64:

>ompi_info
                 Package: Open MPI abuild@ip-172-31-13-34 Distribution
                Open MPI: 4.1.5
  Open MPI repo revision: v4.1.5
   Open MPI release date: Feb 23, 2023
                Open RTE: 4.1.5
  Open RTE repo revision: v4.1.5
   Open RTE release date: Feb 23, 2023
                    OPAL: 4.1.5
      OPAL repo revision: v4.1.5
       OPAL release date: Feb 23, 2023
                 MPI API: 3.1.0
            Ident string: 4.1.5
                  Prefix: /opt/ohpc/pub/mpi/openmpi4-gnu12/4.1.5
 Configured architecture: x86_64-pc-linux-gnu
          Configure host: ip-172-31-13-34
           Configured by: abuild
           Configured on: Thu Aug  3 14:25:40 UTC 2023
          Configure host: ip-172-31-13-34
  Configure command line: '--prefix=/opt/ohpc/pub/mpi/openmpi4-gnu12/4.1.5'
                          '--disable-static' '--enable-builtin-atomics'
                          '--with-sge' '--enable-mpi-cxx'
                          '--with-hwloc=/opt/ohpc/pub/libs/hwloc'
                          '--with-pmix=/opt/ohpc/admin/pmix'
                          '--with-libevent=external'
                          '--with-libfabric=/opt/ohpc/pub/mpi/libfabric/1.18.0'
                          '--with-ucx=/opt/ohpc/pub/mpi/ucx-ohpc/1.14.0'
                          '--without-verbs' '--with-tm=/opt/pbs/'

**Comment by adrianreber** [comment]
You are looking at a package that was built for the OpenHPC 3.0 release. At that time we were building against UCX 1.14.0. The expectation is that if the SO name of a library does not change (UCX 1.14.0 -> UCX 1.15.0) it is not necessary to rebuild the users (Open MPI or MPICH). In OpenHPC 3.1 we updated UCX to 1.15.0. So the Open MPI package is from 3.0 and UCX is from 3.1. This is expected to work and so far we had no complaints.

Please let us know if you have further questions or else please close this ticket.

**Comment by martinj80** [comment]
thank you.
