### ISSUE TITLE
openEuler is missing at http://repos.openhpc.community/dist/3.1/

### ISSUE THREAD

**Issue by martin-g** [openhpc/ohpc#2004]
There are `.tar` files for openEuler at http://repos.openhpc.community/dist/3.0/ but there are no such at http://repos.openhpc.community/dist/3.1/

**Comment by adrianreber** [comment]
Thanks. I just saw that the old Perl script which creates those tarballs is not part of any git repository yet. This will also have to change.

**Comment by martin-g** [comment]
Activity to keep the bot happy

**Comment by adrianreber** [comment]
Please see https://repos.openhpc.community/dist/3.2/
