### ISSUE TITLE
sproradic errors from wwgetfiles

### ISSUE THREAD

**Issue by floerica** [openhpc/ohpc#2018]
Hello,

after upgrading the master node and compute nodes to the latest rhel8 release (including some ohpc packages), i see the following effect;
a few nodes do not get their files during boot time like
- /etc/passwd
- /etc/group
- /etc/shadow
- /etc/hosts
and most important:
- /etc/sysconfig/network-scripts/ifcfg-ib0

due to this several services are failing (including pbs as the mount for pbs is done via IBoIP) and user information is not available

if you execute wwgetfiles manually like 30 seconds after the reboot in most cases all looks fine and you just need to restart NetworkManager, remount nfs and restart pbs. But of course this is not a solution, just a manual hack and workaround. Rareky it complains that it can not download one of the files.

From what i see the http gives a returncode of 500 which i see strange. Can you give me any hint where to look further. As said, it happens on a some nodes (like 10-15 out of 32) but is causing me alot of trouble with manual tasks if i have to reboot the cluster.

this did not happen before the upgrade process, i did a full reboot, no issue seen

**Comment by adrianreber** [comment]
Please try to post your question to the user mailing list. There is much larger number of people who can help you there.

https://lists.openhpc.community/g/users

The GitHub repository is watched by a much smaller number of people (at least that is what I think).

**Comment by adrianreber** [comment]
https://lists.openhpc.community/g/users/message/5294
