### ISSUE TITLE
Error mount /

### ISSUE THREAD

**Issue by felixeye** [openhpc/ohpc#2025]
Hi all,

I am having a hard time booting the nodes of my mini cluster after making a new rocky9 image. I was hoping I could get some lift to help me move forward or some ideas. The mini cluster was running fine with centos-7 after upgrading to rocky 9 and making a new rocky 9 image, the boot process of the nodes fails when trying to mount / without more logs on the issue. I don't know how I can make warewulf show more log on this.
Thank you in advance for your help

[conman.log](https://github.com/user-attachments/files/17110214/conman.log)
[gpt.txt](https://github.com/user-attachments/files/17110228/gpt.txt)

**Comment by adrianreber** [comment]
Please try to post your question to the user mailing list. There is much larger number of people who can help you there.

https://lists.openhpc.community/g/users

The GitHub repository is watched by a much smaller number of people (at least that is what I think).

**Comment by felixeye** [comment]
Thank you for the tip @adrianreber, will do.
