### ISSUE TITLE
Lmod: why skip `make test`?

### ISSUE THREAD

**Issue by simonLeary42** [openhpc/ohpc#2027]
The Lmod documentation instructs users to run `./configure`, then `make`, then `make --install`. The OpenHPC Lmod spec says to run `./configure`, then `make --install`. This skips over the `test` target. Was this done intentionally? If so, why?

**Comment by adrianreber** [comment]
Thanks for reaching out. Can you provide a link to the documentation?

In an RPM spec file you would usually run the `check|test` target in the `%check` section. We are, however, as we have seen problems with certain tests in the RPM build environment, not running the tests during build time. Especially things which hope to run MPI enabled tests. We could run lmod tests but we try to run tests in the following two steps:

We have tests after `git push` or after a pull request: https://github.com/openhpc/ohpc/blob/3.x/.github/workflows/validate.yml

Any also we run over 1000 tests end-to-end (including some lmod tests) over our complete release: https://github.com/openhpc/ohpc/tree/3.x/tests

For our setup we decided that end-to-end testing gives us confidence that our releases work.

> Was this done intentionally?

Yes, it was.

**Comment by simonLeary42** [comment]
oh, I was actually misreading the documentation. I was reading the instructions for building Lua, not Lmod. 

https://lmod.readthedocs.io/en/latest/030_installing.html#install-lua-x-y-z-tar-gz

I think the `test` target must still be currently skipped because it uses a program called Hermes which is not included in the spec file.

The [debian Lmod package](https://packages.debian.org/bookworm/lmod) has sources `lmod-version.tar.gz` and `lmod-version-hermes.tar.gz`, so I was expecting to see an equivalent `Source0` and `Source1` in the spec file, but the spec file has only `Source0`.

https://github.com/openhpc/ohpc/blob/9313526a2e5fd129b493487da265d44650805944/components/admin/lmod/SPECS/lmod.spec#L24

the [Lmod makefile test target](https://github.com/TACC/Lmod/blob/3d7ad3b7bc0868eab689f8ce493ad88acb44bd9e/Makefile.in#L480) runs the `tm` command, which comes from Herems.
