### ISSUE TITLE
mvapich2 extremely slow

### ISSUE THREAD

**Issue by LaHaine** [openhpc/ohpc#207]
I'm currently testing OpenHPC using the included Intel MPI benchmark. I have noticed that IMB-MPI1 is extremely slow when started using mvapich2 compared to openmpi:
On two nodes with 8 processes on each, the openmpi build takes a time of 2:44,31, compared to 1:41:15,93 when using mvapich2.

Some of the tests even ran into a timeout.
There's also this error message on startup:
> WARNING: Error in initializing MVAPICH2 ptmalloc library.Continuing without InfiniBand registration cache support.

**Comment by koomie** [comment]
Thanks for this report.  Can you comment which OpenHPC version you are using (or conversely, which mvapich2 version is being installed)?

**Comment by LaHaine** [comment]
It is OpenHPC 1.0.1 with mvapich2-gnu-ohpc-2.1-2.1.x86_64.

**Comment by LaHaine** [comment]
The mvapich2 version shipped with EL7.2 (mvapich2-2.0a-3.el7.x86_64) is behaving fine, unlike the OpenHPC version.

**Comment by koomie** [comment]
Are you in a position to possibly try the current builds in 1.1 against CentOS 7.2?

http://build.openhpc.community/OpenHPC:/1.1:/Factory/CentOS_7.2/x86_64/mvapich2-gnu-ohpc-2.1-4.1.x86_64.rpm
http://build.openhpc.community/OpenHPC:/1.1:/Factory/CentOS_7.2/x86_64/mvapich2-intel-ohpc-2.1-6.1.x86_64.rpm

**Comment by LaHaine** [comment]
I have tested the gnu build, I have also updated the benchmark package to imb-gnu-mvapich2-ohpc-4.1-6.3.x86_64, still the same problem.

**Comment by koomie** [comment]
Looks like the issue for the ptmalloc initialization warning is related to the use of a newer gcc version.  In particular, the newer gcc 5.x versions are optimizing out some code bits which are negatively influencing the `mvapich2_minit()` function.  I have applied a patch which disables optimization for this particular function and when applied, I no longer see the warning message.  This has been landed on 1.1.

**Comment by koomie** [comment]
Also, I didn't see the same original slowness with MV2, but here are some IMB-MPI1 timings with the latest build that has the patch applied to enable registration cache support for newer gcc versions. I ran on 2 nodes, 8 MPI tasks/node on Mellanox FDR.

* MVAPICH2: 80.36 secs
* OpenMPI: 90.92 secs
* IMPI: 63.65 secs

**Comment by boegel** [comment]
@besserox: fyi, maybe good to point out to the MVAPICH2 dev team?

**Comment by koomie** [comment]
I did iterate with the MVAPICH2 dev team on this - they are aware of the behavior with newer gcc versions and I provided the patch applied here in case it's useful. There is also a related thread on the MV2 list at:

http://mailman.cse.ohio-state.edu/pipermail/mvapich-discuss/2016-March/005978.html

**Comment by boegel** [comment]
Excellent, thanks @koomie, just wanted to make sure :)

**Comment by LaHaine** [comment]
I have rebuilt the package with that patch, the warning is gone but IMB is still extremely slow.

**Comment by koomie** [comment]
Can you comment on what kind of IB hardware you are running on.  Do simple p2p tests give you the peak bandwidths you would expect?

**Comment by LaHaine** [comment]
I'm using Mellanox QDR Infiniband with Red Hat's OFED. I get fine bandwith using the same benchmark and OpenMPI.

**Comment by besserox** [comment]
@LaHaine I think you should bring your issue to the MVAPICH2 mailing list (http://mvapich.cse.ohio-state.edu/mailinglists/). They will be happy to help you debug your performance issue.

**Comment by koomie** [comment]
FYI, below are some PingPong measurements between 2 nodes that I get on Mellanox ConnectX-3 HCAs

#### MVAPICH2

```
$ prun IMB-MPI1 PingPong 
#---------------------------------------------------
# Benchmarking PingPong 
# #processes = 2 
#---------------------------------------------------
       #bytes #repetitions      t[usec]   Mbytes/sec
            0         1000         1.59         0.00
            1         1000         1.77         0.54
            2         1000         1.72         1.11
            4         1000         1.66         2.30
            8         1000         1.60         4.77
           16         1000         1.59         9.61
           32         1000         1.53        19.97
           64         1000         1.57        38.89
          128         1000         1.62        75.30
          256         1000         2.21       110.26
          512         1000         2.31       211.70
         1024         1000         2.61       373.77
         2048         1000         3.12       626.23
         4096         1000         3.69      1058.98
         8192         1000         5.30      1474.38
        16384         1000         7.82      1997.38
        32768         1000        11.68      2675.84
        65536          640        18.11      3450.26
       131072          320        31.04      4027.42
       262144          160        48.82      5121.09
       524288           80       108.52      4607.54
      1048576           40       211.84      4720.59
      2097152           20       418.48      4779.15
      4194304           10       832.13      4806.95
```

#### OpenMPI

```
#---------------------------------------------------
# Benchmarking PingPong 
# #processes = 2 
#---------------------------------------------------
       #bytes #repetitions      t[usec]   Mbytes/sec
            0         1000         1.69         0.00
            1         1000         1.77         0.54
            2         1000         1.74         1.10
            4         1000         1.75         2.18
            8         1000         1.74         4.38
           16         1000         1.73         8.81
           32         1000         1.73        17.66
           64         1000         1.79        34.08
          128         1000         2.63        46.39
          256         1000         3.52        69.34
          512         1000         3.20       152.44
         1024         1000         3.54       275.48
         2048         1000         5.15       379.10
         4096         1000         6.10       640.10
         8192         1000         8.13       960.94
        16384         1000         7.47      2092.13
        32768         1000        12.06      2591.64
        65536          640        15.38      4064.20
       131072          320        27.85      4487.87
       262144          160        46.72      5350.47
       524288           80        88.56      5646.14
      1048576           40       172.50      5797.14
      2097152           20       339.43      5892.22
      4194304           10       677.10      5907.57
```

**Comment by LaHaine** [comment]
I'm using QDR Infiniband here, this should be ConnectX-2.
The strange thing is that I get good values with this command:
/opt/ohpc/pub/mpi/mvapich2-gnu-ohpc/2.1/bin/mpirun -n 2 -hosts pax10,pax11 /opt/ohpc/pub/libs/gnu/mvapich2/imb/4.1/bin/IMB-MPI1
````
# Benchmarking PingPong 
# #processes = 2 
#---------------------------------------------------
       #bytes #repetitions      t[usec]   Mbytes/sec
            0         1000         1.66         0.00
            1         1000         1.74         0.55
            2         1000         1.73         1.10
            4         1000         1.74         2.20
            8         1000         1.72         4.43
           16         1000         1.75         8.71
           32         1000         1.79        17.06
           64         1000         1.82        33.61
          128         1000         1.97        62.08
          256         1000         3.15        77.62
          512         1000         3.40       143.78
         1024         1000         3.94       247.75
         2048         1000         4.92       397.24
         4096         1000         5.86       666.60
         8192         1000        10.16       768.63
        16384         1000        14.50      1077.71
        32768         1000        18.24      1713.10
        65536          640        28.73      2175.27
       131072          320        49.71      2514.61
       262144          160        91.52      2731.69
       524288           80       175.22      2853.49
      1048576           40       342.35      2920.98
      2097152           20       716.14      2792.74
      4194304           10      1429.87      2797.46
````
But I have bad values with this command:
/opt/ohpc/pub/mpi/mvapich2-gnu-ohpc/2.1/bin/mpirun -n 16 -hosts pax10,pax11 /opt/ohpc/pub/libs/gnu/mvapich2/imb/4.1/bin/IMB-MPI1
````
# Benchmarking PingPong 
# #processes = 2 
# ( 14 additional processes waiting in MPI_Barrier)
#---------------------------------------------------
       #bytes #repetitions      t[usec]   Mbytes/sec
            0         1000        39.96         0.00
            1         1000         1.52         0.63
            2         1000         1.53         1.25
            4         1000         1.52         2.51
            8         1000         1.51         5.05
           16         1000         1.58         9.63
           32         1000         1.60        19.03
           64         1000         1.66        36.83
          128         1000         1.83        66.62
          256         1000         3.02        80.86
          512         1000         3.28       149.02
         1024         1000         3.86       252.69
         2048         1000        15.58       125.33
         4096         1000        16.50       236.76
         8192         1000        20.00       390.60
        16384         1000        35.35       441.98
        32768         1000        46.71       668.96
        65536          640        57.74      1082.50
       131072          320       114.04      1096.11
       262144          160       230.87      1082.85
       524288           80       298.22      1676.60
      1048576           40       895.43      1116.79
      2097152           20      9689.93       206.40
      4194304           10      2499.97      1600.02
````

**Comment by koomie** [comment]
Weird. I tried the same exercise above locally and got consistent results between the -n 2 and -n 16 cases. I wonder if perhaps the case with 16 processes (where 14 of them should be idle) is making some non-ideal choices regarding cpu placement?

To test that, perhaps it might be helpful to query the cpu binding and set it to a fixed value.  For example:

```
export MV2_SHOW_CPU_BINDING=1
export MV2_CPU_MAPPING=0:1:2:3:4:5:6:7
```

That's probably not the optimal mapping, but it should set a known condition.

**Comment by LaHaine** [comment]
This helped a lot, I wonder why it is using bad defaults:
````
# Benchmarking PingPong 
# #processes = 2 
# ( 14 additional processes waiting in MPI_Barrier)
#---------------------------------------------------
       #bytes #repetitions      t[usec]   Mbytes/sec
            0         1000         1.54         0.00
            1         1000         1.64         0.58
            2         1000         1.63         1.17
            4         1000         1.57         2.43
            8         1000         1.60         4.76
           16         1000         1.56         9.78
           32         1000         1.62        18.82
           64         1000         1.68        36.42
          128         1000         1.85        65.90
          256         1000         3.01        81.18
          512         1000         3.29       148.61
         1024         1000         3.86       253.32
         2048         1000         4.82       405.23
         4096         1000         5.73       681.70
         8192         1000        16.39       476.66
        16384         1000        13.65      1144.56
        32768         1000        18.95      1648.91
        65536          640        44.33      1409.78
       131072          320        59.10      2115.09
       262144          160        96.76      2583.59
       524288           80       183.15      2729.98
      1048576           40       358.19      2791.83
      2097152           20       719.77      2778.65
      4194304           10      1640.70      2437.98
````

**Comment by koomie** [comment]
Not sure. I assume there are no other MV2_* env variables in your environment that might influence the defaults? It seems to making an acceptable default choice for me locally, however, I also tend to use specific affinity settings when possible for full control (and for hybrid codes).

**Comment by koomie** [comment]
FYI, I did hear back from the MVAPICH team indicating that the patch we have applied to support newer gcc builds will included in a future release.

@LaHaine, feel OK if I close this out?

**Comment by LaHaine** [comment]
OK, closing as the gcc5 issue was fixed by the patch. For the bad CPU binding, I'll mail the mvapich list later.
