### ISSUE TITLE
install guide references ifconfig, but not installed or dependency

### ISSUE THREAD

**Issue by suchytas** [openhpc/ohpc#211]
Referring to Install Guide v1.0.1, Rev: 7e93115, Section 3.6 Complete basic Warewulf setup for master node

```
# Enable internal interface for provisioning
[sms]# ifconfig ${sms_eth_internal} ${sms_ip} netmask ${internal_netmask} up
```

I installed with CentOS "Minimal" installation, and the ifconfig command is not installed by default. To resolve, I had to install net-tools

`yum install net-tools`

Thinking about proposals.. 
- Make net-tools a dependency when installing ohpc-warewulf.. since this was part of the warewulf configuration
- Update the documentation with `yum install net-tools`
- or??

**Comment by koomie** [comment]
Given that it is being called out in the docs recipe, I think I would propose we add it as an install dependency for the docs.

**Comment by koomie** [comment]
Added dependency to docs-ohpc to 1.1 branch:

```
# yum install docs-ohpc
OpenHPC                                                                                                                                                 448/448
Resolving Dependencies
--> Running transaction check
---> Package docs-ohpc.x86_64 0:1.1-121.1 will be installed
--> Processing Dependency: net-tools for package: docs-ohpc-1.1-121.1.x86_64
--> Running transaction check
---> Package net-tools.x86_64 0:2.0-0.17.20131004git.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
```

**Comment by koomie** [comment]
Thanks for the report Scott.
