### ISSUE TITLE
wwbootstrap&wwvnfs fail with "Insecure $ENV{BASH_ENV} while running with -T"

### ISSUE THREAD

**Issue by Ferron7** [openhpc/ohpc#219]
Hello everyone, 

using centos7.2 and openHPC 1.1, following the steps from the Installguide.

At the steps to create a vnfs and bootstrap with Warewulf, both commands exit with "Insecure $ENV{BASH_ENV} while running with -T switch at[...]" warning.

How can i fix/circumvent this warning?

**Comment by koomie** [comment]
For the time being, you can "unset BASH_ENV" prior to running the commands. We have a patch to resolve that warning that unfortunately did not get applied to 1.1 so we will resolve that in the next update.
