### ISSUE TITLE
add additional drivers to WW bootstrap for IB

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#222]
Reported on the openhpc-users list: https://groups.io/g/OpenHPC-users/message/193

Example solution: https://groups.io/g/OpenHPC-users/message/195

Let's patch Warewulf to include ib_isert and xprtdma

**Comment by jmstover** [comment]
Added patch upstream SVN trunk.

-J

**Comment by koomie** [comment]
Thanks for adding that.

**Comment by koomie** [comment]
WW patch landed in 1.1.1

**Comment by koomie** [comment]
Have confirmed that `service rdma` comes up ok with latest WW patch on IB system when the kernel package is not included in VNFS.
