### ISSUE TITLE
How to install on aarch64 arm-v8 platform ?

### ISSUE THREAD

**Issue by icekezuo** [openhpc/ohpc#251]
Hi all
Is it now possible to install openhpc on a platform based on aarch64 arm-v8 platform?
If positive, please guide me.

Many thanks

**Comment by koomie** [comment]
Hi,

Sorry for the delay.  We don't yet have hardware in place to support the build/test for arm, but it is work in progress and we expect to make builds available in a future release. I don't have a timeline just yet, but will certainly announce the availability when it happens on https://groups.io/g/OpenHPC-announce.
