### ISSUE TITLE
Conflict with installing multiple lmod-defaults

### ISSUE THREAD

**Issue by severinstojanovic** [openhpc/ohpc#262]
I'm not sure if the conflict with installing multiple lmod-defaults is a bug or intended behaviour.

I am working on constructing a new cluster and have opted to go the OpenHPC route. I have yet to benchmark which MPI implementation will best suit this cluster so I have been installing both OpenMPI and MVAPICH2 versions of everything for testing purposes. If there is no clear better option across the board, and some instances would yield one implementation more preferred over the other, then I would like to leave both installed and the choice would be made as needed.

The only conflict I have experienced thus far is with lmod-defaults when trying to install the two implementations side-by-side. The error it gives is that both write to the same file /opt/ohpc/pub/modulefiles/ohpc . The only differences in the file are "module try-add" and "module del", where each of these statements is followed by the appropriate MPI implementation.

Can a temporary solution be to manually add an entry so both MPI implementation are loaded, or will this break the system in some way? If having both loaded is technically fine, then maybe a permanent solution could be to have a script check which MPI implementations are installed and modify the file accordingly to contain the necessary entries?

**Comment by JohnWestlund** [comment]
This is intentional. This just sets the default compiler mpi loaded in a
new shell. You can still access the other MPI.

module swap openmpi mvapich2
Or
module swap mvapich2 openmpi

Once you've settled on one you can then keep or replace the defaults rpm
you have installed to make the mpi of your choice the default.

Best,
John

**Comment by severinstojanovic** [comment]
Perfect. Thanks a lot John! Since the behaviour is as intended, I'll close this Issue. Again, thanks.
