### ISSUE TITLE
Enable SLURM accounting storage

### ISSUE THREAD

**Issue by nirmalasrjn** [openhpc/ohpc#268]
To configure SLURM for storing accounting information for jobs, so that information about completed jobs can be viewed, and reports of job usage and cluster utilization can be generated.

**Comment by koomie** [comment]
@nirmalasrjn , sorry I didn't log commits against this open item...I did fix but forgot this was open. The simple flat file accounting storage was added to the default slurm configuration file for v1.3.  A test to confirm that `sacct` does not fail was also added to the integration test suite.
