### ISSUE TITLE
$num_computes not defined in install guide

### ISSUE THREAD

**Issue by severinstojanovic** [openhpc/ohpc#300]
It's used 5 times in each of the install guides, but is not defined anywhere. Cutting + pasting from the pages of the install guide as one goes through it page-by-page could cause execution errors. It should be documented with the other variables in section 1 with a direct means of setting its value by either:

1) Have the value explicitly set by the user; or, to minimize input error

2) Have it calculated as part of the install script using the MAC address entries supplied by the user, i.e., num_computes=${#c_mac[@]}. Using MAC is preferred to keep the install script as generic as possible because not all systems will have BMC and the entries for c_ip[ ] can themselves be automated in the install script given sms_ip and num_computes. This way the only direct user input is the MAC addresses, and that has to be supplied by a typical user anyways.

**Comment by koomie** [comment]
I like #1 and agree it should be called out as an explicit user setting.

**Comment by koomie** [comment]
Added ${num_computes} to Section 1.3.  Note that it was already highlighted as an input for use with the companion template installation script provided via the `docs-ohpc` package (input.local), but is now also mentioned explicitly as a required input in the docs.

Thanks for the suggestion.
