### ISSUE TITLE
Required passwordless ssh between compute nodes 

### ISSUE THREAD

**Issue by nirmalasrjn** [openhpc/ohpc#309]

**Comment by koomie** [comment]
This should already be accommodated via the pam/slurm module so that a user can ssh between nodes that are currently assigned to him/her. Are you observing different behavior?

**Comment by koomie** [comment]
@nirmalasrjn - just checking in. Is this still an issue?

**Comment by nirmalasrjn** [comment]
Yes. I still face this issue.

**Comment by jmstover** [comment]
Hi @nirmalasrjn ,

  Does the user you're trying to log in as have a cluster SSH key setup? If the home directories are shared, then as long as the authorized_keys file has the public part of the cluster key it should "just work."

  If not, is any errors being sent out in the syslogs? What about if you use the '-vvv' option when trying to SSH?

-J

**Comment by koomie** [comment]
Had a chance to talk with @nirmalasrjn in person to get more clarification. Turns out this was related to running jobs as root and is not an issue in normal operation.
