### ISSUE TITLE
aarch64 le7 pre-reqs

### ISSUE THREAD

**Issue by ericvh** [openhpc/ohpc#310]
Still missing fping and radiusclient-ng-devel aarch64 packages in EPEL7-deps - blocking nagios-plugins.

**Comment by koomie** [comment]
Sorry about that. I had `radiusclient-ng` but not `radiusclient-ng-devel`.  And, I had grabbed `fping-debuginfo` instead of `fping`. I imported the 2 missing packages and looks like your build kicked off.
