### ISSUE TITLE
Import SLES 12 SP 1 AARCH64

### ISSUE THREAD

**Issue by ericvh** [openhpc/ohpc#314]
SP1 to match OpenHPC, SP2 to match best current build for AARCH64.
(maybe I should split this into two different requests?)

**Comment by koomie** [comment]
I would suggest we have a separate request for SP2 when it is out. Note that we have to access SLES packages directly from the public OBS build instance at [build.opensuse.org](build.opensuse.org).  They do have aarch64 packages available for SP1 and I just enabled this repo for the 1.2 branch (Factory and Dep:Lmod).
