### ISSUE TITLE
PBS Professional (14.1.0)

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#320]
https://github.com/pbspro/pbspro

**Comment by koomie** [comment]
@suchytas, have you built this against SLES?  Looks like the hwloc-devel dependency is not resolved with part of standard SLES.....

**Comment by scottaltair** [comment]
@koomie I have confirmed with @mike0042 that he has built on the OBS instances that had CentOS and OpenSUSE.

**Comment by koomie** [comment]
@mike0042, what about SLES? What did you do for hwloc?

**Comment by mike0042** [comment]
@koomie The last time we built PBS Pro for OpenHPC we used the OBS instance you supplied running on AWS. I don't believe SLES was one of the targets, but rather CentOS and OpenSUSE. Is it the case that hwloc-devel is missing from SLES, or is something missing from the hwloc-devel package that is causing the dependency to fail?

**Comment by mike0042** [comment]
@koomie We used the files from this repo to build PBS Pro for OpenHPC: https://github.com/PBSPro/ohpc

**Comment by koomie** [comment]
It's the latter case; hwloc-devel is not included in SLES.

**Comment by mike0042** [comment]
@koomie Is there a way to setup a dependency within OpenHPC that allows PBS Pro to utilize the hwloc from the OpenMPI package? You may override the default location of hwloc when building PBS Pro by specifying "configure --with-hwloc=/hwloc/location"

**Comment by koomie** [comment]
possibly, but if the linkage is dynamic, that add's an openmpi dependency at install. Let me get the centos stuff going first...we can likely build hwloc specifically for sles if we have to.

**Comment by koomie** [comment]
@mike0042, seems the systemd service files did not make it into the 14.1.0 release, yes?

**Comment by mike0042** [comment]
@koomie Correct, they didn't make 14.1.0. The changes were committed to master here: https://github.com/PBSPro/pbspro/pull/70

Should we consider a 14.1.1 release with just those changes included? Let me know if this is a showstopper.

**Comment by koomie** [comment]
I think we'll want systemd; not a showstopper, but I'll have to patch in the changeset.

**Comment by koomie** [comment]
systemd-related patch applied.  I suspect more tweaks may be coming, but the initial builds are completing now on centos7 (both x86_64 and aarch64) 

```
RPMS/x86_64/pbspro-ohpc-execution-ohpc-14.1.0-11.1.x86_64.rpm
RPMS/x86_64/pbspro-ohpc-server-ohpc-14.1.0-11.1.x86_64.rpm
RPMS/x86_64/pbspro-ohpc-client-ohpc-14.1.0-11.1.x86_64.rpm

RPMS/aarch64/pbspro-ohpc-server-ohpc-14.1.0-11.1.aarch64.rpm
RPMS/aarch64/pbspro-ohpc-execution-ohpc-14.1.0-11.1.aarch64.rpm
RPMS/aarch64/pbspro-ohpc-client-ohpc-14.1.0-11.1.aarch64.rpm
```

**Comment by mike0042** [comment]
Terrific news! Thanks @koomie! Please let us know if there is anything we can contribute.

**Comment by koomie** [comment]
Thanks, definitely hoping to leverage help for a companion recipe for installation, configuration steps, etc. I'll create a starting docs housing point and hopefully ya'll can come back with some PRs to add snazzy content.

**Comment by koomie** [comment]
basic CI tests are passing now for CentOS and SLES
