### ISSUE TITLE
link cc to gcc

### ISSUE THREAD

**Issue by crbaird** [openhpc/ohpc#328]
create a cc soft link to gcc binary to match distro packaging

**Comment by crbaird** [comment]
Unable to dig up original motivation. Will reevaluate as necessary.

**Comment by jmstover** [comment]
Make defaults to a default value of `cc` for environment variables like CC... So, if in a Makefile you have:

`$(CC) -c [...]`

That would default to:  `cc -c [...]`

See: https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

Operationally, I don't believe there's a difference if it's called as `gcc` or `cc` beyond `--version` output where it uses `argv[0]`. I don't think it behaves differently depending on how it's called though.

But yeah... there should be a `cc` link to `gcc` if it doesn't exist.

-J
