### ISSUE TITLE
Missing SLES-12-SP1 SDK for AARCH64

### ISSUE THREAD

**Issue by ericvh** [openhpc/ohpc#335]
Need mirrors installed in testbed for AARCH64 including SDK rpms imported into build server.

**Comment by koomie** [comment]
Were you able to procure the ISO image for the SDK on SP1?

**Comment by ericvh** [comment]
It's uploading now, check in 15: /home/ericvh on the head node.

**Comment by koomie** [comment]
Ok, shall we just mirror on cv1 for the time being?

**Comment by ericvh** [comment]
that's fine.  At some point I'd like to move it to the head node mirror though so we can auto-deploy cv1 as well.

**Comment by koomie** [comment]
absolutely; let's make it pretty after SC :-)

**Comment by koomie** [comment]
This is superseded by newer releases which moved to SLE SP2. We now have both SP2 and the SDK mirrored on the CI environment at TACC.
