### ISSUE TITLE
Intel MPI module breaks with spaces in version number

### ISSUE THREAD

**Issue by chuckatkins** [openhpc/ohpc#343]
The impi shipped with Parallel Studio Cluster Edition 2017 Update 1 gets a version number for automatic module creation parsed as  "2017 Update 1".  The spaces in the filename break many other aspects of the module infrastructure.

**Comment by koomie** [comment]
Thanks for this report and companion PR.  Will get it scheduled/tested for an update against v1.2.

**Comment by koomie** [comment]
You have probably rebuilt locally, but just in case it's useful, there is an updated build in the 1.2.1 Factory available now. You can access at:

http://build.openhpc.community/OpenHPC:/1.2:/Update1:/Factory/CentOS_7.2/x86_64/intel-mpi-devel-ohpc-2017-16.1.x86_64.rpm

You will have to manually clean up the "2017 Update 1" modulefiles from the previous install though.

**Comment by chuckatkins** [comment]
The package upgrade worked great thanks to the bump in release number 15.1 -> 16.1.  Thanks!

**Comment by koomie** [comment]
Test environment for 1.2.1 was updated to use PXSE 2017 Update 1 and CI tests are passing.
