### ISSUE TITLE
Intel MPI module file is not created by intel-mpi-devel-ohpc

### ISSUE THREAD

**Issue by LaHaine** [openhpc/ohpc#347]
This is with ohpc 1.2 on SL7.2. It is basically the same issue as #254, the postinstall script of intel-mpi-devel-ohpc-2017-15.1.x86_64 doesn't work if I replace the intel-mpi-doc package with a wrapper package containing a symbolic link to the Intel MPI installation on a shared file system. The solution is to add a -L to the find command here as well.

**Comment by koomie** [comment]
Merged in via #349
