### ISSUE TITLE
compute node interfaces always come up as eth0

### ISSUE THREAD

**Issue by nirmalasrjn** [openhpc/ohpc#354]
Irrespective of what I specify in --netdev option in the wwnodescan command, the compute node interfaces are named as eth0 only. The wwsh node print command shows the interface as whatever we specify, be it em1 or eno1. (eno1.HWADDR, eno1.IPADDR etc). However when the node boots up, the message, "Checking for network device: en01 Skipped , Checking for network device: eth0 OK" is displayed.

**Comment by jmstover** [comment]
Hi Nirmala,

  Check the KARGS value (wwsh provision print [node]) and see if it
contains: net.ifnames=0 biosdevname=0

  Those options disable the biosdevname naming of the interface. If, for
some reason it can't reach the given network device it tries eth0-3.

-J

**Comment by nirmalasrjn** [comment]
Thanks for the prompt reply. Yes those arguments are available. While building the node image, I enabled the kernel options in the input file and put in the arguments as "net.ifnames=0 biosdevname=0".  The kargs show up. Even then I face this issue.  (c1: KARGS            = "net.ifnames=0 biosdevname=0"). When I use the wwnodescan command to add nodes, the kargs is "quiet" only.

**Comment by jmstover** [comment]
Hi Nirmala,

  We force the disabling of biosdevnames in the Warewulf code if kargs is
the default. If you're wanting to use it, then you can do a:

      wwsh provision set node00[00-09] --kargs="quiet"

  That should be enough to do it...

-J

**Comment by nirmalasrjn** [comment]
Hi Jason,
Setting kargs=quiet does not resolve this.
cat /proc/cmdline
BOOT_IMAGE=bootstrap/5/kernel ro initrd=bootstrap/5/initfs.gz wwhostname=c4 quiet wwmaster=172.36.0.1 wwipaddr=172.36.1.4 wwnetmask=255.255.0.0 wwnetdev=em1
The init script in warewulf bootstrap image looks for device name given in the netdev option but finds only eth0 in the configuration file. Is it because of hard coding of the interface name? Because I find the following line in   /var/log/provision/config.log,   "cp /tmp/ifcfg-eth0 /newroot/etc/sysconfig/network-scripts/ ".
Thank you

**Comment by QuackDoctor** [comment]
Hi Nirmala,
Did you get to resolve this issue? 
Are these systems Broadwell based?
Thanks,

**Comment by koomie** [comment]
With the 3.7pre version of WW that is planned to be used for the 1.3 release of OpenHPC, it is possible to use the newer naming scheme. Will plan on adding a tooltip for this.

**Comment by koomie** [comment]
The additional steps necessary have been added to the docs as follows when `${eth_provision}` is defined with the newer name (e.g. en4s0f0):

```
[sms]# wwsh provision set "${compute_regex}" --kargs "net.ifnames=1,biosdevname=1" 
[sms]# wwsh provision set --postnetdown=1 "${compute_regex}"
```
