### ISSUE TITLE
Provisioning using warewulf fails when boot mode is UEFI

### ISSUE THREAD

**Issue by nirmalasrjn** [openhpc/ohpc#365]
Provisioning using warewulf is successful only boot mode is set to BIOS

**Comment by jmstover** [comment]
Hi Nirmala,

  WW uses Syslinux 6.0{2,3} which have UEFI issues. You'd want to build at
least 6.04, though I think that may have some issues as well. I believe the
file you would want is syslinux.efi. You would want to replace all
references to lpxelinux.0 in /etc/warewulf/dhcpd-template.conf to that
file, and place your built file at:  /var/lib/tftpboot/warewulf/  (default
location)

  Remove the system dhcpd.conf file, and run:

    # wwsh dhcp update

  The new dhcpd.conf should be built off the dhcpd-template.conf file, so
have the syslinux.efi file being sent out.

  Try booting a UEFI node again. I have never ran in UEFI mode, so this is
mostly guess work on my part.

-J

**Comment by crbaird** [comment]
Addressed in OpenHPC 1.3 by moving to warewulf 3.7-pre. Passing in CI.
