### ISSUE TITLE
warewulf-provision-ohpc package for AArch64 exports /usr/share/warewulf/ldlinux.c32 which is 32-bit x86 binary

### ISSUE THREAD

**Issue by pawosm-arm** [openhpc/ohpc#370]
```
# file /usr/share/warewulf/ldlinux.c32
/usr/share/warewulf/ldlinux.c32: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped

# rpm -q --whatprovides /usr/share/warewulf/ldlinux.c32
warewulf-provision-ohpc-3.6-32.1.aarch64
```

**Comment by pawosm-arm** [comment]
Correction: with newer version of this package, the number of such files increased, /usr/share/warewulf installs:
ldlinux.c32: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped
ldlinux.e32: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped
ldlinux.e64: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped

**Comment by koomie** [comment]
@crbaird, what do you think about adding an %if test for x86 to include these binaries?

**Comment by crbaird** [comment]
The expected workaround is to leverage newer devel WW which will support iPXE to enable aarch64 support.
