### ISSUE TITLE
interim warewulf update

### ISSUE THREAD

**Issue by crbaird** [openhpc/ohpc#372]
Update warewulf based on fork of the warewulf3 github repository. This involves a release of a fork of that repository, and modification of spec files to point to that release. Since NHC is now distributed outside of warewulf, that package will be removed from this release.

**Comment by jmstover** [comment]
@crbaird The Github master branch is effectively 3.7. There's a few minor additions wanted, once time allows. :/  One day it will be released... one day.

**Comment by crbaird** [comment]
No sweat, @jmstover. Our 3.6 base is just showing enough of its teeth that we wanted to get a jump on something 3.7-like. Should you choose to make the release out of the github repo we'll be ready.

**Comment by crbaird** [comment]
tests passing in CI
