### ISSUE TITLE
Permission denied when using Nagios

### ISSUE THREAD

**Issue by pedrothome** [openhpc/ohpc#425]
I just installed nagios from Open HPC 1.3 and when access I got the error:
`You don't have permission to access /nagios/cgi-bin//tac.cgi on this server.`

After some research I noticed that in the /etc/httpd/conf.d/nagios.conf there is a tag not being replaced with the cgi-bin folder - @cgidir@

I was able to find that the nagios-0008-Fix-path-to-CGI-executables.patch should do that, but could not find where this path is being applied. 

Patch being applied on SPEC file
![image](https://cloud.githubusercontent.com/assets/5927445/24878049/e9369226-1e07-11e7-9976-43b5adb048f2.png)

@cgidir@ reference
![image](https://cloud.githubusercontent.com/assets/5927445/24878075/077cf5f4-1e08-11e7-97d9-0edb687edd07.png)

**Comment by crbaird** [comment]
Thanks for the report, @pedrothome.

**Comment by crbaird** [comment]
ref 1e1ff8fc
