### ISSUE TITLE
Resurrect optional slurm integration for pdsh

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#435]
From the mailing list:

Users would like to have a capability to choose a pdsh build that includes SLURM integration options when using SLURM as the chose resource manager.  At the moment, we have an agnostic pdsh build. Potential options for consideration are:

1. support multiple builds, e.g. introduce a pdsh-slurm-ohpc variant
2. split out the slurm-specific stuff into an optional add-on package

**Comment by crbaird** [comment]
Optional mod-slurm package built, and new tests passing in CI
