### ISSUE TITLE
sigar (v1.6.5)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#44]
available from: http://linux-ftp.jf.intel.com/pub/mirrors/fedora/linux/releases/21/Everything/source/SRPMS/s/

last official stable release (v1.6.4) available  at: https://support.hyperic.com/display/SIGAR/Home;jsessionid=CC27373A50A6C0AEEC5C6CD9CD2937C1#Home-download

**Comment by koomie** [comment]
deprecated.
