### ISSUE TITLE
Lmod rpm does not conflict to Suse's environment module

### ISSUE THREAD

**Issue by pliniosilveira** [openhpc/ohpc#440]
The Environment Modules package is named environment-modules in Red Hat family and is named Modules in Suse family.

The spec only references the Red Hat name of the package.
https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3_Factory/components/admin/lmod/SPECS/lmod.spec#L50

Possible fix in PR #439

**Comment by koomie** [comment]
Thanks a bunch for this suggestion. I've landed PR #439 onto the 1.3.1 branch so it should be enabled for the next release.
