### ISSUE TITLE
Unresolvable dependency on /bin/perl

### ISSUE THREAD

**Issue by moschny** [openhpc/ohpc#451]
On a fresh CentOS 7.3.1611 (the Docker image) installed `ohpc-release-1.3-1.el7.x86_64`.

Now, trying to install `mpich-gnu-ohpc` fails with:
```
Error: Package: mpich-gnu-ohpc-3.2-5.3.x86_64 (OpenHPC)
           Requires: /bin/perl
```
The dependency on `/bin/perl` can not be resolved, it should instead be on `/usr/bin/perl`, or simply on `perl`.

Installation succeeds if perl is installed directly via yum beforehand.

**Comment by moschny** [comment]
See also #322 for a similar issue with `/bin/python` vs `/usr/bin/python`.

**Comment by koomie** [comment]
Just digging a bit more, this dependency is introduced via the `parkill` utility that is installed in the `bin/` dir. I'm not sure if anyone really uses this utility, but let's call out the perl dependency directly.  Note that perl on CentOS supplies both /bin/perl and /usr/bin/perl.

**Comment by moschny** [comment]
> Note that perl on CentOS supplies both /bin/perl and /usr/bin/perl.

Not really, it provides `/usr/bin/perl`. The symlink `/bin` -> `/usr/bin` then makes it accessible via `/usr/bin/perl`. 

See also https://fedoraproject.org/wiki/Features/UsrMove.

**Comment by koomie** [comment]
Doh, that's what I get for blindly running `rpm -qf /bin/perl`. Thanks for the clarification. I've added the perl dependency directly which should allow for resolution via the package manager.

**Comment by koomie** [comment]
Just an update here, that I spent some time digging into this and it's, unfortunately, more complicated than I realized and related to the underlying OBS build system. After much debugging, the issue is that OBS is spawning builds with `su - ` and it is the `su` command that is pulling in `/bin` that the rpmbuild scan process is picking up.  

I need to spend some more time with this one to try and devise a fix that is not icky, so pushing to next milestone.

**Comment by koomie** [comment]
Patch to avoid this path issue introduced by `su -` is in place on ohpc public build server.  Submitted for upstream consideration to obs in: https://github.com/openSUSE/obs-build/pull/380.

With this in place, the latest mpich builds no longer detect the symlinked path, but see `/usr/bin` instead:

```
[  464s] Requires: /usr/bin/bash /usr/bin/perl
```
