### ISSUE TITLE
Missing dependency on glibc-devel

### ISSUE THREAD

**Issue by moschny** [openhpc/ohpc#452]
The `gnu-compilers-ohpc-5.4.0-13.1.x86_64` package misses a dependency on `glibc-devel` (which in turn brings in `glibc-headers` and `kernel-headers`.)

Otherwise, even compiling a simple `helloworld.c` fails with
```
helloworld.c:1:19: fatal error: stdio.h: No such file or directory
compilation terminated.
```

CentOS 7.3.1611, ohpc-release-1.3-1.el7.x86_64

**Comment by koomie** [comment]
I forgot to add it flag this as being in the v1.3.1 milestone but it was included in the last release in June.
