### ISSUE TITLE
Dependency problem on petsc

### ISSUE THREAD

**Issue by takekato** [openhpc/ohpc#474]
Hello, 

I found a dependency problem on petsc while I tried to make the SLEPc package(issue #465) with  OpenHPC_1.3_Update1_Factory.
I got the message "have choice for libhdf5.so.10()(64bit) needed by petsc-gnu-openmpi-ohpc: hdf5-gnu-ohpc phdf5-gnu-mpich-ohpc phdf5-gnu-mvapich2-ohpc phdf5-gnu-openmpi-ohpc".

It seems to be a dependency problem in petsc.
Petsc package is needed by SLEPc. So I need the fix for this issue.

Does anyone handle this issue now?

The build result of slepc package: 
https://build.openhpc.community/package/show/home:xtcohpc:OHPCARM/slepc

**Comment by takekato** [comment]
Hello, 

As far as I see, nobody handle this issue now.
If OpenHPC_1.3_Update1_Factory has been obsoleted, I'll change my settings.
Let me know what I should do for next release?

**Comment by crbaird** [comment]
Hi,
The issue in petsc was resolved (#436) in OpenHPC_1.3_Update1_Factory, but all builds in that update also changed the default gnu compiler family to gnu7. So by depending on petsc-gnu-openmpi-ohpc in slepc, you are actually getting the one from the 1.3 base repo, not the 1.3.1 updates repo. If you instead depend on petsc-gnu7-openmpi-ohpc, you should get the correct version which hopefully solves the problem. I imported and updated your slepc spec file in to the current working project ([slepc-gnu-openmpi](https://build.openhpc.community/package/show/OpenHPC:1.3:Update2:Factory/slepc-gnu-openmpi)) and all versions of the package are building successfully.

**Comment by takekato** [comment]
Thank you for your comment.
I'll try to fix my slepc package.
