### ISSUE TITLE
enable dhcpd service which is disabled by default

### ISSUE THREAD

**Issue by linuxstudio** [openhpc/ohpc#492]
both the CentOS and SLES recipes are missing a couple of steps in docs/recipes/install/common/
warewulf_setup_centos.tex
warewulf_setup_sles.tex

namely:

systemctl enable dhcpd.service
systemctl restart dhcpd

**Comment by koomie** [comment]
Thanks for these additions - they have been landed on the 1.3.2 branch, although I removed the service restart as it will be done further along in the recipe by Warewulf during the node registration process.
