### ISSUE TITLE
lmod (7.6.1)

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#495]
https://github.com/TACC/Lmod/releases

This should allow access to new functionality that can be used to define dependencies amongst modules.

**Comment by fgeorgatos** [comment]
7.6!
-- 
echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by koomie** [comment]
Looks like the  `depends_on()` functionality was not extended to tcl files. Issued a PR upstream to enable so we can use in ohpc (https://github.com/TACC/Lmod/pull/303).

**Comment by koomie** [comment]
v7.6.1 is out that should have the tcl fix to support `depends_on`.

**Comment by koomie** [comment]
CI tests passing.
