### ISSUE TITLE
IMPI version test is incorrect for 2016

### ISSUE THREAD

**Issue by chuckatkins** [openhpc/ohpc#533]
intel-mpi-devel-ohpc uses `2016.0` as the minimum supported version, but the impi packages shipped with the 2016 compiler use a different version scheme and are `5.1.x` and `5.3.x`.  This results in failure to install the ohpc impi package when the 2016 compiler and mpi are present.

**Comment by chuckatkins** [comment]
@koomie looks like a bug in the new version tests.  Fixed in #532

**Comment by koomie** [comment]
@chuckatkins, thanks for the fix (and improvement to potentially skip over unsupported versions). This has been landed on 1.3.2 branch.
