### ISSUE TITLE
shine is failing for all remote commands

### ISSUE THREAD

**Issue by LaHaine** [openhpc/ohpc#541]
This is with the recently updated shine-ohpc-1.5-36.1.noarch on EL7.3. All shine commands running on remote hosts fail with an error like this:
````
atmds4: Remote action status failed: Traceback (most recent call last):
  File "/opt/ohpc/pub/libs/shine/1.5/sbin/shine", line 32, in <module>
    from Shine.Controller import Controller
ImportError: No module named Shine.Controller
````
This is caused by the missing PYTHONPATH environment variable on the remote host. It is set by the shine module, but it is not set through ssh/clustershell on the remote machine.

**Comment by LaHaine** [comment]
This isn't resolved yet. I propose to not install shine in /opt/ohpc and put it in /usr/bin. @crbaird : This package isn't supposed to be relocatable, isn't it?

**Comment by adrianreber** [comment]
Closing as shine is no longer distributed on 2.x and 3.x.
