### ISSUE TITLE
python-Cython has no -ohpc suffix

### ISSUE THREAD

**Issue by adrianreber** [openhpc/ohpc#560]
The python-Cython package is odd as it does not have the -ohpc suffix and it is not clear to me why.

A few packages in components/distro-packages have the suffix, some do not.

There are also other packages like slurm which are using /usr as a prefix but still have the -ohpc suffix.

Would it make sense to add the suffix to this package, or not?

**Comment by crbaird** [comment]
Thanks for catching this, @adrianreber. The python-Cython package is intended to be a build-only requirement for scipy (the CentOS-provided version is too old). The intention was to have OBS build cython and use this version for subsequent builds, but it seems to have sneaked in to the published repository.

**Comment by koomie** [comment]
Even though this is intended to only solve a build dependency, an end-user would need the package to reproduce the build for scipy. Talked with @crbaird and agreed it should get updated to include the suffix.  Planning for update in 1.3.3.

**Comment by adrianreber** [comment]
We do not need to set PROJ_DELI in each spec file. It is set by OHPC_macros already. This reference the latest commit https://github.com/openhpc/ohpc/commit/a8eba37ac5a4dee67007aaddc34d0f3a9941453f

I also submitted a PR with these changes #568 which includes more fixes like adding OHPC_macros to SourceX. The PR does unfortunately not apply anymore as some of the changes have been duplicated.

**Comment by crbaird** [comment]
Correctly built in 1.3:Update3:Factory
