### ISSUE TITLE
wrong MANPATH set in MPI modules

### ISSUE THREAD

**Issue by LaHaine** [openhpc/ohpc#561]
Both the openmpi and mvapich2 modules expand MANPATH to the wrong directories. For openmpi, it ise set to/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/man, but the man pages are in /opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/share/man. Same for mvapich2, it is set to /opt/ohpc/pub/mpi/mvapich2-gnu/2.2/man, but the man pages are in /opt/ohpc/pub/mpi/mvapich2-gnu/2.2/share/man. This is with openhpc 1.3 on EL7.

**Comment by koomie** [comment]
Thanks for the report - we'll get `MANPATH` updated.

**Comment by koomie** [comment]
Note: additional test for manpath added to test-suite for MPI stacks.

**Comment by koomie** [comment]
Tests now passing in CI.
