### ISSUE TITLE
libtool-ohpc should not list its provided so names

### ISSUE THREAD

**Issue by adrianreber** [openhpc/ohpc#562]
I can no longer build adios as it BuildRequires: libtool%{PROJ_DELIM}. This leads to the installation of libtool-ohpc which satisfies the dependency of openmpi -> hwloc-libs. The latest mpicc needs libltdl.so.7 which is provided by libtool-ohpc, but which can not be found as it is not in the library search path.

I would recommend to disable auto requires and provides for libtool-ohpc. I can provide a patch.

Looking closer at it, it is not clear why OpenHPC provides libtool at all. According to grep libtool-ohpc is only required by adios and on CentOS 7.4 adios builds with the system provided libtool, autoconf and automake.

**Comment by koomie** [comment]
The autotools packages (autoconf, automake, libtool) are provided to allow for new versions to be available in the ohpc dev environment via modules.  Let me look into this in the obs builds....

**Comment by adrianreber** [comment]
The same problem happened now with slurm.

I am installing slurm-ohpc on a system which has libtool-ohpc already installed. This means that the libltdl.so.7 dependency is fulfilled by libtool-ohpc but libltdl.so.7 cannot be found and the actual libltdl.so.7 is not pulled in by yum.

**Comment by koomie** [comment]
I added a `__provides_exclude` for the .so and the latest OBS build no longer reports it as a `Provides`:

https://build.openhpc.community/package/binary/OpenHPC:1.3:Update3:Factory/libtool?arch=x86_64&filename=libtool-ohpc-2.4.6-20.1.x86_64.rpm&repository=CentOS_7

Groovy?
