### ISSUE TITLE
pmix depends on a meta package

### ISSUE THREAD

**Issue by adrianreber** [openhpc/ohpc#579]
pmix is the first package that depends on a meta-package:

BuildRequires: lmod-ohpc ohpc-autotools

I do not think we should introduce circular dependencies like that. meta-packages are depending on all other packages and some of those packages are now (pmix) depending on some meta-packages.

That makes bootstrapping more difficult. libtool-ohpc already requires autoconf-ohpc and automake-ohpc, so a simple dependency in pmix on libtool-ohpc should have the same effect.

I have patch ready and can open a PR if there is interest.

**Comment by koomie** [comment]
This works fine in OBS, but can change this to not call out a meta-pacakge. I went with your suggestion of `libtool-ohpc` instead.  This should all go away with future pmix release as the patch necessitating an `autoreconf` is upstreamed...
