### ISSUE TITLE
Additional test programs for plasma, scotch, ptscotch.

### ISSUE THREAD

**Issue by ghost** [openhpc/ohpc#585]
HI,

My colleagues and I added some test programs for plasma, scotch, ptscotch into tests/libs to improve ohpc test to evaluate basic functions and performance. These test programs are contained in source archives.
Would you please review them?

https://github.com/takekato/ohpc/tree/plasma-test
https://github.com/takekato/ohpc/tree/scotch-test
https://github.com/takekato/ohpc/tree/ptscotch-test

As far as we know, it can not invoke test_module and rm_execution make targets properly.
We could not figure out what we should do before invoke these targets.
Apparently, PATH environment variable was not set properly.
We got "./common/bats/bin/bats: line 200: exec: bats-exec-test: not found".
What is needed to invoke them properly? 
– Plsama
FAIL: test_module
FAIL: rm_execution
– SlepC
FAIL: test_module
FAIL: rm_execution
–

**Comment by crbaird** [comment]
Hi @takekato. I checked out your plasma-test branch on our test cluster, and I was able to run all your tests succesfully. The steps I took:
```
~/ohpc> cd tests
~/ohpc/tests> ./bootstrap; ./configure      # this sets up the common/TEST_ENV variables
~/ohpc/tests/libs/plasma> cd libs/plasma
~/ohpc/tests/libs/plasma> module load plasma
~/ohpc/tests/libs/plasma> ./bootstrap; ./configure
~/ohpc/tests/libs/plasma> make check
```
and among the output is:
```
PASS: test_module
PASS: rm_execution
PASS: ohpc-plasma-kick-ctest.sh
============================================================================
Testsuite summary for plasma 2.8.0
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
I will say that your additional tests are quite extensive. In OpenHPC we start from the assumption that a particular software package already performs correctly, and our own test suite is checking integration and functionality through the resource manager.

**Comment by takeharukato** [comment]
> I will say that your additional tests are quite extensive. In OpenHPC we start from the assumption that
>  a particular software package already performs correctly, and our own test suite is checking
>  integration  and functionality through the resource manager.
Sure.
From CI test point of view, these tests are extensive certainly.
But they are needed for regression test for me.
So I'll consider that we introduce special make-target for these tests not to prevent CI tests.

**Comment by adrianreber** [comment]
Reporters account has been deleted. Closing as we cannot see the proposed changed any more.
