### ISSUE TITLE
 intel-compilers-devel-ohpc path causing integration issues with Bright Cluster Manager

### ISSUE THREAD

**Issue by metzenw** [openhpc/ohpc#586]
Bright installs the Intel Parallel Studio under the following path and it causes an issue with " intel-compilers-devel-ohpc"

```
[root@bright80]# rpm -qal | grep "intel64/icc"
/cm/shared/apps/intel/compilers_and_libraries/2017.2.174/bin/intel64/icc
/cm/shared/apps/intel/compilers_and_libraries/2017.2.174/bin/intel64/icc.cfg
/cm/shared/apps/intel/compilers_and_libraries/2017.2.174/bin/intel64/icc_libFNP.so
```

In the  intel-compilers-devel-ohpc path, there is a check for "linux/bin/intel64/icc", wich does not resolve since Bright packages it as "2017.2.174/bin/intel64/icc"
`
rpm -qal | grep "linux/bin/intel64/icc"
`
The request here is to remove the "linux" path in this check.

**Comment by koomie** [comment]
Can I see what package owns the paths you provided? something like
```
rpm -qf /cm/shared/apps/intel/compilers_and_libraries/2017.2.174/bin/intel64/icc
```

**Comment by metzenw** [comment]
rpm -qf /cm/shared/apps/intel/compilers_and_libraries/2017.2.174/bin/intel64/icc
intel-cc-2017-17.0.2-53_cm8.0.x86_64

**Comment by koomie** [comment]
So, it seems they are repackaging and providing their own path layout. I'd say this falls outside intended support, and while I wouldn't mind tweaking the rpm query to remove `linux` from the leading path, I don't think that will be sufficient to make this work. In particular, we are leveraging the compilervars.sh script to create a modulefile dynamically, and again that is expected to reside in a `.../linux/bin/compilervars.sh` path.  Perhaps a fix on your side would be to create a soft link for the linux directory so the ohpc compatibility can resolve the expected path?
