### ISSUE TITLE
test-suite (v1.0)

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#63]

**Comment by koomie** [comment]
The use of the `test-suite-ohpc` rpm has been up and running in CI for a while. Last bit needed here to close this out is to add some information on it's installation and usage in the docs.

**Comment by koomie** [comment]
Discussion on existence and installation of the test suite has been added to the docs.  Closing this out.

**Comment by boegel** [comment]
pointer?

**Comment by koomie** [comment]
It will be in Appendix B in the recipes for the forthcoming v1.3 release.  If you are looking for advanced copies of it (or the RPM) you could grab from the current Factory repo: 

http://build.openhpc.community/OpenHPC:/1.3:/Factory/CentOS_7/

If I missed the mark on your question, let me know.
