### ISSUE TITLE
EPEL repo is required in the chroot for nagios plugins, fping and qstat

### ISSUE THREAD

**Issue by aeszter** [openhpc/ohpc#651]
`# yum --installroot=/install/netboot/centos7.4/x86_64/compute/rootimg/ install nagios-plugins-all-ohpc nrpe-ohpc`

...

`--> Finished Dependency Resolution`
`Error: Package: nagios-plugins-game-ohpc-2.2.1-24.2.x86_64 (OpenHPC-updates)`
`           Requires: qstat`
`Error: Package: nagios-plugins-fping-ohpc-2.2.1-24.2.x86_64 (OpenHPC-updates)`
`           Requires: /usr/sbin/fping`

Fixed by #641

**Comment by koomie** [comment]
Landed #641 on 1.3.4 branch to update xCAT recipe.
