### ISSUE TITLE
python-numpy.spec broken

### ISSUE THREAD

**Issue by adrianreber** [openhpc/ohpc#662]
The following two entries in the python-numpy.spec break building for me:

error: line 50: Unknown tag: %python_subpackages

Line 50: %python_subpackages

Line 158: %files %{python_files}

It seems like @crbaird added those lines.

**Comment by adrianreber** [comment]
I guess the idea was that python-rpm-macros is installed in the buildroot when building the SRPM.

This breaks building OpenHPC source packages on a non OpenHPC system. Until this change was introduced I could build OpenHPC packages anywhere without any pre-requirements. With this change it is no longer possible and I hope this can be reverted.

The python-rpm-macros packages also does not use a URL for the Source so that it is hard to tell where to find the tarball.

Can this please be reverted, so that we can still build OpenHPC packages without any requirements on the build system.

**Comment by crbaird** [comment]
This work in progress is intended to allow a single spec file to build both python2 and python3 packages. It would require the python-rpm-macros-ohpc package for build, but does that really make it dependent on a build system?

**Comment by adrianreber** [comment]
Up until know there were no requirements on the system where the SRPM is build. With this change this changes (this is a great sentence by the way). If we are going down this route, which I really hope we do not, this could mean that we could install OHPC_macros also in a package and copy it to macros.d (or similar) and do not need to include it in every file manually.

But again, all of sudden we have a dependency on the SRPM build system, which breaks my repository workflow completely, and as I as using community buildsystems (COPR and centos build system) I can no. longer build the packages (right python-numpy and dependencies).

I am also using Fedora to build the SRPMs where I cannot install OpenHPC packages and actually I do not want to.
