### ISSUE TITLE
mfem (v3.3.2)

### ISSUE THREAD

**Issue by crbaird** [openhpc/ohpc#665]
https://github.com/mfem/mfem/releases

**Comment by koomie** [comment]
Initial MFEM packaging complete. Installation present in CI recipes and related tests added to ohpc test suite are running successfully (thanks @sidio47 for the test additions).  Example CI run:

http://test.openhpc.community:8080/job/1.3.x/job/(1.3.4)%20-%20(centos7.4,x86_64)%20(warewulf+slurm)%20(fabric=ib)%20+%20psxe/87/testReport/UserLevelTests/Mfem/
