### ISSUE TITLE
EasyBuild (v2.3.0)

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#67]
Available at: https://github.com/hpcugent/easybuild

**Comment by boegel** [comment]
I'm the EasyBuild lead dev & release manager, and I'm very happy that EasyBuild is a part of the OpenHPC stack, but I had no idea this happened...

Is there anything we can do to make integration easier/better in future releases?

Is there a guide we can use to update the EasyBuild version included in the OpenHPC stack when we have a new release?

I'd be happy to contribute to this in any way I can.

**Comment by JohnWestlund** [comment]
@boegel 

Great!

If you take a look at the OHPC spec file for EasyBuild you can see some of the things we've done to integrate EasyBuild:

From the module file we generate:
```
set             version                 %{version}
set             home                    \$::env(HOME)

prepend-path    PATH                    %{install_path}/software/EasyBuild/%{version}/bin
prepend-path    PATH                    ${LMOD_DIR}
prepend-path    LD_LIBRARY_PATH         %{install_path}/software/EasyBuild/%{version}/lib
prepend-path    LIBRARY_PATH            %{install_path}/software/EasyBuild/%{version}/lib
module          use                     \$home/.local/easybuild/modules/all

setenv          EBROOTEASYBUILD         %{install_path}/software/EasyBuild/%{version}
setenv          EBVERSIONEASYBUILD      %{version}
setenv          EASYBUILD_MODULES_TOOL  Lmod
```

With your deeper background with EasyBuild perhaps you see something that we can do or take advantage of to improve the current setup.

We do have one patch we're applying to a SLES kernel, but that's a very minor issue. @crbaird may have more specific suggestions.

**Comment by koomie** [comment]
Hi @boegel. I also just wanted to say thanks for the interest in helping with EasyBuild. Definitely appreciate it  - sorry we could not sync up sooner. One thing I wanted to throw out as a potential longer term idea is perhaps figuring out a way to let EasyBuild know about dependencies that might be installed as part of an OpenHPC install.  Thus far, we went for a pretty simple integration which was to build EasyBuild and provide a module for it so users could do ```module load EasyBuild``` and then use as normal.  However, as I understand it, EasyBuild typically manages all of it's own dependencies so it's conceivable a users might be pulling down a dependency that might also be installed locally as part of OpenHPC.  That was one area we were thinking might be interesting to look into more.

Cheers.

-k

**Comment by boegel** [comment]
@JohnWestlund: some of these things in the module don't make a lot of sense; EasyBuild is all Python code, so defining `$LD_LIBRARY_PATH` or `$LIBRARY_PATH` is actually useless (although EB does it by itself for the EasyBuild module)

the `module use` that you add points to the default install location of EasyBuild, which is probably not what you want (`$HOME/.local/easybuild` is a weird default, but it honors the `$XDG*` 'standard')

you probably want to define `$EASYBUILD_PREFIX` (see http://easybuild.readthedocs.org/en/latest/Configuration.html#prefix), and then tweak the `module use` to that

@koomie: to let EasyBuild know of the modules that come as a part of the stack (compilers/MPI), you can include a metadata file for what we refer to as "external modules", see http://easybuild.readthedocs.org/en/latest/Using_external_modules.html

I'll try and look into an update of the EasyBuild `.spec` to EasyBuild v2.4.0.

**Comment by JohnWestlund** [comment]
@boegel I've been making some of these changes to my fork.

Is there a best practice or personal preference for what the `$EASYBUILD_PREFIX` should be set to? I switched it to `\$home/eb` just to be more obvious where the builds were. I could see setting up a `root` version of the module to put the installs in a more global location -- perhaps mimicking the OHPC layout a bit for our purposes.

The example on [Dependencies](http://easybuild.readthedocs.org/en/latest/Writing_easyconfig_files.html#dependency-specs) seems broken: `builddependencies = [('CMake', '2.8.12', '', ('GCC', '4.8.2')]` Missing a close paren at least?

But in terms of @koomie 's question -- it looks like what we want to do is to have each OHPC package that provides a dependency to install something like:
```
cat <<_HERE_
[%{PNAME}/%{version}]
name    = %{PNAME}
version = %{version}
prefix  = \$%{PNAME}_DIR
_HERE_ > /etc/easybuild.d/%{PNAME}-%{VERSION}.cfg
```

But each easyconfig would still need to be modified to look for these external dependencies? Or is it possible to simply have these packages publicize what dependencies they satisfy to EB?

My `prefix` line uses `\$%{...}` with the assumption that in the example for: [Metadata for external modules](http://easybuild.readthedocs.org/en/latest/Using_external_modules.html#metadata-for-external-modules)
```
[cray-netcdf/4.3.2]
name = netCDF, netCDF-Fortran
version = 4.3.2, 4.3.2
prefix = NETCDF_DIR
```
`NET_DIR` should be `$NET_DIR`

**Comment by boegel** [comment]
@JohnWestlund urgh, I just noticed this never got answered, my apologies...

Let me know if something here still isn't clear...
