### ISSUE TITLE
File conflict when installing slurm on SUSE 12.3

### ISSUE THREAD

**Issue by mrmhodak** [openhpc/ohpc#689]
Following the instructions (using local repository, BTW), I hit file conflict when installing slurm on SUSE 12.3:

zypper -n install ohpc-slurm-server
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 18 NEW packages are going to be installed:
  hwloc hwloc-data libhwloc5 libmysqlclient18 munge-devel-ohpc munge-libs-ohpc munge-ohpc ohpc-filesystem ohpc-slurm-server pdsh-mod-slurm-ohpc pmix-ohpc slurm-devel-ohpc slurm-munge-ohpc slurm-ohpc
  slurm-perlapi-ohpc slurm-plugins-ohpc slurm-slurmdbd-ohpc slurm-sql-ohpc

The following 17 packages are not supported by their vendor:
  hwloc hwloc-data libhwloc5 munge-devel-ohpc munge-libs-ohpc munge-ohpc ohpc-filesystem ohpc-slurm-server pdsh-mod-slurm-ohpc pmix-ohpc slurm-devel-ohpc slurm-munge-ohpc slurm-ohpc slurm-perlapi-ohpc
  slurm-plugins-ohpc slurm-slurmdbd-ohpc slurm-sql-ohpc

18 new packages to install.
Overall download size: 0 B. Already cached: 30.1 MiB. After the operation, additional 110.7 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
In cache ohpc-filesystem-1.3-21.1.noarch.rpm                                                                                                                                 (1/18),   3.6 KiB (    0   B unpacked)
In cache hwloc-data-1.11.4-10.1.x86_64.rpm                                                                                                                                   (2/18),   5.1 KiB (  5.3 KiB unpacked)
In cache pmix-ohpc-1.2.3-20.1.x86_64.rpm                                                                                                                                     (3/18), 172.8 KiB (  1.3 MiB unpacked)
In cache munge-libs-ohpc-0.5.12-24.1.x86_64.rpm                                                                                                                              (4/18),  18.6 KiB ( 45.6 KiB unpacked)
In cache libhwloc5-1.11.4-10.1.x86_64.rpm                                                                                                                                    (5/18), 107.7 KiB (285.9 KiB unpacked)
In cache munge-ohpc-0.5.12-24.1.x86_64.rpm                                                                                                                                   (6/18), 105.8 KiB (324.4 KiB unpacked)
In cache hwloc-1.11.4-10.1.x86_64.rpm                                                                                                                                        (7/18), 118.1 KiB (414.0 KiB unpacked)
In cache slurm-plugins-ohpc-17.02.9-69.1.x86_64.rpm                                                                                                                          (8/18),   1.0 MiB (  4.7 MiB unpacked)
In cache munge-devel-ohpc-0.5.12-24.1.x86_64.rpm                                                                                                                             (9/18),  33.1 KiB ( 90.7 KiB unpacked)
In cache slurm-ohpc-17.02.9-69.1.x86_64.rpm                                                                                                                                 (10/18),  26.1 MiB ( 92.6 MiB unpacked)
In cache slurm-perlapi-ohpc-17.02.9-69.1.x86_64.rpm                                                                                                                         (11/18), 497.3 KiB (  2.3 MiB unpacked)
In cache slurm-munge-ohpc-17.02.9-69.1.x86_64.rpm                                                                                                                           (12/18),  16.2 KiB ( 46.3 KiB unpacked)
In cache slurm-devel-ohpc-17.02.9-69.1.x86_64.rpm                                                                                                                           (13/18), 134.2 KiB (398.7 KiB unpacked)
In cache pdsh-mod-slurm-ohpc-2.33-43.1.x86_64.rpm                                                                                                                           (14/18),   7.4 KiB ( 14.5 KiB unpacked)
In cache libmysqlclient18-10.0.30-28.1.x86_64.rpm                                                                                                                           (15/18), 564.6 KiB (  3.3 MiB unpacked)
In cache slurm-sql-ohpc-17.02.9-69.1.x86_64.rpm                                                                                                                             (16/18), 267.7 KiB (  1.0 MiB unpacked)
In cache slurm-slurmdbd-ohpc-17.02.9-69.1.x86_64.rpm                                                                                                                        (17/18), 998.8 KiB (  3.8 MiB unpacked)
In cache ohpc-slurm-server-1.3.3-9.1.x86_64.rpm                                                                                                                             (18/18),   2.6 KiB (    0   B unpacked)
Checking for file conflicts: ...............................................................................................................................................................................[error]
Detected 1 file conflict:

File /usr/lib/systemd/system/slurmdbd.service
  from install of
     slurm-ohpc-17.02.9-69.1.x86_64 (Lenovo-OpenHPC-1.3 - Base)
  conflicts with file from install of
     slurm-slurmdbd-ohpc-17.02.9-69.1.x86_64 (Lenovo-OpenHPC-1.3 - Base)

File conflicts happen when two packages attempt to install files with the same name but different contents. If you continue, conflicting files will be replaced losing the previous content.
Continue? [yes/no] (no): no

Problem occurred during or after installation or removal of packages:
Installation aborted by user

**Comment by adrianreber** [comment]
This seems to have been fixed in newer slurm releases with this commit:

https://github.com/openhpc/ohpc/commit/9895b05440d39695987f6e2359026401dcb2f628#diff-9aded14f522024d22503dd45fb48e9f2
