### ISSUE TITLE
Please enable the slurm Lua job submit plugin

### ISSUE THREAD

**Issue by jabl** [openhpc/ohpc#697]
Slurm provides a job_submit_lua.so plugin, which is pretty useful. Could it be enabled for the openhpc slurm rpm's?

See https://slurm.schedmd.com/job_submit_plugins.html

**Comment by koomie** [comment]
Seems reasonable. Will look to enable that plugin for next release.

**Comment by koomie** [comment]
@jabl, we've done a rebuild to enable lua bindings such that the `slurm-ohpc` packaging includes `/usr/lib64/slurm/job_submit_lua.so`.  

I don't have direct experience using it; if you do and wanted to kick the tires, you can grab the updated build from our working factory for the next release:

http://build.openhpc.community/OpenHPC:/1.3:/Update5:/Factory/CentOS_7/

**Comment by koomie** [comment]
Additional test to check for installation of `job_submit_lua` plugin is running successfully in CI.
