### ISSUE TITLE
Slurm should include the jobcomp_elasticsearch plugin

### ISSUE THREAD

**Issue by LaHaine** [openhpc/ohpc#698]
Please enable the jobcomp_elasticsearch plugin in slurm-ohpc. Version 17.11.5-20.2 for CentOS 7.4 doesn't have it. Adding the build dep of curl-devel to the spec file will add it to the build.

**Comment by koomie** [comment]
Sorry this got dropped during one of the slurm upgrades. Will be adding a test to verify the plugin is available for future releases.

**Comment by koomie** [comment]
Additional test to check for installation of `jobcomp_elasticsearch` plugin is running successfully in CI.
