### ISSUE TITLE
warewulf stateful regression

### ISSUE THREAD

**Issue by crbaird** [openhpc/ohpc#700]
A patch introduced in the packaging of warewulf-provision included with OpenHPC 1.3.4 release causes a previous patch to become ineffectual, resulting in parted failing to partition disks during stateful provisioning.

**Comment by renatopancheri** [comment]
Encountered the same problem (parted not working after update),
i solved this issue by downloading the source rpm and rebuilding it with rpmbuild --rebuild.

rpm with parted patch not applied:
http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7/aarch64/warewulf-provision-ohpc-3.8pre-33.1.aarch64.rpm
rpm used to rebuild:
http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7/src/warewulf-provision-ohpc-3.8pre-33.1.src.rpm

**Comment by crbaird** [comment]
tests passing in CI
