### ISSUE TITLE
Spack and module file templates

### ISSUE THREAD

**Issue by svenevs** [openhpc/ohpc#715]
Hello,

I am opening this ticket on behalf of a user of OpenHPC and spack, since I believe I found the underlying problem.  The [issue was reported to spack](https://github.com/spack/spack/issues/8019) but seems to be a packaging problem here.  I have never written an RPM spec, but I believe this line is the problem

https://github.com/openhpc/ohpc/blob/8980aee13c3ab9507f0d6565dcd4bb09c36271dc/components/dev-tools/spack/SPECS/spack.spec#L58

```console
$ spack> find . -type d -maxdepth 1
./.git      # ?? Exclude?
./bin       # GOOD
./etc       # GOOD
./lib       # GOOD
./opt       # IGNORED (this should be correct)
./share     # GOOD (?)
./templates # (!) missing
./var       # GOOD
```

- `.git`: since it is a folder, I don't think you need to explicitly ignore it.  I imagine syncing the `.git` folder is a recipe for disaster, but is it included in the installation?
- `opt/`: this is where `spack` installs everything, leaving that alone is definitely the right thing to do
- `share`: this is where `spack` installs the module files (e.g. `share/spack/modules/{arch}` for TCL).  I'm not sure how this plays with OpenHPC though, since it seems the patch included changes where module files are installed so maybe this is a non-issue.
- `templates`: I think you just need to add `templates` to the `rsync` command

I hope that helps shed some light.  I know a decent amount about `spack`, but am far from an expert, and I know nothing about OpenHPC.  The only thing that is clear is that the `templates` folder is skipped and needs to be added for users to be able to generate / regenerate their modules using `spack`.

**Comment by crbaird** [comment]
ref 0701c8dd8

**Comment by crbaird** [comment]
tests passing in CI
