### ISSUE TITLE
BeeGFS (v7.1.2)

### ISSUE THREAD

**Issue by crbaird** [openhpc/ohpc#751]
https://www.beegfs.io/content/latest-release/

**Comment by crbaird** [comment]
server updated on sms016

**Comment by koomie** [comment]
CI tests updated to account for slight difference from stdout when querying stripe count.

**Comment by koomie** [comment]
client/server for CI tests updated to use 7.x version. After slight tweak to account for stdout changes, tests are passing in CI.
