### ISSUE TITLE
PBS Pro (v18.1.3)

### ISSUE THREAD

**Issue by scottaltair** [openhpc/ohpc#755]
Altair released PBS Professional 18.1.2 (https://github.com/PBSPro/pbspro/releases/tag/v18.1.2). PBS Professional 18.1.x a significant release from 14.1.x. The 18.1.2 release addresses upgrade issues from 14.1.0.

**Comment by scottaltair** [comment]
I have successfully built x86_64 and aarch64 with 18.1.2 source on the OBS.

**Comment by koomie** [comment]
tests passing in CI.
