### ISSUE TITLE
Packages that do not have ohpc string in them 

### ISSUE THREAD

**Issue by mrmhodak** [openhpc/ohpc#795]
Hello, 

I have noticed that there are rpm packages that do not contain ohpc string in  their name. These are:

pesign-obs-integration
pesign-obs-integration-debuginfo
lustre-iokit

**Comment by koomie** [comment]
The first two are provided by OBS and are related to kernel module signing. I will check on the lustre one.

**Comment by mrmhodak** [comment]
For the OBS packages, is it possible to rename them ?

The issue is that any package lacking "ohpc" string will not be updated using the recommended update procedure which looks for the string.

**Comment by mrmhodak** [comment]
SLES repo contains more rpms with no "ohpc" string in name:
mxml
libmxml1
hwloc*
libconfuse0
libconfuse-devel
libhwloc5
python-Cython

**Comment by jose-d** [comment]
at centos7 - ohpc 1.3.6:
- texlive-*
- latexmk-*
- mxml
- python-Cython

also without "ohpc" string.
