### ISSUE TITLE
UID/GID 200 not always available.

### ISSUE THREAD

**Issue by jlinford** [openhpc/ohpc#813]
@koomie, munge-ohpc hard-codes UID and GID 200 in munge.spec, but these ID's are not always available:

```
    146 %pre
    147 # karl.w.schulz@intel.com (9/10/18) - provide specific uid/gid to deal with
    148 # possibility of getting alternate ownership within Warewulf
    149 /usr/bin/getent group munge >/dev/null 2>&1 || \
    150   /usr/sbin/groupadd -r munge -g 200
    151 /usr/bin/getent passwd munge >/dev/null 2>&1 || \
    152   /usr/sbin/useradd -c "MUNGE authentication service" \
    153   -d "%{_sysconfdir}/munge" -g munge -s /bin/false -r munge -u 200
```

If a user or group with UID/GID 200 already exists then the package fails to install.  Ideally find a way to not hard-code UID/GID for munge, or if that isn't an option then at least add the `-o` flag to useradd/groupadd so the RPM will install.

Thanks!

**Comment by koomie** [comment]
Problem we run into is if you ever end up in a situation where the uid/gids are not consistent across the system. Don't have a magic solution for that gotcha, but can certainly add in the `-o` option.
