### ISSUE TITLE
qmgr not honoring set server default_qsub_arguments

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#858]
CI tests have identified the fact that latest PBS Pro build is no longer passing submission environment by using the global setting to embed "-v"

```
qmgr -c "set server default_qsub_arguments= -V"
```

The `qmgr` command does not error off but have confirmed that an interactive job is not propagating the submission environment.

**Comment by koomie** [comment]
@scottaltair, @mike0042 

It looks like we are encountering the same issue mentioned in https://github.com/PBSPro/pbspro/pull/781 with the v18.1.2 build of pbs pro. We'll need a fix for this to be able to use the newer version...

I tried the final patch mentioned in that PR, but it doesn't take directly against the v18.1.2 release. I can fix some of it (ie, we don't need the test portion at the end of the patch), but wasn't sure about the changes in `daemon_submit`. Can you generate a related patch which applies to the v18.1.2 release that we can apply for ohpc build?

Thanks.

**Comment by scottaltair** [comment]
@koomie, As you know, we have been exchanging a few emails on this topic. To bring those up to speed on the latest. 

Altair is proceeding with the option of providing a 18.1.3 release, which will address this issue (https://github.com/PBSPro/pbspro/pull/781) and a reservation oversubscription issue (https://github.com/PBSPro/pbspro/pull/791). Team is working on the timing to deliver.

**Comment by mike0042** [comment]
First of two PRs have been submitted: https://github.com/PBSPro/pbspro/pull/857

**Comment by mike0042** [comment]
The above PR is not passing QA at the moment, it is still in progress. The second issue appears to be addressed with a clean cherry pick here: https://github.com/PBSPro/pbspro/pull/861

**Comment by mike0042** [comment]
https://github.com/PBSPro/pbspro/pull/861 : PR has been merged
https://github.com/PBSPro/pbspro/pull/857 : PR has been fixed and is now out for review

**Comment by mike0042** [comment]
@koomie and @scottaltair,
https://github.com/PBSPro/pbspro/pull/857 has been approved and is awaiting merge, after which the release may be tagged.

**Comment by koomie** [comment]
Thanks for the update @mike0042 - am I understanding correctly that the net result is that we'll see a v18.1.3 release posted to the pbs pro github site shortly after merge?

**Comment by mike0042** [comment]
@koomie : Exactly. That will likely happen late tonight or early tomorrow since @subhasisb (in India) will perform the merge and tag the release.

**Comment by koomie** [comment]
awesome; I'll check in tomorrow am to see if it's out and update the ohpc build right away so we can get CI testing updated.

**Comment by mike0042** [comment]
Very good. Please let us know if you need anything else.

**Comment by koomie** [comment]
ohpc build updated to use v18.1.3. Basic interactive job test capability looks to be restored and first round of CI tests firing up now...

**Comment by koomie** [comment]
PBS jobs are now running again in ohpc recipes with latest v18.1.3 build. Thanks a bunch for the quick turn-around to resolve.
