### ISSUE TITLE
ipmiutil (v2.9.7)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#87]
just updated: http://ipmiutil.sourceforge.net/

**Comment by JohnWestlund** [comment]
@koomie We're not building this package, and the spec file isn't setup to grab an external source tarball. Is this a `distro-package` we should keep?

**Comment by koomie** [comment]
Oops, missed this one previously. It is not a dependency so we can definitely remove from the 1.1 milestone. I'm going to close this out and we can recreate if we need it in the future as a dependency.
