### ISSUE TITLE
Regression in slurm 17.11.10

### ISSUE THREAD

**Issue by LaHaine** [openhpc/ohpc#871]
According to the release notes of slurm 17.11.11, there is a regression introduced in slurm 17.11.10:

> These versions include a fix for a regression introduced in 18.08.1 and 17.11.10 that prevented the --get-user-env option from working correctly, alongside a few other minor changes.

Also, according to the release notes of slurm 17.11.12, another regression was fixed:
> These versions include a fix for a regression introduced in 18.08.2 and 17.11.11 that could lead to a loss of accounting records if the slurmdbd was offline.

See https://www.schedmd.com/news.php?id=211#OPT_211

**Comment by koomie** [comment]
slurm v18.08.6 will be rolled out with next ohpc version.
