### ISSUE TITLE
adios and buildrequires

### ISSUE THREAD

**Issue by adrianreber** [openhpc/ohpc#872]
Building adios seems difficult right now because it sets python-family to python2. This leads to a BuildRequires: python-numpy-gnu8-ohpc

which does not exist when building the OpenHPC packages outside of the official build system as numpy is built using python34.

I understand why it is done (because adios does not build with python3), but this seems like the wrong approach and only works if an numpy built with python2 exists.

**Comment by martin-g** [comment]
This issue seems related to https://github.com/openhpc/ohpc/pull/1635#issuecomment-1347905406

**Comment by adrianreber** [comment]
Yes, this can be closed.
