### ISSUE TITLE
Wrong dep on libcilkrts.so.5 in openmpi-intel-ohpc package

### ISSUE THREAD

**Issue by LaHaine** [openhpc/ohpc#875]
Several OpenHPC packages based on the Intel compiler have an automatically generated dependency on libcilkrts.so.5()(64bit) (on x86_64). On CentOS 7.5 the dep is resolved by pulling the package libcilkrts, but this doesn't exist on CentOS 7.6.

The dep should be filtered out at package build time, als not the system version of libcilkrts is used but the private copy in the intel directory at compilers_and_libraries/linux/lib/intel64/libcilkrts.so.5

I had noticed that when I tried to build a CentOS 7.6 + OpenHPC 1.3.6 installation:

```
--> Finished Dependency Resolution
Error: Package: openmpi-intel-ohpc-1.10.7-88.1.x86_64 (7extra_OpenHPC)
           Requires: libcilkrts.so.5()(64bit)
Error: Package: mvapich2-intel-ohpc-2.3-45.1.ohpc.1.3.6.x86_64 (7extra_OpenHPC)
           Requires: libcilkrts.so.5()(64bit)
Error: Package: openmpi3-intel-ohpc-3.1.2-13.2.ohpc.1.3.6.x86_64 (7extra_OpenHPC)
           Requires: libcilkrts.so.5()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by koomie** [comment]
Thanks for this report.

**Comment by koomie** [comment]
Looking at this again - I'm not sure I grok this 100%. This libcilkrts.so dependency does need to be resolved by a locally installed copy of intel mpi (not the distro).  For example, from a 2018 version, it's resolved with `libcilkrts intel-comp-ps-ss-bec-18.0.3-222`.  Did you have a copy installed locally and did you also have the `intel-mpi-devel-ohpc` compatibility package installed.

**Comment by LaHaine** [comment]
I don't have the original Intel RPMs installed as the compiler is installed on a shared file system.  I don't have intel-mpi-devel-ohpc installed as I don't have Intel MPI. So I guess I have to update my compatibility package.

**Comment by koomie** [comment]
Oops - I realize I misspoke above saying you need a copy of impi; apologies for my confusion. You are talking about `openmpi-intel1` (or `openmpi3-intel` in recent releases), so you should only require an install of the intel compiler. So, please disregard the comment about needing `intel-mpi-devel-ohpc` in this case. Instead, you should just need the compiler compatibility package: `intel-compilers-devel-ohpc`.  Do you have that and a version of the compiler installed locally?

I double checked on a system locally in a vanilla centos7.6 environment and the dependency resolution was ok for me. In this case, I installed a recent copy of the compiler (`parallel_studio_xe_2019_update1_composer_edition` in my case), but no MPI. Then, I installed `intel-compilers-devel-ohpc` followed by `openmpi3-intel-ohpc`.

**Comment by LaHaine** [comment]
Yes, I couldn't install intel-compilers-devel-ohpc and I had to replace it with a wrapper. So it was entirely my problem.
