### ISSUE TITLE
v1.3.6 upgrade docs don't mention "warewulf-provision-initramfs-x86_64-ohpc"

### ISSUE THREAD

**Issue by phpHavok** [openhpc/ohpc#883]
The package `warewulf-provision-initramfs-x86_64-ohpc` is required for running wwbootstrap in v1.3.6, otherwise you get the error:
```
Integrating the Warewulf bootstrap: 3.10.0-862.el7.x86_64
Including capability: setup-ipmi
ERROR:  Could not locate the Warewulf bootstrap 'base' capability
Done.
```
However, this package is not mentioned in the upgrade notes for v1.3.6.

**Comment by crbaird** [comment]
tests passing in CI
