### ISSUE TITLE
genders support for pdsh

### ISSUE THREAD

**Issue by jabl** [openhpc/ohpc#885]
Seems the genders support for pdsh is no longer included. Apparently it was added as a response to  https://github.com/openhpc/ohpc/issues/159

Per

https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.7_Factory/components/admin/pdsh/SPECS/pdsh.spec

there is a mod-genders rpm, but it's not present in the ohpc yum repo.

Would it be possible to enable the creation of mod-genders as part of building pdsh and add it to the repo?

**Comment by crbaird** [comment]
OBS was choking on some eccentricities of the original spec file. An optional slurm-mod-genders-ohpc package will show up in OHPC 1.3.7.

**Comment by jabl** [comment]
Great, thanks!

**Comment by crbaird** [comment]
Integration is optional, but build and install are functional in CI.
