### ISSUE TITLE
PLASMA (17.1)

### ISSUE THREAD

**Issue by crbaird** [openhpc/ohpc#919]
https://bitbucket.org/icl/plasma

**Comment by adrianreber** [comment]
There are much newer versions of plasma available at: https://bitbucket.org/icl/plasma/downloads/

@crbaird  any reason you selected 17.1 and not the latest?

**Comment by adrianreber** [comment]
Looking more at plasma it changed completely and maybe it would be better to stay at 2.8.0 for now. Their README contains the following sentence:

> PLASMA  is in the process of porting form QUARK to OpenMP. At the same time, it is moving from its ICL SVN repository to this Bitbucket Mercurial repository. The content of this repository reflects the progress of the transition. Before the transition is complete, the last release of the old PLASMA is available here: https://bitbucket.org/icl/plasma/downloads/plasma-2.8.tar.gz

I tested a few of the new versions and I was not able to build any of those versions. It seems configuring is only possible in interactive mode and the requirements are not listed at all. One of the errors I see is "make: *** No rule to make target `tools/lua-5.3.4.tar.gz', needed by `tools/lua-5.3.4/src'.  Stop." without any mentions that it needs the lua source code for building. Maybe it is too early to switch to one of the new versions.

**Comment by koomie** [comment]
Ok makes sense to hold off on this till it's more stable. Thanks for digging into it.
