### ISSUE TITLE
ohpc-base-compute depends on cairo-devel

### ISSUE THREAD

**Issue by jabl** [openhpc/ohpc#922]
Hi,

trying to reduce the size of my images, I noticed that ohpc-base-compute depends on cairo-devel:

<pre><code># repoquery --requires ohpc-base-compute
binutils
cairo-devel
libicu
libpciaccess
libunwind
numactl
python34
</code></pre>

Is this intentional, or could that dependency be removed?

**Comment by crbaird** [comment]
Hi Janne -
   Both cairo-devel and libpciaccess were added to the base compute image
as dependencies of hwloc. We couldn't strictly rely on RPM dependency
resolution, as the main hwloc-ohpc package is only installed on the master
node.

Cheers,
Reese
