### ISSUE TITLE
Warewulf network device in provision.conf

### ISSUE THREAD

**Issue by specificimpulses** [openhpc/ohpc#932]
I was getting this error when adding nodes to a new OHPC install:  

headnode# wwsh -y node new c001 --ipaddr=11.1.1.001 --hwaddr={removed} -D eth0
WARNING:  Could not configure DHCP, check 'network device' configuration!
WARNING:  Could not generate hostfile, check 'network device' configuration!
WARNING:  Could not generate PXE configurations, check 'network device' configuration!

The cause turned out to be a blank space after the interface name in /etc/warewulf/provision.conf

&#35; What is the default network device that the master will use to
&#35; communicate with the nodes?
network device = eno1 <---- hours of frustration from a single space here!!!

**Comment by jmstover** [comment]
Hello!! Let me welcome you to the... fun? enjoyment? excitement? ... whatever it is, that this behavior causes.

At the root, it's because we have a sing controlling object to parse configuration files (`Warewulf::Config`). It's used like:

```perl
my $config = Warewulf::Config->new('provision.conf');
my $defnet = $config->get("network device");
my $defkargs = $config->get("default kargs");
```

Because we have values that _include_ spaces (like for `default kargs`, we read to EOL. In other words... 

```
^network device = eno1 $
```

So, if there's a space in a value, it becomes part of the value that's read (I mean, it may be important right?). Which may not be exactly what someone wants to happen if there shouldn't be a space on the value.

**Comment by amblakem** [comment]
> So, if there's a space in a value, it becomes part of the value that's read (I mean, it may be important right?).

Is that ever true of trailing whitespace though?  Is there any reason not to just chomp() the variable once it's been read in?

**Comment by specificimpulses** [comment]
Thanks for the quick response and the welcome!  I built my first Perceus cluster more years ago than I want to admit, but I'm still learning new stuff every day for sure. :)

Your explanation totally makes sense, but is there a case for having arguments after the network device name?  If so then could you add a bit more debugging output for this error?  When I searched on what I was seeing it looked like there were several possible causes, but I didn't see anyone reporting this one.

Regardless, my fumble is now in the collective Git consciousness so I'm fine with closing the issue.

**Comment by jmstover** [comment]
> Is that ever true of trailing whitespace though? Is there any reason not to just chomp() the variable once it's been read in?

There are cases where a trailing space _can_ be used. Generally that's only if you're digging into the guts and not everyday usage.

But it's really important on the "password" entries. I have had passwords with the last character being a space, and blindly doing a `chomp()` doesn't make those happy. 

But, we are expecting the return values as the are. We use it a few times like:

See:  `50-network.init`
```perl
perl -MWarewulf::Network -MWarewulf::Config \
  -e 'print Warewulf::Network->new()->netmask(Warewulf::Config->new("provision.conf")->get("network device"));'
```

So, we're grabbing the values directly from the config as parameters.

**Comment by amblakem** [comment]
Gotcha, that makes sense.  @jmstover thank you for pointing this out.
