### ISSUE TITLE
ganglia-ohpc should depend on shadow-utils

### ISSUE THREAD

**Issue by omula** [openhpc/ohpc#938]
The package ganglia-ohpc should depend on shadow-utils because on the %pre has a useradd.

**Comment by koomie** [comment]
Updated to call out `shadow-utils` (centos) and `shadow` (sles) as a (pre) Requires dependency.
```
# rpm -qp --requires ganglia-ohpc-3.7.2-26.1.ohpc.1.3.7.x86_64.rpm | grep shadow
shadow-utils
```
