### ISSUE TITLE
singleton behavior changed with latest MPICH/ch4

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#940]

**Comment by koomie** [comment]
@raffenet, by any chance would you have thoughts on a change in behavior I'm seeing as we're trying to roll out an MPICH build using ch4 device?  For testing singleton execution of MPI applications in the past on a login node, we've just executed the binary directly.  That has worked with all the mpi variants we've been building in the past (including mpich/ch3), but I'm seeing an error with our newer mpich build. I can run with `mpiexec.hydra` but not the binary directly.

Here is a quick example.

##### centos7.6 host with mpich 3.3/ch4, simple MPI hello world

```
[karl@sms001 ~]$ which mpicc
/opt/ohpc/pub/mpi/mpich-gnu8-ohpc/3.3/bin/mpicc

[karl@sms001 ~]$ mpichversion 
MPICH Version:    	3.3
MPICH Release date:	Wed Nov 21 11:32:40 CST 2018
MPICH Device:    	ch4:ofi ucx
MPICH configure: 	--prefix=/opt/ohpc/pub/mpi/mpich-gnu8-ohpc/3.3 --with-device=ch4:ofi,ucx
MPICH CC: 	gcc    -O2
MPICH CXX: 	g++   -O2
MPICH F77: 	gfortran   -O2
MPICH FC: 	gfortran   -O2
MPICH Custom Information: 	

[karl@sms001 ~]$ mpicc --version
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


[karl@sms001 ~]$ mpicc /opt/ohpc/pub/examples/mpi/hello.c 
```

##### error if run binary directly:

```
[karl@sms001 ~]$ ./a.out 
[mpiexec@sms001] match_arg (utils/args/args.c:163): unrecognized argument pmi_args
[mpiexec@sms001] HYDU_parse_array (utils/args/args.c:178): argument matching returned error
[mpiexec@sms001] parse_args (ui/mpich/utils.c:1642): error parsing input array
[mpiexec@sms001] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1694): unable to parse user arguments
[mpiexec@sms001] main (ui/mpich/mpiexec.c:148): error parsing parameters
```

##### ok if launch with hydra

```
[karl@sms001 ~]$ mpiexec.hydra ./a.out 

 Hello, world (1 procs total)
    --> Process #   0 of   1 is alive. -> sms001
```

**Comment by koomie** [comment]
Found mention of the same at https://github.com/pmodels/mpich/issues/3542.  I

**Comment by raffenet** [comment]
Yes, this is a regression from ch3. I just posted a patch that will hopefully resolve the issue.

**Comment by koomie** [comment]
Resolved with newer mpich version. Enabling ch4 in 2.0 RC.
