### ISSUE TITLE
intel-imb - MPI Benchmarks (v2019.2)

### ISSUE THREAD

**Issue by amblakem** [openhpc/ohpc#946]
The Intel MPI benchmarks version 2019.2 is available.  Going forward, the release tarballs will have a new naming convention (https://github.com/intel/mpi-benchmarks/issues/15).

**Comment by koomie** [comment]
Expecting build fix in upstream release and we can revisit this when that's available.

**Comment by jcsiadal** [comment]
Upgrading to v2019.6.

**Comment by amblakem** [comment]
Fixed in #1192
