### ISSUE TITLE
OT: Main site is down

### ISSUE THREAD

**Issue by ftarlao** [openhpc/ohpc#949]
I post here because, I cannot find other contacts :-)

The main site [openhpc.community](https://openhpc.community/) is down  at least since one ore two days, from Italy (fastweb ISP). DNS name resolution seems to work fine, perhaps your VPS is down. 
Regards

**Comment by koomie** [comment]
Thanks for the report. We'll look into it - I know the Wordpress site was updated, but it was cooperating before the weekend.

**Comment by crbaird** [comment]
It should be accessible now. Thanks for the report

**Comment by ftarlao** [comment]
Yes, it works now. Tnx
