### ISSUE TITLE
Singularity broken after update in OHPC 1.3.7 due to wrong file permission

### ISSUE THREAD

**Issue by pmargara** [openhpc/ohpc#951]
After upgrading from OpenHPC 1.3.6 to OpenHPC 1.3.7, Singularity was updated from 2.6 to 3.1. When I try to start a shell in my container i get the following error message:

```
 # singularity shell <container>
 WARNING: container does not have /.singularity.d/actions/shell, calling /bin/sh directly
```

The container ran fine under singularity 2.6

After a simple chmod +x on these files/directories the problem was fixed:

- /opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/actions
- /opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/cgroups
- /opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/network
- /opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/seccomp-profiles
- /opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/actions/exec
- /opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/actions/run
- /opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/actions/shell
- /opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/actions/start
- /opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/actions/test

I've checked the %file section of the singularity spec file inside ohpc and the whole "$sysconfdir/singularity/actions/* was set to 644 as follow:
```
%attr(0644, root, root) %config(noreplace) %{install_path}/etc/singularity/*
```
This is a very different behaviour from the one contained in the spec file present in the Singularity repo [https://github.com/sylabs/singularity/blob/master/dist/rpm/singularity.spec.in](https://github.com/sylabs/singularity/blob/master/dist/rpm/singularity.spec.in)

Problems releated to this issue was already discussed in user mailing list: [https://groups.io/g/OpenHPC-users/topic/30750144](https://groups.io/g/OpenHPC-users/topic/30750144)

**Comment by adrianreber** [comment]
I tried to fix it by using the file permissions from upstream's spec file. Could you try the RPM at:

https://copr-be.cloud.fedoraproject.org/results/adrian/ohpc/epel-7-x86_64/00876533-singularity-ohpc/singularity-ohpc-3.1.0-1.ohpc.1.3.6.x86_64.rpm

to see if that fixes the errors you have seen.

**Comment by pmargara** [comment]
I've replaced the old rpm with the new one and now the warning is not showed, I've checked the permissions in _/opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/_ and now they are setted correctly.

There is a thing not related to the bug that I find strange: the two packages, the rebuilded one and the official one published on the repo, even if they should have the same name they have a different one. Yours package name is _singularity-ohpc-3.1.0-1.ohpc.1.3.6.x86_64_ the one published on the repo is named  _singularity-ohpc-3.1.0-29.1.ohpc.1.3.7_ ([http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7/x86_64/singularity-ohpc-3.1.0-29.1.ohpc.1.3.7.x86_64.rpm](http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7/x86_64/singularity-ohpc-3.1.0-29.1.ohpc.1.3.7.x86_64.rpm)).
If I look at the two spec file, [https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.7_Factory/components/runtimes/singularity/SPECS/singularity.spec](https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.7_Factory/components/runtimes/singularity/SPECS/singularity.spec) and the one contained into [http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7/src/singularity-ohpc-3.1.0-29.1.ohpc.1.3.7.src.rpm](http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7/src/singularity-ohpc-3.1.0-29.1.ohpc.1.3.7.src.rpm), they are not the same file. For exemple the _Release_ value change from _1%{?dist}_ to _29.1.ohpc.1.3.7_ and this is why the two rpms have a different name. 
This is expected or something went missing during a previous commit?

Last but not least: considering that this is a fix, it's possible to have the package with this issue fixed on the 1.3.7 release repo?

**Comment by adrianreber** [comment]
> I've replaced the old rpm with the new one and now the warning is not showed, I've checked the permissions in _/opt/ohpc/pub/libs/singularity/3.1.0/etc/singularity/_ and now they are setted correctly.

Thanks for testing.

> There is a thing not related to the bug that I find strange: the two packages, the rebuilded one and the official one published on the repo, even if they should have the same name they have a different one. Yours package name is _singularity-ohpc-3.1.0-1.ohpc.1.3.6.x86_64_ the one published on the repo is named _singularity-ohpc-3.1.0-29.1.ohpc.1.3.7_ (http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7/x86_64/singularity-ohpc-3.1.0-29.1.ohpc.1.3.7.x86_64.rpm).
> If I look at the two spec file, https://github.com/openhpc/ohpc/blob/obs/OpenHPC_1.3.7_Factory/components/runtimes/singularity/SPECS/singularity.spec and the one contained into http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7/src/singularity-ohpc-3.1.0-29.1.ohpc.1.3.7.src.rpm, they are not the same file. For exemple the _Release_ value change from _1%{?dist}_ to _29.1.ohpc.1.3.7_ and this is why the two rpms have a different name.
> This is expected or something went missing during a previous commit?

That is expected. The official OpenHPC build system (Opensuse build system) has some implicit rules to make rebuilds easier by auto incrementing the release field.

I am doing my test builds in Fedora's COPR which works differently.

> Last but not least: considering that this is a fix, it's possible to have the package with this issue fixed on the 1.3.7 release repo?

@koomie can we get this change into 1.3.7 as an update?

**Comment by koomie** [comment]
Let me look into pushing a quick update.

**Comment by koomie** [comment]
@pmargara, an updated build with the perm changes is now available in a branch of the ohpc build system. The corresponding repo is at http://build.openhpc.community/OpenHPC:/1.3:/Update7:/U1/CentOS_7/ or you can `wget` the desired RPM and install locally. 

I want to discuss this update briefly at our steering committee meeting next week, but wanted to let you know of it's availability. If you can possibly have a chance to confirm this latest build locally (it will have an increased release number, so you should be able to upgrade), that would be great.

**Comment by pmargara** [comment]
I've added the corresponding temporary repo and executed `yum update`, the package was updated without problem and everything is running fine. Thanks!

**Comment by koomie** [comment]
Excellent - thanks for trying it out.

**Comment by koomie** [comment]
Updated package builds are now live as part of 1.3.7 Updates repository.
