### ISSUE TITLE
EPEL moving to python 3.6

### ISSUE THREAD

**Issue by jabl** [openhpc/ohpc#953]
EPEL has recently introduced python36* packages, though it seems the old python34* are still kept around for compatibility. But in particular, `/usr/bin/python3` is now provided by the python36 package, whereas the python34 package only provides `/usr/bin/python3.4`

For OpenHPC it would thus make sense to switch all the python 3 packages from 3.4 to 3.6 as well.

See https://www.mail-archive.com/epel-devel@lists.fedoraproject.org/msg06502.html

**Comment by adrianreber** [comment]
Closing as this no longer seems relevant with 2.x and 3.x.
