### ISSUE TITLE
PLASMA (v18.11.1)

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#987]
https://bitbucket.org/icl/plasma

**Comment by koomie** [comment]
@adrianreber; I know you looked at a newer plasma version before in #919 and there were build issues at the time. Do you want to take another look with their latest v18.11.1 release and see if it might be in better shape?

**Comment by adrianreber** [comment]
@koomie : sure, makes sense as I already had a look at it.

**Comment by koomie** [comment]
Builds complete in OBS.

**Comment by koomie** [comment]
@adrianreber, we are seeing CI failures with this build of the latest plasma version. One gotcha is the lack of an f90 module interface to link against. Looking at the cmake log from the build, and futzing with it some more locally, it's not obvious to me that the cmake setup has any support to enable the fortran interface.

There are some linkage issues with our previous C tests too, but given the fortran issue I wonder if we should continue to hold off on this and keep the previous variant?

**Comment by adrianreber** [comment]
@koomie : reverting sounds right. Upstream still seems not really ready with their changes. I was kind of surprised myself when it actually did build. There does not seem to be much documentation and everything I did required looking at the cmake definitions. Let's use the old version.

**Comment by koomie** [comment]
Ok thanks - I reverted back.
